Modernize users page - stop using bootstrap classes and start using PF4 components instead
cockpit-project/cockpit pull request #14517
Opened 2020-08-27 11:53 UTC by KKoukiou

2020-08-27 14:22 UTC, ahmedmgh67 commented
This looks nice hope it gets merged and the other page get a redesign to be like this

2020-08-27 14:24 UTC, KKoukiou commented
> This looks nice hope it gets merged and the other page get a redesign to be like this

Yes, I am working in parallel on the rest as well. I think the majority of the pages will be ready with the new design within next release (next week)

2020-08-27 14:47 UTC, andreasn requested changes
Need some left padding here. Much closer to the left edge than the other pages, and compared to the [Patternfly examples](https://www.patternfly.org/v4/documentation/react/demos/primarydetail/primary--detail-full-page)
![Screenshot from 2020-08-27 16-14-17](https://user-images.githubusercontent.com/209895/91455987-0b875600-e883-11ea-8b62-5e83a28a2d5c.png)

A bit low contrast. Think it needs darker lines and have them go all the way to the edge.
![Screenshot from 2020-08-27 16-36-55](https://user-images.githubusercontent.com/209895/91456456-9700e700-e883-11ea-8af2-fc5ad75b9a6e.png)

So this didn't align before either, so not a regression in that sense, but now it's shifted to the other side. Will look super-clean if lined up, so if you're able to address that in this PR as well, it would be a very nice bonus!
![Screenshot from 2020-08-27 16-37-11](https://user-images.githubusercontent.com/209895/91456642-ce6f9380-e883-11ea-934e-e9e06f477e2b.png)

The layout has problems if the parent window is less than 600px, but so did the old one, so not a regression, and can be fixed in a separate PR.
![Screenshot from 2020-08-27 16-46-24](https://user-images.githubusercontent.com/209895/91457658-e1cf2e80-e884-11ea-929a-aaec0bcfb739.png)

The listing of authorized keys in the same resolution did regress though. The **+** and **-** buttons used to be visible, but now they get hidden.
![Screenshot from 2020-08-27 16-46-52](https://user-images.githubusercontent.com/209895/91457700-ef84b400-e884-11ea-9c2a-84c792329a3f.png)

2020-08-28 16:23 UTC, andreasn commented
Captured the (already existing) issue with the form in issue #14522

2020-09-01 09:01 UTC, garrett requested changes
Looks great overall.

I'd like the cards changed to use a heading and also to use the document order for the actions (so they come after the title, instead of before).

2020-09-01 09:01 UTC, garrett commented on pkg/users/account-details.js
> +                            <CardTitle id="account-title">{title_name}</CardTitle>
The cart titles should probably have a heading inside.

Also, the actions should come after the titles, not relying on changing the order via CSS. (It's important to have document order for all types of a11y: keyboard navigation, screen reader, etc.)

2020-09-01 09:01 UTC, garrett commented on pkg/users/account-details.js
> +                            <CardTitle id="account-title">{title_name}</CardTitle>
(Same should apply to the other cards.)

2020-09-01 09:03 UTC, garrett commented
Additionally, we should adjust the lists at a top-level instead of each page. The SSH keys list doesn't have a border at the top, it has a border at the bottom, and there's padding around it that shouldn't be there. We keep running into the same things and have only fixed it at the page so far.

2020-09-01 09:04 UTC, KKoukiou commented on pkg/users/authorized-keys-panel.js
> +                <div className="pf-c-card__actions">
I copied the example in the DOCS which has it in this order, https://www.patternfly.org/v4/documentation/react/components/card#card-header-in-card-head

I understand what you say though, I will adjust our code and send a patch to PF as well.

2020-09-02 15:59 UTC, garrett commented
I squashed in a bunch of layout and small size fixes, so the page now wraps properly in smaller widths (narrow desktop, graphical VM @ 1024, mobile), force the key hashes to wrap when there's not enough space, and let the actions wrap under the title.

2020-09-02 16:06 UTC, garrett commented
BTW: I think I've addressed all of @andreasn's issues with my changes. Please re-test to be sure. Thanks!

2020-09-02 16:47 UTC, andreasn submitted a review, later dismissed
Thanks! Much better now!
I think my only last two concerns are:
1. The key empty state lacks some padding. Might also want to place it in the center, since it's a placeholder. but left-aligned works too.
![Screenshot from 2020-09-02 18-31-06](https://user-images.githubusercontent.com/209895/92011958-17c05700-ed4c-11ea-950b-257a6c94d8de.png)

2. It seems the SHA-columns doesn't line up, like it does in master, but are dependant on the length of the key name.
![Screenshot from 2020-09-02 18-44-22](https://user-images.githubusercontent.com/209895/92012474-c795c480-ed4c-11ea-99bf-6d17eff8e4aa.png)

2020-09-03 05:28 UTC, marusak commented
Looks great UI and code wise, thanks!

One issue I noticed is that the password strength is not filled when creating a new account (those 4 bars). They are used when changing password. Not sure if regression or broken on master.
![notfilled](https://user-images.githubusercontent.com/12330670/92074678-f5175800-edb6-11ea-9377-7ab60a0b0417.png)

2020-09-03 05:32 UTC, marusak submitted a review, later dismissed
Ok, happens on master as well. Reported as https://github.com/cockpit-project/cockpit/issues/14558
Approving, there are two issues from Andreas, but it might be for followup as it likely comes from a library.

2020-09-03 06:55 UTC, KKoukiou commented
> Looks great UI and code wise, thanks!
> 
> One issue I noticed is that the password strength is not filled when creating a new account (those 4 bars). They are used when changing password. Not sure if regression or broken on master.
> ![notfilled](https://user-images.githubusercontent.com/12330670/92074678-f5175800-edb6-11ea-9377-7ab60a0b0417.png)

It's filled just you have to try harder :) When minimum strength there is no line filled.

2020-09-03 08:00 UTC, garrett commented
> The key empty state lacks some padding. 

Aaah! I forgot to check a non-me user.

> SHA-columns doesn't line up

This is a flex for some reason, not a table or a grid. It seems PF likes to use non-table `<div>`s to fake tables.

I'm looking into both of these now. Thanks for finding them!

2020-09-03 11:07 UTC, marusak commented
> When there's content, it should fill at least one bar. 

Fixed in #14559

2020-09-03 12:22 UTC, garrett commented
I've pushed a change that improves the layout for list items and handles the empty state.

For browsers were subgrid is supported and the browser width is wide enough (512px wide in the iframe), I added a grid and brought it down through the children to align the key list cells to the grid, so that they're interdependent and take each other's sizes into account. Currently, only Firefox supports subgrids, so this only applies when you're viewing it in Firefox on the desktop.

For the fallback case and where subgrid is not supported (Chromium and WebKit based browsers as-of this writing), I messed with the flex values, using flex basis, so that it's approximately correct in typical scenarios. Also, this does not affect mobile and very small desktop sizes, where the items still stack.

It's in a separate commit as it's useful to see what I changed and we might want to re-adjust it before landing this PR. (Hopefully it works for everyone and we can just land this. :wink:)

2020-09-03 13:49 UTC, andreasn approved these changes
Subgrid doesn't work on Chrome (yet), but I think it's OK for now. Not too jarring. So good to go!

2020-09-03 15:44 UTC, merged