Stop using .container-fluid and .breadcrumb bootstrap classes
cockpit-project/cockpit pull request #14537
Opened 2020-08-31 15:42 UTC by KKoukiou

2020-09-01 12:08 UTC, KKoukiou commented
@marusak @martinpitt can any of you review this one? It's an easy one

2020-09-01 12:12 UTC, marusak commented
I'll take this one.

2020-09-01 12:31 UTC, marusak commented
Looking at the UI first.
- in graphs there are two issues - There is no `>` between `Overview` and the subsequent item, and the other `>` is not spaced properly.
![broken](https://user-images.githubusercontent.com/12330670/91850978-b8d0e400-ec5e-11ea-9a9a-da4e5ec61be0.png)

- it feels misaligned on services page: (the same with applications, hardware details, virtual machines)
![servicesmissaligned](https://user-images.githubusercontent.com/12330670/91851192-0b120500-ec5f-11ea-8b3e-27474889357b.png)
(at least when compared to logs (networking, storage...) (plus the `>` is bold on those pages)
![logscompared](https://user-images.githubusercontent.com/12330670/91851280-2d0b8780-ec5f-11ea-9650-81fdf483b044.png)

- the spacing on accounts feels wrong (at least not consistent with the rest of the cockpit)
![acountspacing](https://user-images.githubusercontent.com/12330670/91851345-4dd3dd00-ec5f-11ea-8ff1-ab9959158658.png)

2020-09-01 12:38 UTC, KKoukiou commented
@marusak I think both issues you mentioned are issues in master and are not caused by this PR.

2020-09-01 15:58 UTC, KKoukiou commented
I will address the issues you mentioned and repost.

2020-09-02 11:51 UTC, KKoukiou commented
@marusak I fixed both issues you found in another PR, which is already merged, and rebased. https://github.com/cockpit-project/cockpit/pull/14550

Can you please re-review?

2020-09-03 12:07 UTC, marusak requested changes
One regression unfortunately.

2020-09-03 12:13 UTC, KKoukiou commented on pkg/kdump/kdump-view.jsx
> +import { Button, Tooltip, TooltipPosition, Page, PageSection, PageSectionVariants } from "@patternfly/react-core";
Good catch, reposting.

2020-09-03 12:32 UTC, KKoukiou commented on pkg/kdump/kdump-view.jsx
> +import { Button, Tooltip, TooltipPosition, Page, PageSection, PageSectionVariants } from "@patternfly/react-core";
btw I just noticed that this page is broken on mobile, even on master, it does not wrap at all. I will send another PR for fixing this.

2020-09-03 17:39 UTC, marusak approved these changes
Awesome, thanks!

2020-09-03 17:39 UTC, merged