test: Add some checks about OS input on the creation and import disk dialog
cockpit-project/cockpit pull request #14644
Opened 2020-09-21 18:26 UTC by yunmingyang

2020-09-24 06:06 UTC, martinpitt submitted a review, later dismissed
Thanks @yunmingyang : I converted this to Draft, as the new test still fails. Also, can you please add "Closes #14644" to the topmost commit message on next push? Cheers!

2020-09-24 06:31 UTC, yunmingyang commented
@martinpitt Thanks! I will add it on next push. Then I checked the fails, and found that 'Ctrl + a' in the set_input_text did not take effect. I guess maybe this is related with the version of chromium, so what is the version of chromium in our auto triggered tests? If I get the version I think I can try to reproduce in my laptop.

2020-09-25 07:57 UTC, martinpitt commented
@yunmingyang : The current [cockpit/tasks container](https://hub.docker.com/r/cockpit/tasks/tags/) has chromium 81. It's a bit old by now, the last container refresh was 3 months ago. If that is significant, we can certainly bump it again.

2020-10-08 09:07 UTC, KKoukiou requested changes

2020-10-08 09:07 UTC, KKoukiou commented on test/verify/check-machines
> +        def checkOsInput(self, dialog):
Can you please add a Test suffix to this function?

2020-10-08 09:08 UTC, KKoukiou commented
@yunmingyang unfortunately this is still failing https://logs.cockpit-project.org/logs/pull-14644-20201001-031320-f8b7ffec-fedora-32/log.html#235

2020-10-14 10:09 UTC, KKoukiou approved these changes

2020-10-15 06:57 UTC, merged