machines: Show all possible vm states in filtering section
cockpit-project/cockpit pull request #14667
Opened 2020-09-24 22:08 UTC by skobyda

In filtering section, use the same list of VM states we use when
defining a VM state in a store.

Fixes #14654

2020-09-24 22:10 UTC, skobyda commented
@garrett When I was working adding more states to a dropdown used for filtering, I noticed that dropdown may be too long and be cutoff. The problem is that `<div id="app">` does not resize for a dropdown. Do you know if there is any CSS solution to resize elements when dropdown is too large?
![Screenshot from 2020-09-24 23-52-39](https://user-images.githubusercontent.com/42733240/94205382-80ba6b00-fec3-11ea-916e-0f9ded6bd7b1.png)

2020-09-25 07:52 UTC, garrett commented
From the screenshot, I can tell that this is the result of two different issues: 
1. The page content isn't expanding to the full content area.
2. The dropdowns used are not the correct ones. They look like restyled PF3 dropdowns. Ideally, use PF4, especially [form select](https://www.patternfly.org/v4/documentation/react/components/formselect), if possible. As "form select" is actually using the native widget, it will always pop up over other elements.

Of course # 2 is not much of an issue if # 1 is fixed.

I'll be happy to fix this first issue next week, when I'm back at work. Please ping me about it if I forget. :wink:

2020-09-29 10:03 UTC, garrett commented
Hopefully this doesn't break tests. :wink:

(It's a more proper approach than my initial thought of setting `#app { height: 100% }`.)

2020-09-29 11:50 UTC, skobyda commented
Thanks, works fell. Now the filtering section looks like this. I'm also wondering if Shut off and Running, the two most used states, should be at the beginning of dropdown.
![Screenshot from 2020-09-29 13-48-52](https://user-images.githubusercontent.com/42733240/94554638-aac0b400-025a-11eb-8846-dad43fc437ce.png)

2020-09-30 05:59 UTC, marusak commented
@skobyda how much work it would be to generate this list dynamically from states that currently exist in the UI?
I feel like 'No state' is never gonna happen. Also states like 'Crashed' or 'Shutting down' would be very rare cases (the second one because it is just intermediate state). And as you wrote that you wonder if some states should be on the top of the list - if we would have only states that currently apply there would be no need to think what should be promoted.

2020-09-30 11:37 UTC, garrett commented
I agree about having running / shut off at the top, then a divider, then the rest of the states from the list.

If there's only running and shut off states, then drop the divider.

If there's only running or only shut off, it's debatable if we really want a 1 option dropdown. They're both common enough that perhaps we should _always_ have running and shut off states.

We could extend the 2 common states to 3 if we want to include paused in there. But the rest are mainly error states and should come later, certainly.

2020-10-02 12:58 UTC, skobyda commented
I updated it so that only states which are present in the VM list are shown and Running and Shut off are present at the beginning of the list. But there is no divider because I cannot find the proper way to use divider in PF4 Selector
![Uploading Screenshot from 2020-10-02 14-39-35.png…]()

2020-10-02 20:43 UTC, marusak requested changes
I haven't built this yet, but from the code it looks like if all VMs are in the same state that you still would have dropdown with [All, The_one_state]. That seems pointless. Could we not show the whole filter then? Also when there are no VMs at all.

Also tests seems unhappy, it might likely be related, can you please take a look? Thanks!

2020-10-02 20:43 UTC, marusak commented on pkg/machines/hostvmslist.jsx
> +        console.log(sortOptions);
forgotten debuging line

2020-10-02 20:43 UTC, marusak commented on pkg/machines/hostvmslist.jsx
> +        console.log(sortOptions);
forgotten debugging log

2020-10-03 08:58 UTC, skobyda commented
I updated it so that only states which are present in the VM list are shown and Running and Shut off are present at the beginning of the list. But there is no divider because I cannot find the proper way to use divider in PF4 Selector. Do you know the proper way?

![Screenshot from 2020-10-02 14-39-35](https://user-images.githubusercontent.com/42733240/94987541-5f164f00-0567-11eb-96bd-993d55892629.png)

2020-10-08 08:58 UTC, KKoukiou requested changes

2020-10-08 08:58 UTC, KKoukiou commented on pkg/machines/hostvmslist.jsx
> +                                    : <SelectOption key={index} value={{ ...option, toString: function() { return this.value } }} />
The Vm states need to be translated.

2020-10-12 09:23 UTC, garrett commented
Is that a PF4 select? It isn't styled like one in the screenshot. Odd.

On the first select demo, there's a divider:
https://www.patternfly.org/v4/components/select/react/

Excerpt (with one line context):

```jsx
...
        <SelectOption key={4} value="Ms" />,
        <Divider component="li" key={5} />,
        <SelectOption key={6} value="Dr" />,
...
```

2020-10-12 11:18 UTC, skobyda commented
> Is that a PF4 select? It isn't styled like one in the screenshot. Odd.
> 
> On the first select demo, there's a divider:
> https://www.patternfly.org/v4/components/select/react/
> 
> Excerpt (with one line context):
> 
> ```js-jsx
> ...
>         <SelectOption key={4} value="Ms" />,
>         <Divider component="li" key={5} />,
>         <SelectOption key={6} value="Dr" />,
> ...
> ```

Oh damn, but it has a bug. Try to go here https://www.patternfly.org/v4/components/select/react/,click on first select, select the last option and you will get TypeError: Cannot read property 'toString' of undefined. I get same error when I applied it here.

2020-10-12 11:19 UTC, skobyda commented
It seems they are fixing it: https://github.com/patternfly/patternfly-react/pull/4998

2020-10-12 11:20 UTC, KKoukiou commented
> > Is that a PF4 select? It isn't styled like one in the screenshot. Odd.
> > On the first select demo, there's a divider:
> > https://www.patternfly.org/v4/components/select/react/
> > Excerpt (with one line context):
> > ```
> > ...
> >         <SelectOption key={4} value="Ms" />,
> >         <Divider component="li" key={5} />,
> >         <SelectOption key={6} value="Dr" />,
> > ...
> > ```
> 
> Oh damn, but it has a bug. Try to go here https://www.patternfly.org/v4/components/select/react/,click on first select, select the last option and you will get TypeError: Cannot read property 'toString' of undefined. I get same error when I applied it here.

This issue has already being reported. https://github.com/patternfly/patternfly-react/issues/4945 
If you feel like fixing it I can help you get around the patternfly repository and testing tools.

2020-10-12 11:21 UTC, skobyda commented
> > > Is that a PF4 select? It isn't styled like one in the screenshot. Odd.
> > > On the first select demo, there's a divider:
> > > https://www.patternfly.org/v4/components/select/react/
> > > Excerpt (with one line context):
> > > ```
> > > ...
> > >         <SelectOption key={4} value="Ms" />,
> > >         <Divider component="li" key={5} />,
> > >         <SelectOption key={6} value="Dr" />,
> > > ...
> > > ```
> > 
> > 
> > Oh damn, but it has a bug. Try to go here https://www.patternfly.org/v4/components/select/react/,click on first select, select the last option and you will get TypeError: Cannot read property 'toString' of undefined. I get same error when I applied it here.
> 
> This issue has already being reported. [patternfly/patternfly-react#4945](https://github.com/patternfly/patternfly-react/issues/4945)
> If you feel like fixing it I can help you get around the patternfly repository and testing tools.

But there is already a fix for that. See my comment above.

2020-10-16 06:55 UTC, marusak commented
@skobyda Today we got https://github.com/cockpit-project/cockpit/issues/14759 which has very similar problem as you were fixing here. Can you please check if by that fix in this PR you fixed that issue? If so, can you please add Fixes line, if not would it make sense to fix it together for all dropdowns?
Thanks!

p.s. There are conflicts, can you also rebase?
p.s.2 Is this blocked on the aforementioned issue? Can we do something about it to unblock ourselves?

2020-10-20 10:03 UTC, KKoukiou approved these changes
Rebased because it has a merge conflict and force pushed. The PR looks good otherwise.

2020-10-20 20:26 UTC, marusak commented
Only testStoragePools is broken but that is unrealated and being fixed in https://github.com/cockpit-project/cockpit/pull/14778/commits/3f0e7ce6b1594ccfee7fa7e69d5110fc66637bb9

2020-10-20 20:27 UTC, marusak approved these changes

2020-10-20 20:27 UTC, merged