machines: Allow a space characters in arguments of virt-install
cockpit-project/cockpit pull request #14703
Opened 2020-10-05 13:01 UTC by skobyda

Closes #14524
Closes #9623

2020-10-08 08:48 UTC, KKoukiou requested changes
This rather needs a test case with a  disk && vm name with spaces in the name.

2020-10-08 08:48 UTC, KKoukiou commented on pkg/machines/scripts/install_machine.sh
> +    "$AUTOSTART_PARAM "|| handleFailure $?
Wrong spacing here after parameter, not that it matters but for consistency.

2020-10-13 19:04 UTC, KKoukiou reviewed
@skobyda this is only missing a test, otherwise I am happy with it

2020-10-28 18:31 UTC, skobyda commented
I added a test, it passes, and all the failures are flakes which I have seen in other cases. @KKoukiou can you give it another look?

2020-10-30 13:11 UTC, KKoukiou approved these changes

2020-10-30 13:13 UTC, merged