storage: Show spinner inside the buttons when operation is in progress
cockpit-project/cockpit pull request #14815
Opened 2020-10-27 09:49 UTC by KKoukiou

When an 'idle message' is presented show it in the same row with the
action buttons in the footer.

Before:

After: 
![Screen Shot 2020-10-27 at 10 47 05](https://user-images.githubusercontent.com/14921356/97284892-e478e080-1841-11eb-938e-72efc0920440.png)

Before:
![marius](https://user-images.githubusercontent.com/14921356/97285020-05413600-1842-11eb-961b-99886a3fdcd2.png)

2020-10-28 07:13 UTC, mvollmer commented on pkg/lib/cockpit-components-dialog.jsx
> +                isLoading={ this.state.action_in_progress || action.loading }
Doesn't this mean that the spinner is in _all_ action buttons? Ideally, it should be only in the one that created the current action promise.

2020-10-28 07:26 UTC, mvollmer requested changes
I don't like this as a layout fix, as it doesn't return us to the previous status quo.
It's a genuine UI change, and right now I am not liking it as a genuine UI change either. I need to be convinced, without release pressure. :-)

2020-10-28 07:39 UTC, mvollmer commented
> After:
> ![Screen Shot 2020-10-27 at 10 47 05](https://user-images.githubusercontent.com/14921356/97284892-e478e080-1841-11eb-938e-72efc0920440.png)

When clicking format, the dialog still expands a bit vertically to show more whitespace under the "Format" button.

2020-10-28 08:46 UTC, KKoukiou commented
> > After:
> > ![Screen Shot 2020-10-27 at 10 47 05](https://user-images.githubusercontent.com/14921356/97284892-e478e080-1841-11eb-938e-72efc0920440.png)
> 
> When clicking format, the dialog still expands a bit vertically to show more whitespace under the "Format" button.

Reverted back to the old design.

2020-10-29 12:06 UTC, mvollmer approved these changes
Nice!

2020-10-29 15:13 UTC, merged