test: rhel-8-4 supports firmware configuration
cockpit-project/cockpit pull request #14909
Opened 2020-11-16 16:54 UTC by marusak

Downstream sees this already. We don't see it due to https://github.com/cockpit-project/bots/pull/1394

Blocked until we get new refresh.

2020-11-16 19:11 UTC, marusak commented
https://github.com/cockpit-project/bots/pull/1396 have not reproduced this, maybe it was released just now, lets give this a week.

2020-11-17 09:54 UTC, KKoukiou submitted a review, later dismissed

2021-01-04 06:26 UTC, martinpitt requested changes
This looks like an old test PR, and is most certainly wrong. If 8.4 regresses there, it needs to be naughtied and reported.

2021-01-04 06:26 UTC, martinpitt commented on test/verify/check-machines
> +        supports_firmware_config = m.image in ['fedora-32', 'fedora-33', 'fedora-testing', 'rhel-8-3', 'rhel-8-3-distropkg', 'debian-testing', 'ubuntu-stable', 'ubuntu-2004']
This looks strange -- the effect is that rhel-8-4 would suddenly *stop* supporting firmware config. Also, by now we should certainly invert that list, I think debian-stable is the only remaining OS that does not support it. Such positive lists are prone to forgetting new ones.

2021-01-04 06:27 UTC, martinpitt commented
https://github.com/cockpit-project/bots/pull/1489 is also fine (just blocked on podman regresssion)

2021-01-04 06:27 UTC, closed without merging