overview: allow editing motd
cockpit-project/cockpit pull request #15037
Opened 2020-12-11 14:16 UTC by KKoukiou

Closes #8296

2020-12-12 07:14 UTC, marusak commented
I like your current motd :)

2020-12-12 09:55 UTC, marusak requested changes
Awesome! Thanks :)
Just two tiny comments

2020-12-12 09:55 UTC, marusak commented on test/verify/check-system-info
> +        b.wait_text('#motd', "Hello cockpit team")
Can you please check here that `/etc/motd` also contains this new text and it hasn't just changed in cockpit?

2020-12-12 09:55 UTC, marusak commented on pkg/systemd/overview-cards/motdCard.jsx
> +                                   aria-label="Action">
That is not a great label :) Can you put there something like `Edit motd` and don't forget to localize it as well.

2020-12-14 19:57 UTC, marusak requested changes

2020-12-14 19:57 UTC, marusak commented on pkg/systemd/overview-cards/motdCard.jsx
> +                                   aria-label={_("Edit motd")}
needs `>`, see all builds are failing:
```
ERROR in ../pkg/systemd/overview-cards/motdCard.jsx
Module build failed (from ../node_modules/babel-loader/lib/index.js):
SyntaxError: /home/user/cockpit-project/bots/make-checkout-workdir/pkg/systemd/overview-cards/motdCard.jsx: Unexpected token (78:31)

  76 |                                    })}
  77 |                                    aria-label={_("Edit motd")}
> 78 |                                <EditIcon />
     |                                ^
  79 |                            </Button>}
  80 |                            <AlertActionCloseButton onClose={this.hideAlert} />
  81 |                        </>} />
```

2020-12-15 16:21 UTC, marusak approved these changes
Thank you!

2020-12-15 16:22 UTC, merged

2020-12-15 17:47 UTC, garrett commented
Just saw this.

If you don't already have an MOTD, what happens?

And does it handle /etc/motd.d/?

2020-12-15 18:09 UTC, marusak commented
> If you don't already have an MOTD, what happens?

You cannot set it up. Also if you edit it and save empty message you won't be able to set it up to some other value. I thought about it, but that will require some additional design.

> And does it handle /etc/motd.d/?

We only show `/etc/motd` and not `/etc/motd.d/`.