Use sassc instead of node-sass
cockpit-project/cockpit pull request #15088
Opened 2021-01-04 11:26 UTC by KKoukiou

node-sass is a compiled ELF module, which is problematic for
distributions that want to rebuild everything from source. The sassc CLI
program is packaged everywhere, and both use the same libsass library.

So drop node-sass and sass-loader, and replace it with a simple loader
wrapper around sassc.

This also saves 122 npm packages (16 MB in node_modules/).

Ported from starter-kit commits 233b5cfe04142, 8821db1daf1, and 50ef8a93623.

Fixes #15068

2021-01-04 12:50 UTC, martinpitt requested changes
Niiice! Just a triviality, otherwise I'm eager to see the test results.

2021-01-04 12:50 UTC, martinpitt commented on HACKING.md
> +    $ sudo apt-get install nodejs sassc
Please keep npm. `nodejs` is a bit redundant as `npm` depends on it. But the `apt-get` and `dnf install` commands should have the same package names for consistency.

2021-01-05 10:56 UTC, martinpitt commented on HACKING.md
> +    $ sudo apt-get install nodejs sassc
Done while I was at it.

2021-01-05 10:57 UTC, martinpitt commented
I taught sassc-loader to respect `$SRCDIR` so that out-of-tree builds continue to work. The previous version did that with `includePaths: path.resolve(nodedir)`, this now does the moral equivalent of that.

2021-01-05 11:55 UTC, martinpitt commented
Green! Running all tests.

2021-01-05 11:56 UTC, martinpitt approved these changes
Thanks for this! I'm really happy about all these cleanups.

2021-01-05 13:28 UTC, martinpitt commented
@lnussel : This might make your downstream packaging a little easier?

2021-01-05 14:14 UTC, lnussel commented
Sounds good at least :+1:
Will avoid having to recompile sass in the spec file of cockpit

2021-01-05 14:27 UTC, merged