machines: Fix VM deletion bugs
cockpit-project/cockpit pull request #15102
Opened 2021-01-06 11:09 UTC by skobyda

2021-01-07 06:02 UTC, martinpitt requested changes
Thanks!

2021-01-07 06:02 UTC, martinpitt commented on pkg/machines/libvirt-dbus.js
> +                                        return cockpit.file(disk.source.file, { superuser: "try" }).replace(null); // delete key file
This looked a bit brittle at first, but I confirmed that trying to delete a non-existing file succeeds.

2021-01-14 13:10 UTC, skobyda commented on pkg/machines/libvirt-dbus.js
> +                                    if (!ex.message.includes("no storage vol with matching path"))
Fixed

2021-01-15 06:23 UTC, martinpitt requested changes
Thanks! Looks good in general (I have a few nitpicks), but TestMachines.testDelete fails a lot, this needs fixing.

2021-01-15 06:23 UTC, martinpitt commented on test/verify/check-machines
> +        # In this case, the libvirt's storage volume deletion API would fall but cockpit would fall back to deleting the file directly
"would fall" → "would fail"

2021-01-15 06:23 UTC, martinpitt commented on test/verify/check-machines
> +        self.assertTrue(lambda: checkFilePresent(disk))
simpler: `m.execute("test -e " + disk)`

2021-01-15 06:23 UTC, martinpitt commented on test/verify/check-machines
> +        self.assertTrue(lambda: not checkFilePresent(disk))
This is a bit weird -- please use `assertFalse` to check for negative conditions.  But moreover, `m.execute("test ! -e " + disk`

2021-01-26 12:57 UTC, martinpitt requested changes
Code changes look good, thank you! But there's still at least one 
[testDelete failure](https://logs.cockpit-project.org/logs/pull-15102-20210126-123711-ca920132-rhel-8-4/log.html#314) (tests are still running everywhere, though)

2021-01-27 12:23 UTC, KKoukiou requested changes
Simon the test is already there, no need for a new one.
Just remove the set_checked after:
        
        # HACK: Don't delete disks here because they will fail with 'storage volume does not exist'
        # This can be reverted when https://github.com/cockpit-project/cockpit/pull/15102 gets merged

2021-01-29 08:25 UTC, KKoukiou approved these changes
It looks good now! thanks for fixing this :)

2021-01-29 10:24 UTC, merged