tests: fix TestSystemInfo.testCPUSecurityMitigationsEnable
cockpit-project/cockpit pull request #15138
Opened 2021-01-13 17:43 UTC by KKoukiou

This started failing with:
 #hwinfo th:contains(CPU) is ambiguous

Indeed there are two elements starting containing 'CPU' string in the
description. Let's keep using the old wait_present method.

See failure https://logs.cockpit-project.org/logs/pull-15130-20210113-101552-dd028da8-fedora-33/log.html#298-2

2021-01-13 19:12 UTC, martinpitt requested changes
Thanks! I'd rather clean this up a bit more, although this is not a strong opinion.

2021-01-13 19:12 UTC, martinpitt commented on test/verify/check-system-info
> +        b._wait_present('#hwinfo th:contains(CPU)')
I think for this one, `wait_in_text("#hwinfo", "CPU")` would be sufficient. It's just to make sure that the table got rendered.

2021-01-13 19:12 UTC, martinpitt commented on test/verify/check-system-info
> +                b._wait_present('#hwinfo th:contains(CPU)')
Here the old code should actually work, as the next line makes sure that the "CPU security" line does *not* exist.

2021-01-13 19:12 UTC, martinpitt commented on test/verify/check-system-info
> +        b._wait_present('#hwinfo th:contains(CPU)')
Dito with `wait_in_text()` here, or drop this completely -- the next `wait_visible()` is enough.

2021-01-13 19:53 UTC, marusak commented
Agree with Martin's review. I would not just use `_wait_present` that is step back and really just misusing how this function works.

2021-01-14 08:40 UTC, martinpitt approved these changes
Cheers!

2021-01-14 08:53 UTC, merged