check-login: use faillock on debian-testing
cockpit-project/cockpit pull request #15217
Opened 2021-01-26 13:00 UTC by allisonkarlitskaya

As of pam 1.4.0-1 in debian-testing, tally2 is gone and has been
replaced with faillock.  Unfortunately, the tests are currently failing
due to the /sbin/faillock command not currently being properly packaged.
For now, we're introducing a naughty in bots#1569 to deal with that, but
let's make sure that this test starts working again properly once the
issue has been resolved.

2021-01-26 13:11 UTC, marusak commented
Nice, can you please add naughty pattern into https://github.com/cockpit-project/bots/pull/1569 and then test that PR here? (with tests-trigger --bots-pr)

2021-01-27 18:58 UTC, marusak reviewed
Later in the code it does : ` # add it to the pam config`
Is it going to use `/etc/pam.d/password-auth` or it will still use `/etc/pam.d/cockpit`?

2021-01-28 04:41 UTC, martinpitt commented
@marusak: Our /etc/pam.d/cockpit includes the system's shared password PAM file (password-auth in Fedora, common-password in Debian)

2021-01-28 06:16 UTC, martinpitt commented
Moving to draft as this is still failing. Please move back when ready to review.

2021-01-28 06:17 UTC, martinpitt submitted a review, later dismissed
Change looks good, though! Agreed about dropping the "unexpected image name" thing, and standardize around faillock.

2021-01-28 08:13 UTC, marusak commented
> Our /etc/pam.d/cockpit includes the system's shared password PAM file (password-auth in Fedora, common-password in Debian)

Heh, sorry for being dumb, but I am not sure, if that means we should use it for faillock or not, as we use it for tally2. That file does not exist on debian, but there is packaging issue where failock utility is missing, so it might just miss `/etc/pam.d/password-auth` as well.


>  Agreed about dropping the "unexpected image name" thing, and standardize around faillock.

This PR exists beacause of bots#1569 where d-testing is moving to faillock but it packages it wrongly, so we need naughty anyway, I am just thinking if the first place where it should fail is missing config.

2021-01-28 08:13 UTC, allisonkarlitskaya commented
This is definitely not ready.  I'm working on adjusting the patches to the pam config to work on Debian (which is proving to be a bit tricky)

2021-01-28 08:20 UTC, martinpitt commented
@marusak: Sorry for being unclear. The [Fedora version of our PAM file](https://github.com/cockpit-project/cockpit/blob/master/tools/cockpit.pam) uses `password   include      password-auth`, while the [Debian version](https://github.com/cockpit-project/cockpit/blob/master/tools/cockpit.debian.pam) uses `password   include      common-password`.

Fedora's /etc/pam.d/password-auth and Debian's /etc/pam.d/common-password have a similar role (common PAM stack for all services that need to check passwords), but are named and managed differently for historical reasons.

2021-01-28 11:29 UTC, allisonkarlitskaya commented
Now I'm happy.  The tests should now be failing with

```
+ faillock --user admin
bash: line 1: faillock: command not found
```

which is the pattern that I'll use to make the naughty.

2021-01-28 11:41 UTC, allisonkarlitskaya commented
All eyes on test results from `debian-testing@bots#1594`.

2021-01-28 13:59 UTC, marusak commented
[checkLogin.testRaw](https://logs.cockpit-project.org/logs/pull-15217-20210128-114004-ba6b10f3-debian-testing-bots-1594/log.html#311) possibly related?

2021-01-28 16:01 UTC, martinpitt requested changes
Thanks for investigating this failure! But IMO this test hackery is overzealous and not really helping anything :-/

2021-01-28 16:20 UTC, martinpitt commented on test/verify/check-login
> +                          "/etc/pam.d/common-auth")
Sorry for being dense.. FTR, can you please add a comment like `# enable pam_faillock, see <URL or manpage>`?

2021-01-28 16:26 UTC, allisonkarlitskaya commented on test/verify/check-login
> +            # see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=981092
dropped the mkdir

2021-01-28 16:26 UTC, allisonkarlitskaya commented on test/verify/check-login
> +                          "/etc/pam.d/common-auth")
i did

2021-01-28 16:27 UTC, allisonkarlitskaya commented on test/verify/check-login
> +            # this is really a bugfix to the OS, so it doesn't need to be reversed
i meant this with regards to `@nondestructive`, not removing it after the upstream bug is fixed, but you're right.  we should just remove it now anyway: the test will fail before it's relevant.

2021-01-28 16:28 UTC, martinpitt approved these changes
Thanks! And sorry again for being half-blind this evening. Hoping for green :)

2021-01-28 18:09 UTC, merged