unit-tests: copy source to a `workdir` first
cockpit-project/cockpit pull request #15210
Opened 2021-01-22 18:38 UTC by allisonkarlitskaya

The unit-tests container currently have two problems:

 - it cannot be run out of a git worktree because the .git directory is
   outside of the source tree, so when we bind-mount the source tree, we
   don't get the gitdir included

 - it cannot be run on machines with selinux enabled because of
   labelling issues.  We could get around that with -v ::z, but this
   causes the given path to be relabelled, even if specified with 'ro',
   which is not something we should want to do to our source tree

The solution to both problems is to clone the source and pass the clone
into the container, complete with .git directory in the normal place,
and allowing the whole thing to be relabelled with :z.

Some notes:
 - this currently feels a bit gross, but it's EOD and i want to push it to see if anyone has feedback
 - we might want to investigate pitti's idea of sending in the .git dir plus the branch name (or more likely ref sha) to clone.  we'd still need to copy it to allow the relabel
 - we might want to use tar and send in the tarball
 - my first idea was to make the workdir read-write and have the container work directly inside of it instead of making its own clone, but i ran into some issues.  I might give it another try, though.

2021-01-25 06:20 UTC, martinpitt commented
Agreed that it is rather gross to copy it twice, and moreover, having to copy the rather bulky `node_modules/`; can't we at least reuse that and let that be relabeled? It now goes away on `git clean` anyway, so a changed label shouldn't hurt?

One of these days we need to fix our build system to build everything in a separate build tree. `make-source` seems rather close to that already. Anyway, I can't say I like this much, but I already don't like the current setup, so not much of a difference :grin: This should at least update the documentation, though.

2021-01-25 08:57 UTC, allisonkarlitskaya commented
> Agreed that it is rather gross to copy it twice, and moreover, having to copy the rather bulky `node_modules/`; can't we at least reuse that and let that be relabeled? It now goes away on `git clean` anyway, so a changed label shouldn't hurt?

I'm going to try again on my idea of creating the worktree outside and having the inside work directly on it (ie: no further copying), which will reduce one of the copies.

Additionally: at least on btrfs, `cp` defaults to `--reflink=auto` and is therefore really fast and doesn't use very much space...

2021-01-25 09:35 UTC, allisonkarlitskaya commented
So I remembered what the problem was before: we don't build as root, and the directory on the outside is almost definitely not going to end up with the correct uid for the `builder` user on the inside...

2021-12-21 14:49 UTC, allisonkarlitskaya commented
The force-push just now fixes both of the original problems that this PR was opened for, and also represents a very large cleanup.

It also seems to be working correctly.

Generally, while developing this, it also started to feel like something that I might actually want to use locally.

2021-12-21 15:14 UTC, martinpitt commented
The first 8 commits are obvious no-brainers, and could land right away (in a separate PR).

I don't like the others, honestly, at least not from a quick pass-by review: This is a *lot* of non-straightforward shell code, copying, and hacking for something which should be done properly with volumes -- either `:ro` and a separate build tree, or with `:z` for writable directories and running the unit test container as root so that it uses the correct UID for the host user.

Copying is not only slow, it's also annoying because it breaks the "edit source on your host and re-run make in running container" development iteration use case.

So for these I'll need a lot more convincing -- let's talk in January?

2021-12-21 15:19 UTC, allisonkarlitskaya commented
> The first 8 commits are obvious no-brainers, and could land right away (in a separate PR).

→ #16749

2021-12-21 15:46 UTC, allisonkarlitskaya commented
> Copying is not only slow, it's also annoying because it breaks the "edit source on your host and re-run make in running container" development iteration use case.

But that doesn't work anyway: the existing setup already takes a clone of the `/source` repository into `/tmp/source` and builds from there...

This is more about replacing one form of copying with a different one...

2022-01-04 12:08 UTC, martinpitt commented
Notes for myself: I had a look at this again, on a fully standard F35 machine:
```sh
mkdir src; echo world > src/hello.txt
ls -lZ src/
# -rw-r--r--. 1 admin admin unconfined_u:object_r:user_home_t:s0 6 Jan  4 11:53 hello.txt

podman run -it --rm -v ./src:/src:ro quay.io/libpod/busybox sh -c 'ls -lr /src; grep -r . /src'
# ls: can't open '/src': Permission denied
# grep: /src: Permission denied
```

The same happens with `sudo`, so this is not a problem specific to user containers, and not even related to the UID inside the container -- the latter might impose an additional problem with regular Unix UIDs, but that one would be easy enough to work around -- just run the build inside the container as root (then it's equal to your user on the host).

So indeed you either need to switch off SELinux, or live with the changing container labels:
```
podman run -it --rm -v ./src:/src:ro,z quay.io/libpod/busybox sh -c 'ls -lr /src; grep -r . /src'
# -rw-r--r--    1 root     root             6 Jan  4 11:53 hello.txt
# /src/hello.txt:world

ls -lZ src/
# -rw-r--r--. 1 admin admin system_u:object_r:container_file_t:s0 6 Jan  4 11:53 hello.txt
```

I'm not sure how much of a problem that actually is, especially in a git tree which is not particularly precious. Unfortunately in https://github.com/cockpit-project/cockpit/commit/af1053ca00e2faa1b1dec30e8302108086acd43d I didn't say *why* it was a problem. :cry: 

This is not a bug in the sense that it works as designed -- SELinux forbids "exporting" files to containers unless they are typed `container_file_t`. As to whether this policy makes *sense* we can have a long discussion, but the current status quo won't change much.

So, in summary, we have three options: `:z`, `setenforce 0`, or copying the tree into the container via tar, or a temporary directory (which then can use `:z` just fine) -- this PR essentially does the latter.

2022-01-04 12:21 UTC, martinpitt requested changes
During the holidays I just had a cursory glance at this, now a deeper look. I do agree about the two problems (SELinux and .git work trees), but I still find create-pack unacceptably and wildly over-engineered.

What we essentially need to do is to move the `git clone /source` out of the container into the host, so that we don't increase the amount of work and complexity.

This should essentially be:

    cp -a . $tmpdir
    podman run ... -v $tmpdir:/source:z

and then doing the build right in /source. This will work just fine if the container runs as root, but fail if it runs as user. I don't see a good reason to actually run it as non-root, do you?

This needs to be optimized a little: For sure the above `cp -a` is a little too naïve, as it will also copy any existing test/images/. That should certainly be skipped from the copying, as that takes long and is unnecessary. We want pretty much everything else from the build tree (node_modules, dist, autoconf files, etc.) -- if code is already built, there is little reason to not use them (this won't matter in CI, but is nice for local iteration).

But I propose to do this in smaller steps: For the first version, just move out the `git clone` and `node_modules` copying from the container to the host, and switch the unit-test container to root. That is a straight code move without any increasing complexity or performance penalty, and will fix the original problems (SELinux, worktrees).

Another commit can then add dist/ to the thing, which is simple enough.

For the pre-built C stuff and local changes, we can re-engineer this the other way around: not start from git clone, but from copying the whole tree and filter out test/common.

All of this should be < +10 lines and be obvious and understandable.

2022-01-04 14:50 UTC, allisonkarlitskaya commented
Your suggestions here are basically what I did in my first approach to solving this problem.  I'll come back to this later.

2022-06-14 09:13 UTC, allisonkarlitskaya commented
We landed #17304 instead.

2022-06-14 09:13 UTC, closed without merging