Replace 'restart' with 'reboot' when related to a system reboot
cockpit-project/cockpit pull request #15311
Opened 2021-02-11 01:02 UTC by skobyda

This should make clearer distinction between 'restart' (often used in relation to a service restart) and a 'reboot' (used in relation to a system reboot)

Fixes #15273

2021-02-11 05:00 UTC, martinpitt requested changes
Thanks! Fortunately we already have "Reboot" as translated string, so it won't break too many translations. In favor of the change, but still needs a bunch of test adjustments.

2021-02-15 12:21 UTC, skobyda commented
Looking at tests, there are failures which seem unrelated (or I cannot think of how they relate to a simple string ammendation). @martinpitt have you seen these failures before?

2021-02-15 12:45 UTC, martinpitt commented
@skobyda : They mostly look familiar, yes. See our [weather report](https://images-frontdoor.apps.ocp.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7). Retrying.

2021-02-15 12:56 UTC, martinpitt approved these changes
Thanks, looks good! Please land once everything is green.

2021-02-16 09:26 UTC, martinpitt commented
For some reason [rhel-8-4-distropkg](https://logs.cockpit-project.org/logs/pull-15311-20210216-083547-e538dadc-rhel-8-4-distropkg/log.html) is cursed on this PR. That's like the 5th time that it fails.

2021-02-16 11:15 UTC, marusak commented
There is probably no point in retrying this anymore. If we are sure it is unrelated error, lets just merge it as is.

2021-02-16 11:27 UTC, martinpitt commented
At least fedora-32 succeeded at last.

2021-02-16 11:27 UTC, merged