Kpatch integration
cockpit-project/cockpit pull request #15569
Opened 2021-03-22 11:19 UTC by marusak

Note about commits:
Includes a few unrelated commits, I'll split them into separate PR once I get test runs on them. Almost certain at least one of them breaks tests but too many tests might be affected so I'll let bots do the dirty work.

Notes:
- I would really like to test this on real patches. To my knowledge there are no patches yet for 8.4, but I'll check it out again.
- Tests are not as I would like them - I would prefer to also test kernel update with patches for this new kernel - but I struggled to make it work so I just check that `dnf kpatch` is set to `auto` and hope it works as it is supposed to. I would also prefer to test `kpatch list` but making own patches that would be real was just impractical to do, so I ended up faking `kpatch` utility.
- We possibly could watch /sys/kernel/livepatch to recognize when patches are loaded, but seems rather corner case. When using our UI to install patches it will be updated after package updates
- There is corner case when for some reason patches are installed but not loaded. This would happen only if user would mangle with it in some way (like disabling service and rebooting machine). We could show `Install` button but I haven't implemented that yet.
- I don't show any changelog, follow up?

How it looks like: (sorry no screencast, computer does not want to collaborate)
(No patches installed nor loaded, but available):
![packgesandneabled](https://user-images.githubusercontent.com/12330670/111981387-eb153680-8b07-11eb-8d2f-f40be004761c.png)

The edit button (that can be `Install` when kpatch is not installed but available) opens this dialog. When user toggles switches a note is shown on bottom of what will happen if they press 'Apply'.
![willdostuff](https://user-images.githubusercontent.com/12330670/111981428-f5cfcb80-8b07-11eb-9947-5e16ae9e3655.png)

When some patches are also loaded (it will show also when some are only installed).
![withactivepatches](https://user-images.githubusercontent.com/12330670/111981594-2a438780-8b08-11eb-8a58-ade644ebe3ff.png)

2021-03-22 13:39 UTC, KKoukiou commented on pkg/packagekit/autoupdates.jsx
> +                <SplitItem>
So here you use the split item to nicely position a label - value pair. 
I suggest you use DescritionList for such usecases. If for some reason you can't, (I see there are some buttons on the right) let's make sure that the generated html is also accessible for screen readers. For that you will need an aria-labelledby  on the second split item.

2021-03-22 13:48 UTC, KKoukiou requested changes

2021-03-22 13:48 UTC, KKoukiou commented on pkg/packagekit/kpatch.jsx
> +                    console.log("Failed to query info about availablity of kpatch");
This is more like: kpatch not available on the system, no? In any case it's just a console message, I don't mind.

2021-03-22 13:48 UTC, KKoukiou commented on pkg/packagekit/kpatch.jsx
> +                .catch(console.log)
Let's JSON.stringify the exception at least? Otherwise we don't see it in the test logs.

2021-03-22 13:48 UTC, KKoukiou commented on pkg/packagekit/kpatch.jsx
> +                            disabled={!this.props.privileged}
s/disabled/isDisabled

2021-03-25 13:36 UTC, marusak commented on pkg/packagekit/updates.jsx
> +            <StackItem>
thanks! I was thinking about it whether it is actually necessary. I'll cleanup after myself for sure

2021-03-26 08:39 UTC, marusak commented
Note to myself - Commit "packagekit: Restyle UI to have status and settings cards" includes:
```
 
+    const patches = pkgNames.some(p => p.name.startsWith("kpatch-patch"));
+
+    const pkgTitle = <>
+        <span>{pkgsTruncated}</span>
+        {patches && <>{" "}<Badge>{_("patches")}</Badge></>}
+    </>;
+
     let descriptionFirstLine = (info.description || "").trim();
     if (descriptionFirstLine.indexOf("\n") >= 0)
         descriptionFirstLine = descriptionFirstLine.slice(0, descriptionFirstLine.indexOf("\n"));
(3/13) Stage this hunk [y,n,q,a,d,K,j,J,g,/,e,?]? n
@@ -318,7 +327,7 @@ function updateItem(info, pkgNames, key) {
 
     return {
         columns: [
-            { title: pkgsTruncated },
+            { title: pkgTitle },
```
which needs to be part of commit "packagekit: Introduce kpatch integration".

2021-04-01 06:07 UTC, marusak commented
Closing for time being. I want to test this on real system with real patches but that will take a while until such environment is available.

2021-04-01 06:07 UTC, closed without merging