build: Fix polkit detection
cockpit-project/cockpit pull request #15576
Opened 2021-03-23 16:24 UTC by martinpitt

Fixes #14052

2021-03-23 18:35 UTC, allisonkarlitskaya requested changes
If we're fixing bugs anyway...

I'd prefer we make polkit support mandatory by default (ie: remove all autodetection) and then add an option to `--disable-polkit`.  Never autodetected.

Prevents accidentally building cockpit with missing features, and leaves us with less "cases" to test, by half.

2021-03-23 18:38 UTC, allisonkarlitskaya commented
ps: I'd like to make that a general thing: as part of our recent push to clean up the build system, let's remove all automagic detections, entirely.  polkit just volunteered to be candidate #1.

2021-03-24 05:05 UTC, martinpitt commented
@allisonkarlitskaya Sure, makes sense! Updated, it's now much simpler.

2021-03-24 08:14 UTC, allisonkarlitskaya approved these changes

2021-03-24 08:14 UTC, allisonkarlitskaya commented on configure.ac
> +AC_ARG_ENABLE(polkit, AC_HELP_STRING([--disable-polkit], [Disable usage of polkit]),,enable_polkit=yes)
Some small bikeshedding:

`enable_polkit` will be set to
  - `yes` if `--enable-polkit`
  - `no` if `--disable-polkit`
  - not set, if neither

so it maybe makes sense to simplify this a bit and handle the default by dropping this extra assignment here and inverting the check below to test `"$enable_polkit" != "no"` (ie: "unless explicitly disabled...")

On the other hand, that will result in an undefined variable expansion (which is not an error in configure scripts, but which you might find to be undesirable).

Take it or leave it :)

2021-03-24 08:14 UTC, allisonkarlitskaya commented on configure.ac
>    COCKPIT_BRIDGE_CFLAGS="$COCKPIT_CFLAGS"
It seems a bit yucky to define this in a branch of a check that's polkit-specific, but that's something we can iron out later on...

2021-03-24 08:14 UTC, allisonkarlitskaya commented on configure.ac
> +        With polkit:                ${enable_polkit}
Okay.  Maybe, for this alone, it makes sense to keep it as you have it above :)

2021-03-24 08:25 UTC, merged