containers: Speed up dist unit-tests scenario
cockpit-project/cockpit pull request #15816
Opened 2021-05-11 07:41 UTC by martinpitt

Skip the full `make` build and xz extreme compression in the "start
dist" scenario.

2021-05-11 11:06 UTC, allisonkarlitskaya requested changes

2021-05-11 11:06 UTC, allisonkarlitskaya commented on .github/workflows/build-dist.yml
> +          sudo podman run -i -v ./source:/source -w /source ghcr.io/cockpit-project/unit-tests test/make_dist.py
Why not support that officially in the `start` script?

2021-05-11 13:53 UTC, allisonkarlitskaya commented on .github/workflows/build-dist.yml
> +          sudo podman run -i -v ./source:/source -w /source ghcr.io/cockpit-project/unit-tests test/make_dist.py
Testing "`make dist` without `make`" is semi-legit as a scenario...

2021-05-12 05:18 UTC, martinpitt commented
@allisonkarlitskaya : Reworked. build-dist  run here took 8:32 minutes, which is significantly faster than the [previous recent runs](https://github.com/cockpit-project/cockpit/actions/workflows/build-dist.yml) (9:30 to 11:30 minutes).

2021-05-12 06:29 UTC, allisonkarlitskaya approved these changes
That's a lot better!  Thanks!!

2021-05-12 06:29 UTC, merged