storage: Use semantic HTML in verify key modal
cockpit-project/cockpit pull request #15871
Opened 2021-05-26 14:42 UTC by garrett

Follow-up to #15844, to fix the HTML.

Would've been in #15870, but I wanted the previous fix to be implemented quickly. This changes a lot more.

2021-05-26 14:53 UTC, garrett commented
It doesn't look _so much_ different, but anyone using a screen reader would care.

![Screenshot from 2021-05-26 16-52-00](https://user-images.githubusercontent.com/10246/119682009-d4aa9480-be42-11eb-8a7a-a047db25bb9e.png)

2021-05-26 15:03 UTC, allisonkarlitskaya reviewed
Can you add a copy widget to those while you're at it?

2021-05-26 15:27 UTC, garrett commented
> Can you add a copy widget to those while you're at it?

I'd love that.

Specifically inline compact code: https://www.patternfly.org/v4/components/clipboard-copy#inline-compact-code

2021-05-27 07:50 UTC, mvollmer approved these changes

2021-05-27 07:50 UTC, mvollmer commented
Thanks!

2021-05-27 10:43 UTC, KKoukiou reviewed
This PR also add some style fixes which are not mentioned in the commit message. Especially the 'pre' customization I would like to check before we merge this.

2021-05-27 10:49 UTC, KKoukiou requested changes

2021-05-27 10:49 UTC, KKoukiou commented on pkg/storaged/storage.scss
> +    background: var(--pf-global--BorderColor--300);
OK Patternfly does not style ` <pre> ` with grey background etc.
Instead for code blocks or text areas they provide their own components - see https://www.patternfly.org/v4/components/code-block 

As this is overriding default PF styles I think this is not correct do here - as we 're trying to move away from custom stylesheets.

2021-05-27 16:44 UTC, garrett commented
I've changed the pre to an inline code copy from PF @ 8895962.

However, it looks like this:

![Screenshot from 2021-05-27 18-35-33](https://user-images.githubusercontent.com/10246/119864836-55d55a80-bf1b-11eb-95e5-c98677a01652.png)

And it should be inline, with code, and have a grey background like this:

![Screenshot_2021-05-27 PatternFly 4 • Clipboard copy](https://user-images.githubusercontent.com/10246/119864877-5ff75900-bf1b-11eb-839b-2e2ac3ee600d.png)

From https://www.patternfly.org/v4/components/clipboard-copy/#inline-compact-code

Do we need to update PF to get the new variants perhaps?

2021-05-28 10:32 UTC, KKoukiou commented
For the inline copy clipbord component we need https://github.com/patternfly/patternfly-react/pull/5629
which is included in @patternfly/react-core@4.108.0
We currently have lower version than this so it's expected that you can't use it with this patternfly version @garrett .

2021-06-01 11:44 UTC, garrett commented
Added a blocked tag, as we're blocked on a PF upgrade. Hopefully we can upgrade soon and get this merged in shortly after.

2021-07-13 10:27 UTC, KKoukiou approved these changes

2021-08-04 06:03 UTC, martinpitt commented
Whoops, this slipped through the cracks, sorry! The PF update landed a month ago, and this was already approved. I pushed a rebase and I'll see to get this into today's release.

2021-08-04 06:33 UTC, martinpitt commented
I tested the rebase. The dialog looks fine to me, and copy&paste works as expected.

![image](https://user-images.githubusercontent.com/200109/128132944-8fde7313-8de4-483d-8c27-2ecf346a6448.png)

2021-08-04 06:33 UTC, martinpitt approved these changes

2021-08-04 06:45 UTC, mvollmer approved these changes

2021-08-04 06:56 UTC, merged