livetest: stop spinning up a vm every single time anyone writes any comment on any PR or issue
cockpit-project/cockpit pull request #15892
Opened 2021-06-04 13:43 UTC by KKoukiou

If we put a `if:` on each `job:` then the workflow will dispatch, but at
least it won't start any VMs.

2021-06-04 13:47 UTC, allisonkarlitskaya requested changes
As written, it seems like you really only need one job here.  The job can have the static checks based on the event blob and the permissions checking can just fail (`core.setFailed()` or something like that) in case access is denied.

If you want to add/remove additional permissions to the github token, for example, then it might make sense to keep things separate...

But in any case, now that I mention it: please introduce `permissions:` to scope the credential to what is actually required here.

2021-06-04 13:50 UTC, KKoukiou commented
Works as expected: tested on https://github.com/KKoukiou/cockpit/pull/3 
First normal run: https://github.com/KKoukiou/cockpit/actions/runs/906460733
And run which should not spawn a VM: https://github.com/KKoukiou/cockpit/actions/runs/906462637

2021-06-04 13:51 UTC, KKoukiou commented
> As written, it seems like you really only need one job here. The job can have the static checks based on the event blob and the permissions checking can just fail (`core.setFailed()` or something like that) in case access is denied.
> 
> If you want to add/remove additional permissions to the github token, for example, then it might make sense to keep things separate...
> 
> But in any case, now that I mention it: please introduce `permissions:` to scope the credential to what is actually required here.

Sure, this workflow is broken anyway. Mind getting this tiny improvement in so that we don't spawn VMs like that and I will take a look in improvements another time.

2021-06-04 15:13 UTC, allisonkarlitskaya approved these changes
Approved because, strictly speaking, it's an improvement :)

Looking forward to the follow-up.

2021-06-07 11:02 UTC, martinpitt approved these changes
This could have been no-test, but prodding the tests a bit to not ruin statistics. (Also, the reposchutz one needed the label). Danke!

2021-06-07 11:02 UTC, merged