Revert "Use sassc instead of node-sass"
cockpit-project/cockpit pull request #15922
Opened 2021-06-10 11:32 UTC by allisonkarlitskaya

This reverts commit 4063e3df28fb877adc3336c1b4526c02ffec3b84.

Instead, port to Dart Sass (which we already had in our package.json for
some reason).

This is already working really well, except we get about a billion
warnings about

  DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

with a recommendation to use `math.div()` instead.  Someone should look
at those.

2021-06-10 11:33 UTC, allisonkarlitskaya commented
/npm install

2021-06-10 13:23 UTC, KKoukiou requested changes

2021-06-10 13:23 UTC, KKoukiou commented on webpack.config.js
> +                            sourceMap: true,
sourceMap: !production

2021-06-10 13:23 UTC, KKoukiou commented on webpack.config.js
> +                            sourceMap: true,
sourceMap: !production

2021-06-10 13:23 UTC, KKoukiou commented on webpack.config.js
> +                                outputStyle: 'compressed',
compressed should be only in production mode I believe.

2021-06-10 14:41 UTC, allisonkarlitskaya commented
/npm install

2021-06-10 14:49 UTC, allisonkarlitskaya commented
There's a minor slowdown here on the order of a couple of seconds.  Apparently it's down to async call overhead and we could reverse that by using the `fibers` package to do some kind of weird magic, but that's due to stop working in Node version 16...

Let's look at that separately.

2021-06-10 17:50 UTC, allisonkarlitskaya commented
the problem is that the word `truetype` is appearing in our CSS files suddenly, but only in `NODE_ENV=development`.  There are a lot of cases of this:

```css
dist/storaged/storage.css:  src: url("patternfly-icons-fake-path/pficon.eot?#iefix") format("eot"), url("patternfly-icons-fake-path/pficon.woff2") format("woff2"), url("patternfly-icons-fake-path/pficon.woff") format("woff"), url("patternfly-icons-fake-path/pficon.ttf") format("truetype"), url("patternfly-icons-fake-path/pficon.svg#pficon") format("svg");
```

which is failing the check:

```sh
elif grep "\.\./fonts/OpenSans\|fonts/.*eot\|truetype" ${cssfiles} >&2; then
    echo "ERROR: invalid patternfly fonts paths found" >&2
```

2021-06-11 05:13 UTC, martinpitt commented
@allisonkarlitskaya These are supposed to be fixed up by the `string-replace-loader` bits in webpack.config.js. At first sight this is because the pattern matches on `src:url..`, but dart-sass compiles it as `src: url..` (with a space in between). Try adjusting the string-replace pattern to `src: *url` ?

2021-06-11 08:08 UTC, allisonkarlitskaya commented
Just merged the parallel commit for the po plugin to make sure this would be handled correctly here.

![image](https://user-images.githubusercontent.com/36541154/121653303-d60fca00-ca9c-11eb-968a-43835ae2b9c2.png)

Cool!

2021-06-11 08:14 UTC, allisonkarlitskaya commented
/npm install

2021-06-14 05:05 UTC, martinpitt approved these changes
This looks great to me, and we all seemed to agree on IRC that this is the right way to go. Thanks!

2021-06-14 05:05 UTC, merged

2021-06-14 05:06 UTC, martinpitt commented
@allisonkarlitskaya : starter-kit (and derived projects) also use this. Do you want to send corresponding PRs for these as well? I cana give you a hand with that, of course.

2021-06-14 06:56 UTC, allisonkarlitskaya commented
> @allisonkarlitskaya : starter-kit (and derived projects) also use this. Do you want to send corresponding PRs for these as well? I cana give you a hand with that, of course.

gern :)

2021-06-19 09:56 UTC, garrett commented
> Pin the version to strictly less than 1.33 to avoid an annoying warning about division (which we don't have a lot of control over, since most cases of its are coming from PatternFly, who are currently deciding what to do about this issue, themselves).

[PatternFly 4.115.0 fixes Dart Sass compatibility](https://github.com/patternfly/patternfly/pull/4164), so once we upgrade PF to that version (or higher), we can even adjust our version of Dart Sass accordingly (that is: unlock the version requirements).

This was a _lot_ faster and less painful than what I thought it would be. :partying_face:

2021-06-21 09:05 UTC, allisonkarlitskaya commented
> [PatternFly 4.115.0 fixes Dart Sass compatibility](https://github.com/patternfly/patternfly/pull/4164), so once we upgrade PF to that version (or higher), we can even adjust our version of Dart Sass accordingly (that is: unlock the version requirements).

@garrett And PF3?

2021-06-21 09:09 UTC, KKoukiou commented
> > [PatternFly 4.115.0 fixes Dart Sass compatibility](https://github.com/patternfly/patternfly/pull/4164), so once we upgrade PF to that version (or higher), we can even adjust our version of Dart Sass accordingly (that is: unlock the version requirements).
> 
> @garrett And PF3?

I don't think that PF4 is anyhow maintained or supported.

2021-06-21 12:02 UTC, allisonkarlitskaya commented
> > > [PatternFly 4.115.0 fixes Dart Sass compatibility](https://github.com/patternfly/patternfly/pull/4164), so once we upgrade PF to that version (or higher), we can even adjust our version of Dart Sass accordingly (that is: unlock the version requirements).
> > 
> > 
> > @garrett And PF3?
> 
> I don't think that PF3 is anyhow maintained or supported.

This is kinda my point: I think we're gonna be stuck on the old Dart Sass version until we can stop using PF3.