Some create timer modal improvements (SPUR)
cockpit-project/cockpit pull request #15958
Opened 2021-06-16 08:25 UTC by KKoukiou

Partially addresses https://github.com/cockpit-project/cockpit/issues/15927

2021-06-16 12:55 UTC, garrett commented
Dropdowns are center aligned... and I'm not sure why.

![Screenshot from 2021-06-16 13-24-30](https://user-images.githubusercontent.com/10246/122211489-1610eb80-cea7-11eb-8c07-28c106dc0f69.png)

Hourly timers are still non-obvious. (I guess that's minute offset?)

![image](https://user-images.githubusercontent.com/10246/122211564-2aed7f00-cea7-11eb-86c7-b4b1d6de1ad9.png)

- We're creating a single timer in the UI, so the dialog should be "Create timer", not "Create timers".
- Is there a limit or a recommended length on service names? If so, we should show that in the UI. 
- Are there only ever two options for "Run"? It should probably be renamed "When" as it's after system boot or at a specific time.
- After system boot is a delay, right? It should probably be called "Delay"?

Some sketches:

![service-timer-modal(1)](https://user-images.githubusercontent.com/10246/122222546-abfe4380-ceb2-11eb-9d04-9d30cdb1d58b.png)

![service-timer-modal(2)](https://user-images.githubusercontent.com/10246/122222776-dcde7880-ceb2-11eb-977b-008df1909fd4.png)

![service-timer-modal(4)](https://user-images.githubusercontent.com/10246/122222772-dc45e200-ceb2-11eb-9b54-e82102c64540.png)

2021-06-16 12:58 UTC, garrett commented
I'm fine if this PR just adjusts the list above, including the simle stuff like alignment and the text strings. UI changes in this case are mainly superfluous and can go in a follow-up or just be ignored, as what we have isn't so bad (except for the lack of communication of what that text entry is for hourly mode and the "Run"/"When" dropdown for just two items).

2021-06-16 14:44 UTC, KKoukiou commented
> I'm fine if this PR just adjusts the list above, including the simle stuff like alignment and the text strings. UI changes in this case are mainly superfluous and can go in a follow-up or just be ignored, as what we have isn't so bad (except for the lack of communication of what that text entry is for hourly mode and the "Run"/"When" dropdown for just two items).

I can fix your suggestions in this PR - it's about getting the perfect from this anyway. When we are satisfied I will also add a pixel test to make sure we don't break it.

2021-06-16 16:50 UTC, KKoukiou commented
@garrett there are still some unsolved issue from https://github.com/cockpit-project/cockpit/issues/15927#issuecomment-862108330 which are not so trivial.

Can you please review this again anyway? and maybe we can split the enhancements in multiple PRs.

2021-06-17 14:50 UTC, garrett approved these changes
I like the changes and I'm happy with splitting off the rest to another PR.

There is a little problem with the layout in super-small sizes (iPhone SE), but everything else is fine.

![Screen Shot 2021-06-17 at 16 48 01](https://user-images.githubusercontent.com/10246/122420377-ef78b080-cf8b-11eb-8f3b-d9382cb8ed37.png)


One somewhat notable thing: When adding new items, they're below the scroll. We should probably instruct the browser to scroll down to the bottom when adding them. When there's no overflow, it shouldn't do anything. This mainly affects smaller screens like mobile.

But, overall, happy to see a lot of this custom code go away, and the rest can be addressed in follow-up PR(s).

2021-06-17 15:03 UTC, garrett requested changes
Oh, I just noticed the radio button labels aren't clickable. This means it's also broken for accessibility.

![Screenshot from 2021-06-17 17-01-01](https://user-images.githubusercontent.com/10246/122422766-b3dee600-cf8d-11eb-9866-de01270c9023.png)

The label exists, but it doesn't have a for="" attribute pointing to the ID of the `<input>`... and the input also doesn't have a generated unique ID.

2021-06-17 15:05 UTC, garrett commented on pkg/systemd/services/timer-dialog.jsx
> +                               label={_("At specific time")} />
I guess leaving out an ID doesn't make the radios get hooked up properly in PatternFly, so each needs its own unique ID.

This really should be a compile time error for PF, or PF should wrap the label around the radio. Either-or, but right now, neither happens, so we need to manually ensure there's an ID.

2021-06-21 14:11 UTC, garrett submitted a review, later dismissed
1. Dropdowns look fine (that was my fault, and on my machine only)
   ![Screenshot from 2021-06-21 16-09-06](https://user-images.githubusercontent.com/10246/122776275-3ed02100-d2ab-11eb-8486-cc9435dbebd0.png)
2. Labels are now fixed for a11y and are clickable!

LGTM! :+1:

2021-06-21 14:19 UTC, KKoukiou commented
/packit build

2021-06-21 15:15 UTC, garrett approved these changes

2021-06-22 13:23 UTC, merged