make webpack-watch a symlink of webpack-make
cockpit-project/cockpit pull request #16292
Opened 2021-09-01 10:18 UTC by jelly

This removes the wrapper script `webpack-watch` and makes `webpack-make` if it's called as `webpack-watch`.

2021-09-01 10:31 UTC, jelly commented
I've left out keeping the symlinks in the dist tarball as I'm not 100% sure what the implications are if we don't pass `-h` for the symlinks in the `test` folder.

2021-09-01 20:39 UTC, martinpitt requested changes
Thanks! I'm really glad to see that nasty shell wrapper gone. Supposedly this gets duplicated in the shipped tarball? (Doesn't matter much, it's not a tool you'd use on release tarballs anyway)

2021-09-01 20:39 UTC, martinpitt commented on tools/webpack-make
> +parser.add_argument('--no-eslint', { action: 'store_true', help: "Disable eslint linting", default: webpack_watch })
I wonder if we should enable eslint by default for watching as well. Personally I find it sometimes useful, sometimes it gets in the way -- it's not really about the time (incremental builds with eslint don't take much longer), but more about whether you are hacking on something where "unused function" etc. is annoying. For consistency I'd generally enable it, and provide an option to disable it. @KKoukiou , @mvollmer , @marusak , do you have an opinion about changing the default?

Also, could this get a short option, like `-e`, as it is rather common?

2021-09-02 16:07 UTC, jelly commented
> Thanks! I'm really glad to see that nasty shell wrapper gone. Supposedly this gets duplicated in the shipped tarball? (Doesn't matter much, it's not a tool you'd use on release tarballs anyway)

Yes, it will get duplicated in the tarball, which we can fix but I am not 100% sure about the implications for the other symlinks in our tarball.

2021-09-03 05:07 UTC, martinpitt approved these changes
Thanks! No feedback so far, so let's land this (keeping the current behaviour). Triggering required f34 test.

2021-09-03 18:28 UTC, merged