lib/patternfly: Fix "form select" padding
cockpit-project/cockpit pull request #16376
Opened 2021-09-21 14:39 UTC by garrett

PatternFly's form select does not use similar spacing to PF's select.

This casues issues when the form select is not stretched. Seen @:
https://github.com/cockpit-project/cockpit-podman/issues/755

Upstream issue:
https://github.com/patternfly/patternfly/issues/4387

2021-09-21 14:45 UTC, garrett commented on pkg/lib/patternfly/patternfly-4-overrides.scss
> +    --pf-c-form-control--PaddingLeft: 6px;
We could possibly reverse out the padding to the normal selects, if they apply the values on the `pf-c-form-control` and use that minus some values (possibly spacing related, but as this doesn't divide cleanly, we would probably still have to add magic `px` values, especially to the Firefox compensation below).

In other words, I think we're stuck with magic values in `px` one way or the other, to make form selects look more like custom selects.

2021-09-22 07:00 UTC, KKoukiou approved these changes
Since there is an upstream PF4 issue we can leave even with the magic numbers wa. thanks :)

2021-09-22 09:01 UTC, garrett commented
The visual tests that failed pointed me to a location that has form selects in the same place as inputs, so it's mixing and matching elements. I've used that as reference to correct the left padding (which was off by 2px in all browsers in this PR prior, as I only tested based on isolated examples from the PF demo instead of in Cockpit itself with other elements nearby).

I force pushed and I guess I'll have to wait for the visual tests to see what happens and then correct them when they get built.

2021-09-22 10:22 UTC, garrett commented
For the non-Firefox values, the left padding looks like it's 0.5 of spacer, the right seems like 2.5 of spacer might be about right (I'd have to re-check with both in-page). For Firefox, we could use the same values in a calc() and remove 4px to make it pixel perfect with the rest.

2021-09-22 11:37 UTC, KKoukiou requested changes
Failing pixel tests.

2021-09-22 11:43 UTC, garrett commented
> Failing pixel tests.

Not surprising, as changing this PR will change the visuals, which would cause the so-called "pixel" tests to fail. But we need them to fail first to get the new PNGs to download, then copy, then push.

2021-09-22 11:46 UTC, garrett commented
It's only failing mobile, I guess? Fedora 34 doesn't even show the "pixel" tests.

2021-09-22 11:47 UTC, garrett commented
I updated the images _again_, and just got:

```
$ ./test/common/pixel-tests push
No changes
Everything up-to-date
```

:shrug:

2021-09-22 14:52 UTC, garrett commented
@KKoukiou: It looks like the pixel tests passed this time? I see pakit failures, but everything else seems fine?

I guess I could try to change the values to PF variables and it should still pass afterward if I do it successfully (as they should resolve to the same pixel values).

2021-09-22 15:10 UTC, KKoukiou approved these changes

2021-09-22 15:31 UTC, merged