storage: Unmount via dialog
cockpit-project/cockpit pull request #16559
Opened 2021-11-03 14:43 UTC by mvollmer

Unmounting takes a long time now because we need to reload
systemd (because we modify fstab).  And while a unmount operation is
running, we should block other operations that modify fstab.

2021-11-04 07:09 UTC, martinpitt commented
How can I test this? I created a LUKS 2 file system on the `modprobe scsi_debug dev_size_mb=200` device, get it mounted, click "Unmount" in the kebab menu, and don't see a dialog.

2021-11-04 08:50 UTC, mvollmer commented
> How can I test this? I created a LUKS 2 file system on the `modprobe scsi_debug dev_size_mb=200` device, get it mounted, click "Unmount" in the kebab menu, and don't see a dialog.

That should do it... hmm.

2021-11-04 12:55 UTC, mvollmer commented
The dialog is pretty bare:

![image](https://user-images.githubusercontent.com/3228183/140316824-f1214bb9-725b-4cb5-9dc3-8cc7417caf9f.png)

We could add a sentence that explains what will happen.  "Unmounting a filesystem makes its content unavailable to services and applications."

Eventually, there will be "teardown" information in there about services and sessions that keep this filesystem busy.

2021-11-04 13:41 UTC, garrett commented
Which filesystem is being unmounted? What device or RAID or whatever is it coming from? Is it currently in use? Is it dangerous to unmount the filesystem?

These are all questions I have that the dialog is not answering whatsoever.

2021-11-04 14:18 UTC, garrett requested changes
Oh, related to the previous comment: Please answer these questions in the dialog.

(I forgot to comment about that with a request changes. Whoops!)

Ideally, the modal wouldn't block, but other operations wouldn't be available until the unmounting is done. But having a confirmation dialog on an unmount probably makes sense anyway, I guess... at least if it's currently in use. So having it pause for a few seconds as the unmount finishes isn't the worst thing.

2021-11-05 07:41 UTC, mvollmer commented
> Which filesystem is being unmounted?

Let's add that to the title.

> What device or RAID or whatever is it coming from?

I think this is clear from where the "Unmount" menu entry is placed, no?

> Is it currently in use? Is it dangerous to unmount the filesystem?

We don't have that information yet, unfortunately.  If it is in use, the unmount will fail with an error message.

2021-11-08 13:10 UTC, garrett commented
>>    What device or RAID or whatever is it coming from?
>
> I think this is clear from where the "Unmount" menu entry is placed, no?

It's not clear in the dialog and people do misclick, get interrupted in the middle of tasks, etc. Having the necessary information to perform a task self-contained within a dialog is a good thing. Even if someone remembers what they were doing, it's a bit of reassurance to make sure they'd doing the right thing, especially on a task that could cause issues.



>>    Is it currently in use? Is it dangerous to unmount the filesystem?
>
> We don't have that information yet, unfortunately. If it is in use, the unmount will fail with an error message.

If we don't know if it's hazardous, then it could be. 

It would be nice to check ahead of time and present that information, instead of resulting with an error.

2021-11-18 13:11 UTC, mvollmer commented
> It would be nice to check ahead of time and present that information, instead of resulting with an error.

Alright! :-)  I have started working on this, and while it needs some more polish code-wise, this was pretty easy to get working, actually.  Looks like this (exactly like the NFS unmount dialog):

![image](https://user-images.githubusercontent.com/3228183/142421536-29f3cfb7-7a49-4671-86c7-8603864a6c9e.png)

2021-11-18 14:17 UTC, jpopelka commented
/packit build

2021-11-18 14:34 UTC, garrett commented
You need to have singular and plural wording (plus, I adjusted the text a little):

1. This filesystem is currently in use. Unmounting will stop all related processes.
2. This filesystem is currently in use. Unmounting will stop the related process.

Also, shouldn't process come first, before the session?

2021-11-18 14:45 UTC, jpopelka commented
/packit build

2021-11-23 10:47 UTC, garrett commented on pkg/storaged/storage.scss
> +}
We could use PF utils instead.

https://www.patternfly.org/v4/utilities/sizing

The class `pf-u-w-100` will make something 100% width. It also supports breakpoints and other sizing, but this is a 1:1 change.

To use it: Just make sure the utils CSS is imported and add the class to the element.

2021-11-25 13:09 UTC, mvollmer commented
This now also stops processes when doing teardown, and is getting a bit out of hand... I'll merge this with #16431.

2021-11-25 13:09 UTC, closed without merging