storaged: Change VDO package installation alert to a helper text
cockpit-project/cockpit pull request #16644
Opened 2021-11-24 13:29 UTC by martinpitt

Leftover from https://github.com/cockpit-project/cockpit/pull/16623#issuecomment-976407637

Looks like this now:
![shot](https://user-images.githubusercontent.com/200109/143247306-bafeeca3-e988-412d-be9b-9d8d03d24342.png)

2021-11-25 10:35 UTC, mvollmer approved these changes

2021-11-25 12:43 UTC, garrett requested changes
Better... but isn't the (i) icon supposed to be blue?

2021-11-25 13:24 UTC, martinpitt commented
@garrett : Maybe.. but that's what I meant earlier -- [HelperText](https://www.patternfly.org/v4/components/helper-text/#static-with-custom-icons) does not have an "info" variant, just "default" or "warning". I'll try for a bit to customize the color.

2021-11-25 13:52 UTC, martinpitt commented
As discussed, I switched that to the non-circled i icon, and kept it at the default color. Screenshot updated.

2021-11-29 13:46 UTC, garrett approved these changes
OK, with @martinpitt's help and a bunch of effort, I managed to test this live in a VM and it looks good to me! :+1: 

Thanks!

2021-11-29 13:56 UTC, merged