selinux: fix onSelect callback for selinux page
cockpit-project/cockpit pull request #16651
Opened 2021-11-26 09:49 UTC by KKoukiou

Commit 5108999badee3834fcc8e57222b5f9c82feae3a9 changed the
implementation of the ListingTable component and now the children rows
are not counting as extra rows, so the division by 2 is not needed.

Fixes #16640

2021-11-26 10:09 UTC, martinpitt approved these changes

2021-11-26 10:12 UTC, jelly approved these changes

2021-11-26 11:28 UTC, martinpitt commented
Oops, seems this is [actively breaking stuff](https://logs.cockpit-project.org/logs/pull-16651-20211126-095003-5090a93b-fedora-35/log.html#126)?

2021-11-26 11:29 UTC, martinpitt requested changes
test failure

2021-11-29 14:24 UTC, KKoukiou commented
@martinpitt the test failure was flakiness. Succeeded with the first retry. I tried also locally and it passes.

2021-11-29 14:27 UTC, martinpitt approved these changes
Ah, good, thanks!

2021-11-29 14:27 UTC, merged