use DynamicUser=yes for all cockpit components
cockpit-project/cockpit pull request #16811
Opened 2022-01-11 08:00 UTC by allisonkarlitskaya

Switch over to systemd allocating user IDs for us dynamically, dropping our static users.

We create these users dynamically:
 - `cockpit-session-socket` is the group owner of `/run/cockpit/session`
 - `cockpit-wsinstance-socket` is the group owner of all sockets in `/run/cockpit/wsinstance/`
 - `cockpit-tls` gets its own user
 - `cockpit-wsinstance-http{,s@}.service` each get a user.  In this case, I think the separate https instances even each get a separate user.

Right now it's not working.  There seem to be quite some edge cases, particularly involving the use of `DynamicUser` in combination with `SupplementaryGroup`.  Also, the approach to using virtual services to create the dynamic user is really strange.

I feel like we maybe shouldn't proceed here until we get better support for this from systemd.

 - [ ] #16808

2022-04-13 11:21 UTC, martinpitt commented
I filed https://github.com/systemd/systemd/issues/23067 to start the discussion.

2024-05-10 10:03 UTC, martinpitt commented
Rebased after the rebasing of #16808 and the recent heavy changes to sysuser management. Locally this at least works for a simple local session, let's see if there's any fallout beyond what's already in #16808.

2024-11-05 15:26 UTC, cgwalters commented
xref https://github.com/containers/bootc/issues/870 too here

2024-11-15 12:27 UTC, martinpitt commented
I want to see this all in action, the "look ma! no static users!" hands-free operation. I rebased/unconflicted this on top of current #16808, and fixed it up a little bit.

2024-11-17 08:54 UTC, martinpitt commented
[whoops](https://cockpit-logs.us-east-1.linodeobjects.com/pull-16811-cd548123-20241115-123524-debian-stable-other/log.html)! fixed.

2024-11-21 14:36 UTC, martinpitt requested changes
@allisonkarlitskaya This looks good in general (albeit annoyingly complicated, but that systemd request didn't go anywhere). There are [two](https://cockpit-logs.us-east-1.linodeobjects.com/pull-16811-165d0b61-20241121-133635-fedora-40-networking/log.html#56) [failures](https://cockpit-logs.us-east-1.linodeobjects.com/pull-16811-165d0b61-20241121-133633-fedora-40-other/log.html#164) still which perfectly reproduce locally.

Now, do you want me to work on this (like #16808 reverse ownership/review :grin: ) or want to do this yourself?

2024-11-21 14:36 UTC, martinpitt commented on src/systemd/cockpit-wsinstance-http.socket
> +After=cockpit-ws-user.service cockpit-wsinstance-socket-user.service
Likewise, this shouldn't be here. service socket depending on its own user (i.e. status quo) is ok of course, but not for foreign services.

2024-11-21 14:56 UTC, martinpitt commented on src/systemd/cockpit-session-socket-user.service
> +BindsTo=cockpit.service
That actually explains [this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-16811-165d0b61-20241121-133635-fedora-40-networking/log.html#56) -- The test *only* wants to start `cockpit-session.socket` and run its own cockpit-ws process. Like this, starting the session socket also starts cockpit.socket, which then fails due to port 9090 being busy already.

2024-11-21 20:03 UTC, martinpitt approved these changes
While this is quite a complex zoo of systemd units, it is rather straightforward and adequately easy to understand (at least for me). The benefits are definitively worth it, so let's do this!

@allisonkarlitskaya I dabbled with this (minor unit changes and test adjustments, and the package postinst cleanups), so please cross-check.

2024-11-22 08:54 UTC, merged

2024-11-22 09:01 UTC, martinpitt commented on src/systemd/cockpit.service.in
> +Requires=cockpit-ws-user.service cockpit-wsinstance-socket-user.service
We need to be careful about "cockpit-ws", as we used to have that static user, and /etc/cockpit/ws-certs.d/* may still be owned by it on old systems. In general, +1 for cleaning up the user names, though!

2024-11-22 09:47 UTC, martinpitt commented on src/systemd/cockpit.service.in
> +Requires=cockpit-ws-user.service cockpit-wsinstance-socket-user.service
For that reason I added postinst scripts which remove the cockpit-wsinstance user on upgrade, but not for cockpit-ws. I don't want to get into the business of randomly chowning files in /etc. You can just too easily screw up shared certificates, backups, break Ansible scripts, etc.