users: Rename locking in create new account
cockpit-project/cockpit pull request #16908
Opened 2022-02-02 15:52 UTC by tomasmatus

Fixes: #16886

2022-02-02 15:53 UTC, marusak commented
Can you please post screenshot how this looks like?

2022-02-03 00:24 UTC, tomasmatus commented
Somehow I managed to link incorrect issue and changed the text to "Disallow **account** usage" in the first screenshot
Both will be fixed tomorrow

2022-02-03 17:07 UTC, garrett requested changes
Cool! And thanks for the screenshots too!

However:

- The popover talks about it currently being disabled. We don't want two variants of the explanation for when it's checked and when it's not. It's better to explain the reason why without including the current state.
- The (?) icon should go to the right of the checkbox's text label, not next to options. (It should _not_ be part of the text label. Clicking on (?) should definitely _not_ toggle the checkbox.)

The popover text could probably be something like:

"Other authentication methods are still available even when password authentication is disallowed."

After you fix these issues, it's probably good to merge from my viewpoint.

2022-02-04 15:15 UTC, tomasmatus commented
I moved the (?) icon behind checkbox and changed popup message like you said.
Please have a look on new screenshots above

2022-02-09 15:43 UTC, garrett commented on pkg/users/account-create-dialog.js
> +                                  <Popover bodyContent={_("Other authentication methods are still available even when password authentication is disallowed")}>
```suggestion
                                  <Popover bodyContent={_("Other authentication methods are still available even when password authentication is disallowed.")}>
```

This popover has a sentence. It needs a period.

2022-02-09 15:45 UTC, garrett commented on pkg/users/account-details.js
> +                                                              <Popover bodyContent={_("Other authentication methods are still available even when password authentication is disallowed")}>
```suggestion
                                                              <Popover bodyContent={_("Other authentication methods are still available even when interactive password authentication is not allowed.")}>
```

Should

2022-02-09 15:46 UTC, garrett commented on pkg/users/account-create-dialog.js
> +                                  {_("Disallow password usage")}
```suggestion
                                  {_("Disallow interactive password")}
```

2022-02-09 15:47 UTC, garrett commented on pkg/users/account-details.js
> +                                                              {_("Disallow password usage")}
```suggestion
                                                              {_("Disallow interactive password")}
```

2022-02-09 15:47 UTC, garrett requested changes
This looks great!

Apologies for taking a while to get back to this.

I was looking at it again and some clearer text occurred to me. I'll add suggestions inline. Other than the text adjustments, it looks great though! (Sorry for changing things.)

2022-02-09 23:16 UTC, tomasmatus commented
No worries, this definitely sounds more polished.
I updated screenshots above.

2022-02-10 06:24 UTC, marusak commented
I think that [users: Rename locking in create new account](https://github.com/cockpit-project/cockpit/pull/16908/commits/d6bd4741165b4a0871058b1df40c34ccb0522907) and [users: Rename locking in create new account](https://github.com/cockpit-project/cockpit/pull/16908/commits/d6bd4741165b4a0871058b1df40c34ccb0522907) commits could be squashed. Can you please take a look?

2022-02-11 14:08 UTC, jelly commented on pkg/users/account-create-dialog.js
> +                              </>
If this is an issue , we need to change it here as well? https://github.com/cockpit-project/cockpit/blob/ba8700a6e501a9539b7a72d1d395649a8263cb69/pkg/users/account-roles.js#L74

2022-02-11 17:15 UTC, marusak commented on pkg/users/account-create-dialog.js
> +                              </>
I think so. Now when you click on the (?) it toggles the checkbox.

2022-02-14 10:34 UTC, garrett commented on pkg/users/account-create-dialog.js
> +                              </>
Correct. Having the icon in the label causes three issues:

1. Clicking on the (?) toggles the checkbox (and it should not).
2. Screen readers interpret the action incorrectly.
3. Labels should not have children that are widgets (such as buttons), so it's invalid HTML.
   - See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#accessibility_concerns

2022-02-14 17:22 UTC, tomasmatus commented on pkg/users/account-create-dialog.js
> +                              </>
OK @garrett  ! Moved the popover out of label and fixed the issue jelly mentioned.
I also updated screenshots.

2022-02-15 11:58 UTC, garrett approved these changes
LGTM (Looks Good To Me)! :+1: 

---

I did notice a weird error that does talk about unlocking and is therefore semi-related:

![Screenshot 2022-02-15 at 12-54-52 Accounts - garrett Bolt](https://user-images.githubusercontent.com/10246/154057508-f596b9b0-6067-4816-8a77-32dead5e3782.png)

I encountered this by unchecking the disallow password setting.

We probably want to change the text... and also perhaps make it disabled for a scenario like this?

Could we address it in a follow-up?

2022-02-15 12:08 UTC, marusak commented
> We probably want to change the text

I don't think that is our test, I guess it comes from `usermod` utlity

>  perhaps make it disabled for a scenario like this

If we can recognize this case, then yes. Can you please post reproducer for this? (what kind of account is created...)

>  follow-up?

yes, this PR is getting big on its own already :)

2022-02-15 12:58 UTC, merged