Nondestructive tests
cockpit-project/cockpit pull request #16943
Opened 2022-02-08 12:05 UTC by jelly

2022-02-08 14:21 UTC, martinpitt requested changes
Looks nice, thanks! However, please drop the no-test before the final run.

2022-02-08 14:21 UTC, martinpitt commented on test/verify/check-system-info
> +    @nondestructive
commit message subject has an excess "to"

2022-02-08 14:53 UTC, jelly commented
> Looks nice, thanks! However, please drop the no-test before the final run.

Ofcourse, I have some more WIP stuff locally, just wanted to run a single distro before running it on all as one distro should already shown some breakages.

2022-02-09 14:14 UTC, martinpitt approved these changes
Nice, thanks!

2022-02-09 14:14 UTC, martinpitt commented on test/verify/check-users-roles
> +        self.addCleanup(m.execute, "groupdel docker || true")
We shouldn't need this, testlib.py already restores passwd/group and so on. But of course it doesn't really hurt.

2022-02-09 14:15 UTC, merged