users: Add override button to confirm weak password
cockpit-project/cockpit pull request #16957
Opened 2022-02-09 11:20 UTC by tomasmatus

Fixes: #16612

2022-02-09 11:23 UTC, tomasmatus commented
Screenshots

![create_weak_password](https://user-images.githubusercontent.com/74668142/153190325-77057b92-d8a0-4d79-a263-57feb6d03f6d.png)
![set_weak_password](https://user-images.githubusercontent.com/74668142/153190329-8f377ad9-2a42-48e5-ad07-f8411e6219a6.png)

2022-02-09 11:31 UTC, marusak commented on pkg/users/password-dialogs.js
> +                        });
This is the same as from line 236. Could be factored out into function.

2022-02-09 11:32 UTC, marusak commented on pkg/users/account-create-dialog.js
> +                        });
This is the same as on line 260, could be factored into a function

2022-02-12 06:50 UTC, marusak commented
Almost all tests aborted due to some networking outage. I rebased and force pushed to get them a clean run

2022-02-12 08:56 UTC, marusak approved these changes
nice, thank you!

2022-02-15 10:09 UTC, marusak commented
Bad news @tomasmatus - this is in conflict now. Can you please rebase? Feel free to ping me and I can help you with it!

2022-02-16 06:35 UTC, marusak commented on test/verify/check-users
> -        b.wait_in_text("#accounts-create-dialog .pf-c-form__helper-text.pf-m-error", "Click Create again to use the password anyway.")
Oh, can you please replace these with checks that the new button was shown? It is equivalent to that.

2022-02-16 06:37 UTC, marusak requested changes
Can you please add two more checks into tests to make sure the logic is kept the same?

2022-02-16 06:37 UTC, marusak commented on test/verify/check-users
> -        b.wait_in_text("#account-set-password-dialog .pf-c-form__helper-text.pf-m-error", "Click Set password again to use the password anyway.")
Here as well please.

2022-02-16 06:39 UTC, marusak commented on test/verify/check-users
>          b.wait_not_present("#accounts-create-dialog .pf-c-form__helper-text.pf-m-error")
Plus here then you should wait for the button to disappear.

2022-02-16 06:40 UTC, marusak commented on test/verify/check-users
> -        b.wait_in_text("#account-set-password-dialog .pf-c-form__helper-text.pf-m-error", "Click Set password again to use the password anyway.")
And on line 257 you could wait for the button to not appear when `passwords do not match`.

2022-02-16 11:00 UTC, tomasmatus commented
Also added checks in a couple more places where the button should not appear.

2022-02-16 12:48 UTC, marusak approved these changes
Nice! Thank you :)

2022-02-16 13:43 UTC, merged