test: New libvirt uses bugzilla API key
cockpit-project/cockpit pull request #17049
Opened 2022-02-25 07:54 UTC by marusak

2022-02-25 08:20 UTC, martinpitt commented on test/verify/check-system-journal
> +        # Since libvirt version `2.15.2-7` bugzilla plugin does not require username and password but API key
It has nothing to do with libvirt, right? (comment/commit message)

2022-02-25 08:20 UTC, martinpitt commented on test/verify/check-system-journal
> +        if version.parse(libreport_version) > version.parse("2.15.2-6"):
Could this be the new default, and we handle user+password in fedora-35 (and possibly fedora-36, didn't check) as the "special case"? Then it's easier to spot with grepping the tests for these OS names, and we can clean it up over time.

2022-02-25 08:24 UTC, martinpitt commented on test/verify/check-system-journal
> +        if version.parse(libreport_version) > version.parse("2.15.2-6"):
I made a calendar entry in a month to clean this up.

2022-02-25 08:27 UTC, martinpitt approved these changes
Dakujem!

2022-02-25 08:40 UTC, martinpitt commented
Huh @ [c9s failure](https://artifacts.dev.testing-farm.io/927d997f-4d14-4c4e-8f37-6abe7f1ab7f3/):
```
  File "test/verify/check-system-journal", line 23, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```
Last-minute Python regression? Unrelated to this PR, but needs to be investigated.

2022-02-25 08:47 UTC, martinpitt requested changes
Oh wait, of course the packit failure *is* related -- it needs to add the new python3-packaging test dependency. Not sure if it is present on our images already. If not, I'd rather suggest to avoid it completely, and parse it ourselves. This hack won't have to stay for long.

2022-02-25 09:09 UTC, marusak commented
Yes, it is related. We need to have it in our task container - which we have. I was not thinking of testing farm. Let me add deps.

Also `TestJournal.testBasic` failed on [rhel-9-0](https://logs.cockpit-project.org/logs/pull-17049-20220225-081848-73397fa8-rhel-9-0/log.html), [debian-testing](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-17049-20220225-081848-73397fa8-debian-testing/log.html), [arch](https://logs.cockpit-project.org/logs/pull-17049-20220225-081848-73397fa8-arch/log.html) and [ubuntu-2004](https://logs.cockpit-project.org/logs/pull-17049-20220225-081848-73397fa8-ubuntu-2004/log.html). Always the same way. That cannot be coincidence, there must be more to it. Looking.

2022-02-25 09:16 UTC, marusak commented
waait, that? it expects to see in journal `Started slow10.service - Slowly log 10 identical lines.` but it sees `Started Slowly log 10 identical lines.`
How is this related to this change? It seems like image refresh issue - but how did that pass tests??

2022-02-28 12:13 UTC, martinpitt commented
[this failure](https://logs.cockpit-project.org/logs/pull-17049-20220228-112310-5d284728-fedora-35-devel/log.html#297-2) is in journal tests, but almost certainly unrelated to the change here. The ten thousand key collisions are also not new. Retrying.

2022-02-28 12:19 UTC, martinpitt approved these changes
Cheers!

2022-02-28 13:05 UTC, merged