base1: Default to base-10 units in cockpit.format_bytes*()
cockpit-project/cockpit pull request #17163
Opened 2022-03-22 06:35 UTC by martinpitt

This makes more sense as a default now. Storage and network devices,
network transmission speeds etc. have all been base-10 for decades. The
only place which is inherently/physically base-2 is total RAM size, and
reserved kdump memory because that's just what its API are. But these
special cases have all been explicitly moved to format as base-2
recently.

https://bugzilla.redhat.com/show_bug.cgi?id=1970119

2022-03-22 10:56 UTC, martinpitt commented
OK, this works in general. There are a [few expected pixel failures](https://logs-https-frontdoor.apps.ocp.ci.centos.org/logs/pull-17163-20220322-100044-02321839-fedora-35/log.html) which I'll update after this is otherwise ready. @marusak , @mvollmer , could you please do an initial review here? The test changes do show some impedance mismatch between the CLI tools like `lvcreate` (which *only* support base-2 units) and our new UI consistency aim for base-10 everywhere. I don't think it's too bad, but I'd welcome some more eyes on this. Thanks!

2022-03-22 11:53 UTC, marusak commented on test/verify/check-storage-stratis
> -        m.add_disk("4G", serial="DISK1")
4G meant 4GiB?

2022-03-22 12:20 UTC, martinpitt commented on test/verify/check-storage-stratis
> -        m.add_disk("4G", serial="DISK1")
Yes, the QEMU API works in base-2 units

2022-03-23 11:18 UTC, mvollmer commented
"Usage" on the overview still shows "GiB".

![image](https://user-images.githubusercontent.com/3228183/159687851-b337a16b-245c-4c41-9aba-79116896e72f.png)

2022-03-23 11:28 UTC, mvollmer commented
I wonder if we should change the order here to "GB", "GiB", "bytes", so that the familiar unit comes first.

![image](https://user-images.githubusercontent.com/3228183/159689349-db6ae5c7-1ce8-4d4e-a3b0-cce7d8953e2e.png)

2022-03-23 11:29 UTC, mvollmer requested changes
Overview "Usage" should use base10 as well.

2022-03-23 12:00 UTC, martinpitt commented
> "Usage" on the overview still shows "GiB".

That's the one I'm unsure about -- we discussed in the meeting that total memory size is "special". I don't have a machine where it is actually a round number (my laptop uses some of its 16 GiB for video memory, resulting in 15.4 GiB, and my other stuff is just VMs). I wouldn't mind too much with switching that over to base-10 as well, but there's a tension here -- being consistent wiht other pages vs. reflecting what your computer says on the tin.

> I wonder if we should change the order here to "GB", "GiB", "bytes", so that the familiar unit comes first.

Good idea, I'll do that.

2022-03-25 08:14 UTC, mvollmer commented
> > "Usage" on the overview still shows "GiB".
> 
> That's the one I'm unsure about -- we discussed in the meeting that total memory size is "special".

Ahh.  If it's not a bug then I am fine with it.

2022-03-25 13:26 UTC, martinpitt commented
I added another commit for swapping the binary/decimal units on the storage page, as above. Rebased, and re-running to see if that broke any test, and get a current pixel diff.

2022-03-25 18:20 UTC, martinpitt commented
Bah, right, [distropkg](https://logs.cockpit-project.org/logs/pull-17163-20220325-165806-84561a78-rhel-8-6-distropkg/log.html) -- I'll have to add back these special cases. These are not nearly as important as they used to be, but still a thing for RHEL 8.

2022-03-28 06:52 UTC, martinpitt commented
@mvollmer : This is ready for review now.

2022-03-28 07:35 UTC, mvollmer approved these changes

2022-03-28 07:38 UTC, merged