kdump: Show current journal when (re)starting service fails
cockpit-project/cockpit pull request #17214
Opened 2022-04-04 06:35 UTC by martinpitt

This is often due to some mis-configuration, such as an NFS remote
directory not existing on the server. There is currently no better
machine-readable API for showing the root cause of the error, so
show the journal of the recently failed kdump.service run.

Use the same `<CodeBlockCode>` formatting and size as the realmd
overview card.

https://bugzilla.redhat.com/show_bug.cgi?id=2062297

----
![wide](https://user-images.githubusercontent.com/200109/161486482-4c7fb949-b2b8-4740-9a69-cc8fb68a2e1c.png)

Narrow window:
![narrow](https://user-images.githubusercontent.com/200109/161486492-ecc9e0af-1bd1-4623-917e-b6a427ee2bc4.png)

The error message is still a bit confusing, I reported this in https://bugzilla.redhat.com/show_bug.cgi?id=2071529. After that gets fixed, it'll be okay. But showing the journal is still better than just "it failed".

2022-04-04 06:43 UTC, martinpitt commented on pkg/kdump/kdump-view.jsx
> +                            error.details = <CodeBlockCode>{ error.details }</CodeBlockCode>;
FTR: I first tried to add a `className="kdump-error-details"` here, but that completely destroy's PF's own CSS. This component isn't made for custom CSS classes, that's why I wrote the CSS in terms of its default `.pf-c-code-block__pre` class.

2022-04-04 08:15 UTC, martinpitt commented
Argh, the [c8s repo instability](https://copr-be.cloud.fedoraproject.org/results/packit/cockpit-project-cockpit-17214/centos-stream-8-x86_64/03942181-cockpit/builder-live.log.gz) is a bit unnerving.. Retrying, I just saw it fail the same way in a c-machines PR and now it succeeds.

2022-04-04 08:15 UTC, martinpitt commented
/packit build

2022-04-04 12:46 UTC, garrett requested changes
Inline alerts related to form submission are supposed to be at the top:

https://www.patternfly.org/v4/components/form/design-guidelines#error-validation-on-submission

That is a lot of text, so the details are supposed to be hidden by default and expandable. PatternFly's implementation looks like this:

https://www.patternfly.org/v4/components/alert#expandable

We currently don't use PF's expandable alerts (AFAIK), as they're relatively new. I think we have used expandable sections in alerts before for this:

https://www.patternfly.org/v4/components/expandable-section

We should probably start to use expandable alerts, however. The details link could also expand the ">" part, to make it more discoverable.

2022-04-05 06:41 UTC, martinpitt commented
With an expandable alert it would look like this:

![image](https://user-images.githubusercontent.com/200109/161693629-28962b40-d205-4823-ba3f-f7372956a5c6.png)

and once expanded:

![image](https://user-images.githubusercontent.com/200109/161693682-4edf9f43-3c1b-451b-8b8d-8e5b10444c9b.png)

However, I'm not very happy about this. The "service failed" error doesn't help with the "what do I need to fix", so unless the user is making the same error over and over and can guess it, it will have to be expanded. This is the original bug which this is aiming to fix.

However, the `<Alert isExpandable` is not a controlled component -- it means that we can neither expand it by default (which I'd like to do) nor can we add a "View Details.." link which could open it, as the expandedness is simply not controllable by code. This can probably be hacked somehow, with rebuilding the Alert ourselves, or putting an [ExpandableSection](https://www.patternfly.org/v4/components/expandable-section) inside the alert. But first I'd like to negotiate a bit whether we should really hide this by default -- I rather strongly believe that we shouldn't.

> Inline alerts related to form submission are supposed to be at the top.

OK - this is a widely used component (cockpit-components-dialog.jsx), so if I move it here, it'll also move on all the other pages. I can do this first, and block on that PR.

2022-04-05 10:03 UTC, martinpitt commented
@garrett : I sent #17221 to move dialog errors to the top. IMHO we should do this in one go to remain consistent, and decouple that from this PR. So what remains here is to discuss the expander stuff above. Thanks!

2022-04-06 05:13 UTC, martinpitt commented
@garrett: I reworked this a bit. I cleaned up the systemd unit noise from the error message, and also dropped that silly "RestartUnit failed with result failed" part of the title. Screenshots updated, they look a lot cleaner now. I also showed a different error for SSH (which can also fail for any number of reasons). I am convinced that we should not hide these messages by default.

2022-04-06 08:39 UTC, garrett commented
> I reworked this a bit. I cleaned up the systemd unit noise from the error message, and also dropped that silly "RestartUnit failed with result failed" part of the title. Screenshots updated, they look a lot cleaner now. I also showed a different error for SSH (which can also fail for any number of reasons). I am convinced that we should not hide these messages by default.

OK, better! I'm looking forward to the move to the top and the expanded version.

Thanks for adjusting this all!

2022-04-08 03:49 UTC, martinpitt commented
@marusak , @jelly : Friendly review ping? Thanks!

2022-04-08 05:49 UTC, marusak approved these changes
Nice, thank you!

2022-04-08 05:49 UTC, merged