firewall: Allow editing custom services
cockpit-project/cockpit pull request #17436
Opened 2022-06-07 11:08 UTC by marusak

Fixes #12287

![Screenshot from 2022-06-07 13-07-56](https://user-images.githubusercontent.com/12330670/172365272-2ae47b9e-e216-4399-85b1-dfe11d818c80.png)

![Screenshot from 2022-06-07 13-08-11](https://user-images.githubusercontent.com/12330670/172365270-cbd83ce2-cca3-4853-9e21-b6793a607dc6.png)

2022-06-08 06:02 UTC, martinpitt requested changes
Thank you!

2022-06-08 06:02 UTC, martinpitt commented on test/verify/check-networkmanager-firewall
> +        b.click("#add-services-dialog button.btn-cancel")
This belongs after the `wait_in_text` in line 407 IMHO.

2022-06-08 06:02 UTC, martinpitt commented on test/verify/check-networkmanager-firewall
> +        save("custom--80-82-echo-83-123-snmp", "80-82, 8", "83-123, 161", "edited snmp firewall rule", 'Edit service')
Does that validate the actual settings in firewalld anywhere? That tcp/7 is really closed, tcp/8 got opened, and UDP survived?

2022-06-08 06:36 UTC, marusak commented on pkg/networkmanager/firewall-client.js
> +                                              'update2', [{ description: { t: 's', v: desc }, ports: { t: 'a(ss)', v: ports } }])
Yes it does. You give it a new value for ports and it changes it to them. Whether you add, remove or change completely, it just applies the new ports.

2022-06-08 08:29 UTC, marusak commented
`RuntimeError: TypeError: Cannot read properties of null (reading '8')` oopses sometimes on [rhel](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17436-20220608-072422-0f7cc838-rhel-8-7/log.html#305-2). I will need to debug this.

2022-06-09 11:54 UTC, garrett submitted a review, later dismissed
The title is missing the word "custom". So the title would be this instead:

Edit custom service in Fedora Workstation Zone

---

Additionally: That alert should be a helpertext. (Alerts have to be at the top of modals, not at the bottom, but alerts should be reactive not proactive. Proactive text is anticipatory and should be helper text at the bottom. In other words: The ahead-of-time warning text has the right idea in the right place, just the wrong widget type.)

This warning text change could either be a separate commit or a follow-up PR.

2022-06-10 09:08 UTC, marusak commented
> The title is missing the word "custom". So the title would be this instead:
> Edit custom service in Fedora Workstation Zone

Done

> `RuntimeError: TypeError: Cannot read properties of null (reading '8')` oopses sometimes on [rhel](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17436-20220608-072422-0f7cc838-rhel-8-7/log.html#305-2).

Figured it out and fixed.

> Additionally: That alert should be a helpertext

Right. I haven;t touched that in this PR. Not super sure how it should look like so I don't want to block this PR on it. Lets adjust it outside of this PR.

2022-06-14 03:30 UTC, martinpitt approved these changes
Yay, dakujem! Can you please update the screenshot and add a release note?

2022-06-14 04:20 UTC, merged