static: drop Internet Explorer workaround for baseUri
cockpit-project/cockpit pull request #17445
Opened 2022-06-08 15:41 UTC by jelly

Since Internet Explorer is no longer support and Microsoft Edge does
support document.baseUri this can be dropped.

2022-06-08 15:57 UTC, garrett requested changes
No, the login page is special.

We still need to support Internet Explorer to the extent to say that it is not supported.

Removing this code will break the message of not being supported on IE.

2022-06-08 15:57 UTC, garrett commented
Believe it or not, people still use IE. We need to tell them they're not supported instead of showing a broken page.

2022-06-09 07:30 UTC, jelly commented
Actually this does not break the page at all, it breaks the login functionality and I believe users should already see an message on the login page then that their "browser is not supported".

2022-06-20 12:18 UTC, martinpitt commented
@jelly : If you want to go ahead with this, can you please rebase? Note that my PR #17469 also deletes this code en passant; I just don't know how fast that will land.

2022-06-20 14:40 UTC, martinpitt approved these changes
Thanks!

2022-06-20 14:41 UTC, merged