kdump: show tooltip when crashkernel is not configured
cockpit-project/cockpit pull request #17452
Opened 2022-06-14 09:22 UTC by jelly

Disable the service switch and show a tooltip when the kernel's command
line lacks the crashkernel option. Without this change a user can try to
enable the service which will instantly fail without an indication that
crashkernel has to be configured upfront.

2022-06-14 12:27 UTC, jelly commented
rawhide failure is related to an update to firefox last night.

2022-06-14 15:27 UTC, martinpitt requested changes
Thanks, this is a nice idea! Let's just fix the error handling.

2022-06-14 15:27 UTC, martinpitt commented on pkg/kdump/kdump.js
> +            });
Is it guaranteed to be enabled in /proc/cmdline always? I.e. there's no way to set that in the kernel config?

Please handle failures. read() returns `null` if the file does not exist (yes, strange API), so calling `null.indexOf()` will crash. Permission errors will cause a rejection as usual. I know it's unlikely, but in principle we can connect to LXC or nspawn containers or have an environment where an unprivileged user can't read the file.

2022-06-15 04:27 UTC, martinpitt approved these changes
Dank je wel!

2022-06-15 04:28 UTC, merged