login: Fix username/password autofill
cockpit-project/cockpit pull request #17730
Opened 2022-09-12 13:23 UTC by skazi0

Some browsers get confused when there is some type="password" field before the username field. Re-ordering mutually exclusive parts of the login page should not have any visible impact but fixes automatic filling of credentials saved in browser's password manager.

2022-09-12 14:56 UTC, garrett requested changes
Interesting idea.

Which browsers though? I tried Firefox, Chrome, and GNOME Web (WebKit), and couldn't get password management to work as expected (prefilling saved password), except for the username.

2022-09-12 16:27 UTC, skazi0 commented
@garrett I tried applying those changes in place it it looks like after moving the `conversation-input` down, it *does* fill the form correctly *but* one piece of JS cleans the password explicitly. It was added as part of https://github.com/cockpit-project/cockpit/commit/74e58fc8c12a4f3fa0033bbdd3f9be79519d416f so I assume it was meant to be done only for conversation auth. I don't have a test env for checking how this works in those cases. Can you test this somehow?

2022-09-13 11:55 UTC, garrett approved these changes
I've tried this latest iteration locally and also in a VM and found it working in Firefox and Chrome.

Thanks!

2022-09-13 11:57 UTC, garrett commented
> It was added as part of https://github.com/cockpit-project/cockpit/commit/74e58fc8c12a4f3fa0033bbdd3f9be79519d416f so I assume it was meant to be done only for conversation auth. I don't have a test env for checking how this works in those cases. Can you test this somehow?

We might want to have @mvollmer look at the auth stuff. He's the one who worked the most on it recently. @martinpitt could also be good too. We don't want to break the login page accidentally... :sweat_smile:

2022-09-14 07:23 UTC, marusak approved these changes
I have tested the change in .js and could not find any case where this would be an issue, seems fine!

2022-09-14 07:24 UTC, merged