pkg: enable object property newline rule
cockpit-project/cockpit pull request #17890
Opened 2022-11-07 16:28 UTC by jelly

This is more readable and automatically applied using `eslint --fix`.

2022-11-07 17:47 UTC, cockpituous commented on pkg/lib/cockpit-components-plot.jsx
> +                right: Math.max(selection.start, x)
These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17890-20221107-162851-fa6168ae-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-07 17:47 UTC, cockpituous commented on pkg/storaged/iscsi-panel.jsx
> +                name: session.data.target_name || "",
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17890-20221107-162851-fa6168ae-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-07 17:47 UTC, cockpituous commented on pkg/storaged/stratis-panel.jsx
> +        go: () => cockpit.location.go(["pool", uuid])
These 7 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17890-20221107-162851-fa6168ae-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-07 17:47 UTC, cockpituous commented on pkg/storaged/vdos-panel.jsx
> +        devname: vdo.dev,
These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17890-20221107-162851-fa6168ae-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-07 18:17 UTC, martinpitt requested changes

2022-11-07 18:17 UTC, martinpitt commented on pkg/lib/cockpit.js
> +writable: false
And this is even worse

2022-11-08 08:53 UTC, jelly commented on pkg/lib/cockpit.js
> +writable: false,
Ugh... `eslint --fix` does not fix super well

2022-11-08 09:15 UTC, martinpitt approved these changes
Cheers!

2022-11-08 10:22 UTC, cockpituous commented on pkg/lib/cockpit-components-plot.jsx
> +                right: Math.max(selection.start, x)
These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17890-20221108-090107-5c6c50b0-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-08 10:22 UTC, cockpituous commented on pkg/storaged/iscsi-panel.jsx
> +                name: session.data.target_name || "",
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17890-20221108-090107-5c6c50b0-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-08 10:22 UTC, cockpituous commented on pkg/storaged/stratis-panel.jsx
> +        go: () => cockpit.location.go(["pool", uuid])
These 7 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17890-20221108-090107-5c6c50b0-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-08 10:22 UTC, cockpituous commented on pkg/storaged/vdos-panel.jsx
> +        devname: vdo.dev,
These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17890-20221108-090107-5c6c50b0-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-08 21:13 UTC, merged