systemd: remove position="right" for service dropdown
cockpit-project/cockpit pull request #17926
Opened 2022-11-16 17:17 UTC by jelly

This causes issue on mobile and with very tiny service names which makes the dropdown disappear under the sidebar menu on mobile and small screens.

See https://github.com/cockpit-project/cockpit/issues/17596#issuecomment-1317365314 for screenshots

2022-11-17 08:10 UTC, garrett requested changes
No, this isn't the right fix. I explained it in the bug @ https://github.com/cockpit-project/cockpit/issues/17596#issuecomment-1195615379, with a workaround for us, based on brreakpoints.

The proper fix is for PatternFly to fix their auto layout. They've been working on that.

Meanwhile, we need one alignment for desktop and another for mobile.

JSX:
```
<Dropdown
  alignments={{
    default: 'right',
    sm: 'left'
  }}
  ...
>
```

But then a little bit of CSS to improve things too:

```scss
.service-top-panel .pf-c-dropdown {
  flex: auto;
  justify-content: end;
}
```

But this CSS could be in the className in JSX with helper classes:
`pf-u-flex-grow-on-sm pf-u-justify-content-flex-end-on-sm`

2022-11-17 08:12 UTC, garrett commented on pkg/systemd/services/service-details.jsx
>                    dropdownItems={actions} />
```suggestion
                  className='pf-u-flex-grow-on-sm pf-u-justify-content-flex-end-on-sm'
                  alignments={{ default: 'right', sm: 'left' }}
                  dropdownItems={actions} />
```

2022-11-17 08:13 UTC, garrett commented on pkg/systemd/services/service-details.jsx
>                    dropdownItems={actions} />
It should probably be something like this for a proper fix. Screenshots in the comment I posted on the issue.

2022-11-17 09:00 UTC, garrett commented
Oh, I forgot that PF changed auto placement. Whoops! Checking out this PR to test it locally. A simpler fix is almost always better, right? :grin:

2022-11-17 09:28 UTC, garrett requested changes
Still broken for me on mobile...

![image](https://user-images.githubusercontent.com/10246/202408230-4fc3b55a-938a-40ef-8d3a-7efc0a633452.png)

2022-11-17 11:14 UTC, jelly commented
> Still broken for me on mobile...
> 
> ![image](https://user-images.githubusercontent.com/10246/202408230-4fc3b55a-938a-40ef-8d3a-7efc0a633452.png)

Right, I only tested it with a small unit name.. sorry!

2023-01-05 20:05 UTC, KKoukiou commented
This solution wont' work as is. Closing to clean up PR list, and you can always reopen when you work on this.

2023-01-05 20:05 UTC, closed without merging