shell: fix open state toggling of the dropdowns on the shell
cockpit-project/cockpit pull request #17959
Opened 2022-11-28 12:52 UTC by KKoukiou

Explanation of the commit message in inline comment. For more info on this HACK please read https://github.com/wellyshen/react-cool-onclickoutside/blob/master/README.md#detecting-iframe-clicks

Fixes #17944

2022-11-28 13:59 UTC, jelly submitted a review, later dismissed
TIL!

I'd have never thought about our iframes causing this!

2022-11-28 14:20 UTC, cockpituous commented on pkg/shell/topnav.jsx
> +        window.removeEventListener("blur", this.handleClickOutside);
These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17959-20221128-125239-e85efe43-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-28 17:23 UTC, garrett requested changes
This is working as I would expect for the help and session  menus.

However, it's not working for the host and system menus in mobile mode.

While this is already a great improvement, would it be possible to add support for the other menus too? Thanks!

(Unrelated: I also see there's a dark theme problem with the host switcher in mobile now. So when you're checking mobile, don't be surprised.)

2022-11-29 11:49 UTC, KKoukiou commented
@garrett fixed the system selector (although it's actually not much relevant as it takes most of the space in mobile) but the hosts one I won't fix in this commit because the code for hosts expander code is mixed in for mobile and desktop. I am sure we only want to affect the mobile one as you said, and that will require a quite big rewrite of the code in order that it's achievable.

2022-11-29 13:23 UTC, cockpituous commented on pkg/shell/topnav.jsx
> +        window.removeEventListener("blur", this.handleClickOutside);
These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17959-20221129-115044-2afa12d5-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

2022-11-29 15:03 UTC, jelly approved these changes

2022-11-29 16:04 UTC, garrett commented
@KKoukiou: I had already fixed the host selector in the dark theme PR; I was mentioning it here just to not be surprised about it being broken in this PR. :grin: We'll have a fix for it landing soon, one way or another.

2022-11-29 16:05 UTC, merged