Move dark theme handling to pkg/lib/cockpit-dark-theme.js out of the shell
cockpit-project/cockpit pull request #18042
Opened 2022-12-15 12:02 UTC by KKoukiou

There are scenarios where cockpit-system (package shipping shell code) is not installed: e.g. when using cockpit-desktop or embedding, the shell isn't required.

On this scenario users would miss the support for dark theme. Therefore this commit will move the theme handling to a new file, in pkg/lib which should be included in all cockpit pages.

2022-12-16 10:15 UTC, jelly commented
Moving the switching away from the shell also breaks here, I see dark flashes when I set dark theme in developers tools and override it in Cockpit then the outer shell does not switch.

![Screenshot from 2022-12-16 11-13-18](https://user-images.githubusercontent.com/67428/208076270-3a318dea-96f2-456d-8096-46de28afe5fe.png)

2022-12-16 16:08 UTC, jelly requested changes
I've debugged the flickering issue a bit and it seems to occur on chrome/chromium when:

Set the system settings to dark, override in Cockpit to light mode, load a new page or F5.

I dropped `class="pf-theme-dark"` from `pkg/storaged/index.html` and then the issue is gone. But that obviously won't fix it as they we will get a white flash.

So I guess either our JavaScript is too late or Chrome already parses and displays CSS before the JavaScript is executed.

2022-12-19 16:15 UTC, jelly requested changes

2022-12-20 08:53 UTC, KKoukiou commented on pkg/lib/cockpit-dark-theme.js
> +        console.debug([`cockpit-dark-theme: ${document.documentElement.id}:`, ...arguments].join(" "));
This is just for debugging. I think its fine. Let's not overcomplicate it.

2022-12-20 15:07 UTC, jelly approved these changes

2022-12-20 15:10 UTC, jelly commented
webpack-jumpstart fails due to re-pushing, rhel-8-7 will be hard to get green as TestAccounts.testBasic will flake for a while, we also dropped this from our testing matrix. So let's merge it! Thanks @KKoukiou for fixing it (again)!

2022-12-20 15:12 UTC, merged