storage: Don't accidentally leave the filesystem unmounted
cockpit-project/cockpit pull request #18180
Opened 2023-01-16 14:29 UTC by mvollmer

The "Mount configuration" dialog unmounts the filesystem, changes fstab, and then re-mounts it.  However, if neither the mountpoint nor the options would change, the last two steps would be skipped, leaving the filesystem accidentally unmounted.

This is fixed here by not optimizing empty changes.  This is what other storage dialogs also do.

2023-01-16 15:28 UTC, martinpitt reviewed
Danke! This shouldn't be too hard to cover in a test?

2023-01-17 10:19 UTC, mvollmer commented
> This shouldn't be too hard to cover in a test?

No, and it lead to a number of additional fixes... :-)

2023-01-17 10:42 UTC, martinpitt commented
```
# test/verify/check-storage-mounting:22:1: F401 'testlib.sit' imported but unused
# test/verify/check-storage-mounting:458:1: E305 expected 2 blank lines after class or function definition, found 1
```

2023-01-17 10:45 UTC, martinpitt requested changes
Thanks! Some debugging leftovers, and flake8 issues (see above), otherwise LGTM!

2023-01-17 10:45 UTC, martinpitt commented on pkg/storaged/fsys-tab.jsx
> +        console.log("C", JSON.stringify({ new_dir, new_opts, old_dir, old_opts }));
debugging leftover

2023-01-17 10:45 UTC, martinpitt commented on test/verify/check-storage-mounting
> +from testlib import test_main, sit
debugging leftover

2023-01-17 10:45 UTC, martinpitt commented on test/verify/check-storage-mounting
> +        m.upload(["/home/mvo/work/cockpit/dist/storaged"], "/usr/share/cockpit")
debugging leftover

2023-01-17 11:20 UTC, cockpituous commented on pkg/storaged/fsys-tab.jsx
> +                                                            })
These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18180-20230117-101932-3c5e4716-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-01-17 11:20 UTC, cockpituous commented on pkg/storaged/fsys-tab.jsx
> +                                                            .then(() => Promise.reject(error)));
These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18180-20230117-101932-3c5e4716-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-01-18 09:29 UTC, martinpitt approved these changes
Cheers!

2023-01-18 13:19 UTC, merged