python: Properly report HTTPExceptions
cockpit-project/cockpit pull request #18283
Opened 2023-02-02 14:22 UTC by martinpitt

If reading the response throws a http.client exception, close the channel with that error message, instead of crashing the thread and letting it log tracebacks. This does not change observable behaviour much, but cleans up unexpected error messages.

---

This will fix the last [podman failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1196-20230202-124820-1dc12492-fedora-37-pybridge/log.html) with the pybridge, see https://github.com/cockpit-project/cockpit-podman/pull/1196

2023-02-02 14:46 UTC, jelly submitted a review, later dismissed

2023-02-02 14:46 UTC, jelly commented on src/cockpit/channels/http.py
> +            logger.debug('HTTP %s reading response failed: %s', error)
This passes one argument while the format string expects two? Also shouldn't we call `str(error`)

2023-02-03 08:38 UTC, allisonkarlitskaya requested changes

2023-02-03 08:38 UTC, allisonkarlitskaya commented on src/cockpit/channels/http.py
> +            connection.close()
This goes in `finally:`

2023-02-03 08:40 UTC, martinpitt commented on src/cockpit/channels/http.py
> +            connection.close()
Thanks! Done.

2023-02-03 08:41 UTC, allisonkarlitskaya approved these changes
:+1: thx

2023-02-03 10:27 UTC, merged