feat(cockpit-rsync-plugin): add development support for remote hosts
cockpit-project/cockpit pull request #18325
Opened 2023-02-10 19:47 UTC by shawly

Adds the variable `RSYNC_DEVEL` for starter-kit.

`RSYNC_DEVEL` uses `~/.local/share/cockpit/` instead of `/usr/local/share/cockpit/`.
This helps for developing on a remote host.

2023-02-11 05:32 UTC, martinpitt requested changes
Thanks, this is a nice idea! Some bikeshedding/minor cleanups.

2023-02-11 05:32 UTC, martinpitt commented on pkg/lib/cockpit-rsync-plugin.js
> +            this.cockpit_dir = process.env.RSYNC ? "/usr/local/share/cockpit/" : "~/.local/share/cockpit/";
this.rsync_dir

2023-02-11 05:32 UTC, martinpitt commented on pkg/lib/cockpit-rsync-plugin.js
> +            this.ssh_host = process.env.RSYNC ? process.env.RSYNC : process.env.RSYNC_DEVEL;
process.env.RSYNC || process.env.RSYNC_DEVEL

2023-02-11 05:32 UTC, martinpitt commented on pkg/lib/cockpit-rsync-plugin.js
> +            if (process.env.RSYNC || process.env.RSYNC_DEVEL) {
Duplicating this is a bit ugly. Please rather check `if (this.ssh_host)`.

2023-02-11 11:18 UTC, shawly commented
@martinpitt I refactored the stuff you mentioned and also had to add braces to the if condition in the constructor since the ssh command would be executed otherwise! Thanks for reviewing!

2023-02-12 06:41 UTC, martinpitt approved these changes
Thank you, this looks nice! I just saw that neigher is documented in HACKING.md, we should fix that.

Triggered tests, will merge once they are green.

2023-02-13 06:48 UTC, merged

2023-02-13 17:02 UTC, shawly commented
Thank you @martinpitt!