Show shell and home directory in user's details page
cockpit-project/cockpit pull request #18470
Opened 2023-03-08 13:12 UTC by skobyda

Split from https://github.com/cockpit-project/cockpit/pull/18234 as recommended

![Screenshot from 2023-03-08 14-11-55](https://user-images.githubusercontent.com/42733240/223722047-2885b1d2-2bbb-4694-8135-398d51a79387.png)

2023-03-08 13:54 UTC, martinpitt requested changes
Can you please add a corresponding integration test? Also, does this need a pixel ref update?

2023-03-15 10:05 UTC, martinpitt requested changes
see above

2023-03-16 09:57 UTC, skobyda commented
In the end, I added getUserAddDetails helper function to tests which parses defaults of useradd, since that's the approach which I plan to use futher in https://github.com/cockpit-project/cockpit/pull/18234

2023-03-16 13:56 UTC, skobyda commented
Tests seems pretty green, apart from some flakes. I think the PR is ready

2023-03-17 05:05 UTC, martinpitt approved these changes
LGTM, thanks! Still fighting a bit with that i386 unit-test, previous two attempts failed with a podman error.

2023-03-17 05:12 UTC, merged