systemd: set a different text color in the dark theme
cockpit-project/cockpit pull request #18573
Opened 2023-03-28 10:58 UTC by jelly

The current version is barely readable in the dark theme.

Before:

![image](https://user-images.githubusercontent.com/67428/228215138-36c5bb1c-1c34-40e4-a2ce-eaa2d0805bae.png)

After:

![image](https://user-images.githubusercontent.com/67428/228215185-ba9df52c-0deb-4c66-9691-49fbc98ad574.png)

2023-03-28 11:19 UTC, martinpitt submitted a review, later dismissed

2023-03-28 14:53 UTC, KKoukiou requested changes
The proper solution is to use <Text component={TextVariants.small}> which work as expected in dark theme and then we also don't need the rest of custom CSS for font size, color and such.

2023-03-28 14:55 UTC, jelly commented
> The proper solution is to use which work as expected in dark theme and then we also don't need the rest of custom CSS for font size, color and such.

I think you mean using the correct PF component instead of our custom div/css's?

2023-03-28 19:15 UTC, KKoukiou commented
> > The proper solution is to use which work as expected in dark theme and then we also don't need the rest of custom CSS for font size, color and such.
> 
> I think you mean using the correct PF component instead of our custom div/css's?

Heh the text inside `<` `>` in markdown got hidden. Fixed.

2023-03-29 14:51 UTC, jelly commented
> The proper solution is to use `<Text component={TextVariants.small}>` which work as expected in dark theme and then we also don't need the rest of custom CSS for font size, color and such.

Our <span has `--pf-global--FontSize--xs` for which the Text component does not have, it's smallest is `small` which is bigger then `xs`. The HTML variant does have xs https://www.patternfly.org/v4/utilities/text/#font-size 

So I guess we first have to create an PF issue and then we can use the `Text` component. Aside from that, it should use a  different color then the default `Text` and Flex for layout.

![image](https://user-images.githubusercontent.com/67428/228578256-7a13e3a4-a618-4431-a0f6-b022f4df84dc.png)

2023-04-05 07:36 UTC, KKoukiou commented
> > The proper solution is to use `<Text component={TextVariants.small}>` which work as expected in dark theme and then we also don't need the rest of custom CSS for font size, color and such.
> 
> Our <span has `--pf-global--FontSize--xs` for which the Text component does not have, it's smallest is `small` which is bigger then `xs`. The HTML variant does have xs https://www.patternfly.org/v4/utilities/text/#font-size
> 
> So I guess we first have to create an PF issue and then we can use the `Text` component. Aside from that, it should use a different color then the default `Text` and Flex for layout.
> 
> ![image](https://user-images.githubusercontent.com/67428/228578256-7a13e3a4-a618-4431-a0f6-b022f4df84dc.png)

We can keep the font-xs class, that's not a problem. I am just proposing to not add this extra custom CSS for background color - when PF supports that fine.

2023-04-12 09:03 UTC, merged