#18424 Issue: Added functions reboot and wait_reboot
cockpit-project/cockpit pull request #18644
Opened 2023-04-14 22:24 UTC by mrdetective

I have made some updates to the `MachineCase` class in the `testlib.py` file. Specifically, I have added two new functions: `reboot` and `wait_reboot`. These functions now support a `timeout_sec` parameter, and I have implemented function overloading to achieve this.

Additionally, I have included a call to `self.machine.allow_restart_journal_messages()` within both of these functions. This will automatically trigger whenever either of the two functions is called.

2023-04-17 05:18 UTC, KKoukiou requested changes

2023-04-17 05:18 UTC, KKoukiou commented on test/common/testlib.py
> +    def reboot(self):
Remove duplicate.

2023-04-17 05:18 UTC, KKoukiou commented on test/common/testlib.py
> +    def wait_reboot(self):
Please remove duplicate.

2023-04-17 05:18 UTC, KKoukiou commented on test/common/testlib.py
> +    def wait_reboot(self):
This is great, but nothing actually uses it. Please adjust the existing tests to use the new self.wait_reboot. For example testTracer in test/verify/check-packagekit.

    Adjust the usage of m.wait_reboot in test/verify/check-packagekit
    Prepare a test virtual machine: ./test/image-prepare -q fedora-37
    Run the test: TEST_OS=fedora-37 ./test/verify/check-packagekit -vst

If this works as expected (test passes), adjust all other occurrences of m.wait_reboot in test/verify.

See original comment at https://github.com/cockpit-project/cockpit/pull/18431/files#r1122949054

2023-04-17 17:17 UTC, mrdetective commented
Thank you for reviewing my changes. I have made the requested modifications, but I'm unsure about how to test them. Could you please provide me with some guidance or resources on how to properly test the changes?

2023-04-18 10:38 UTC, KKoukiou commented
> Thank you for reviewing my changes. I have made the requested modifications, but I'm unsure about how to test them. Could you please provide me with some guidance or resources on how to properly test the changes?

No problem please take a look here https://github.com/cockpit-project/cockpit/blob/main/test/README.md and reach out to me on [matrix](https://github.com/cockpit-project/cockpit/wiki/About#contact-developers--stay-up-to-date) in case you need further guidance.

2023-04-19 21:21 UTC, mrdetective commented
Based on the information you provided, it sounds like @jelly suggested making changes to the `wait_reboot()` function in all the places within test\verify. It is unclear whether the `reboot()` function needs to be modified in the same way without further context.  
And also for functions without parameters can I simply put `(timeout_sec = 0)`? 
for example,  `m.reboot()` will become `m.reboot(timeout_sec = 0)`

2023-04-20 08:28 UTC, jelly commented
> Based on the information you provided, it sounds like @jelly suggested making changes to the `wait_reboot()` function in all the places within test\verify. It is unclear whether the `reboot()` function needs to be modified in the same way without further context. And also for functions without parameters can I simply put `(timeout_sec = 0)`? for example, `m.reboot()` will become `m.reboot(timeout_sec = 0)`

The suggestion is to wrap the Machine's reboot function in the testlib MachineCase class, which you did. And then to replace our tests which call `m.reboot()` with `self.reboot()`.

2023-04-21 06:37 UTC, KKoukiou requested changes

2023-04-21 06:37 UTC, KKoukiou commented on test/verify/check-kdump
>          self.allow_restart_journal_messages()
No allow_restart_journal messages() call can be removed from all of the tests, when ths follows the new reboot or wait_reboot calls.

2023-04-25 07:17 UTC, KKoukiou requested changes
git grep allow_restart_journal_messages. There are a bunch of occurances still that can be removed. Check if in the same test the this is called we do call the reboot functions. If so the alow_restart_journal_messages call can be removed now safely.

2023-04-25 07:17 UTC, KKoukiou commented on test/common/testlib.py
> +    def reboot(self, timeout_sec):
Needs empty line before new function

2023-04-25 07:17 UTC, KKoukiou commented on test/common/testlib.py
> +
Remove these two extra new lines.

2023-04-25 07:17 UTC, KKoukiou commented on test/common/testlib.py
> +
Run ./test/static-code to see the linter errors.

2023-04-25 07:17 UTC, KKoukiou commented on test/common/testlib.py
> +    def wait_reboot(self, timeout_sec):
timeout_sec needs a default value, None.

2023-04-25 07:17 UTC, KKoukiou commented on test/verify/check-system-realms
> -        m.wait_reboot()
self.allow_restart_journal_messages() can be removed on line 344.

2023-04-25 07:17 UTC, KKoukiou commented on test/verify/check-system-services
> -        m.reboot()
self.allow_restart_journal_messages() can be removed on line 344.

2023-04-25 07:17 UTC, KKoukiou commented on test/verify/check-system-info
> +        self.wait_reboot()
self.allow_restart_journal_messages() can be removed from line 988.

2023-05-02 07:01 UTC, KKoukiou requested changes
All tests that are affected now fail with 'AttributeError: 'VirtMachine' object has no attribute 'allow_restart_journal_messages''

I think you need to call it like, self.allow._restart...() instead of self.machine.allow_restart() in the reboot and wait_reboot methods.

2023-05-05 09:13 UTC, KKoukiou commented
@mrdetective this needs a rebase.

2023-07-21 12:27 UTC, KKoukiou commented
Closing because of inactivitry. Feel free to reopen if interested.

2023-07-21 12:27 UTC, closed without merging