storage: Support stopped Stratis pools
cockpit-project/cockpit pull request #18679
Opened 2023-04-20 12:59 UTC by mvollmer

Stopped pools are a generalization of locked encrypted pools introduced in newer versions of Stratis.  Now every kind of pool can be inactive, not just encrypted ones.

2023-04-20 13:02 UTC, mvollmer commented
Stopped pools look like this on the overview now:

![image](https://user-images.githubusercontent.com/3228183/233374156-110b538e-bbeb-4e5c-8d63-8edabb1ed681.png)

Maybe there is a better icon to use for the "Start" action?

2023-04-20 14:07 UTC, cockpituous commented on pkg/storaged/client.js
> +                client.stratis_start_pool = (uuid) => {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230420-131050-f1115ac6-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-20 14:07 UTC, cockpituous commented on pkg/storaged/content-views.jsx
> +        } else if (block_stratis_stopped_pool) {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230420-131050-f1115ac6-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-20 14:07 UTC, cockpituous commented on pkg/storaged/content-views.jsx
> +            used_for = block_stratis_stopped_pool;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230420-131050-f1115ac6-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-20 14:07 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +            return;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230420-131050-f1115ac6-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-20 14:07 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                        return start("keyring");
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230420-131050-f1115ac6-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-20 14:07 UTC, cockpituous commented on pkg/storaged/stratis-panel.jsx
> +    const action = <StorageButton onClick={() => start_pool(client, uuid, true)}><PlayIcon /></StorageButton>;
These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230420-131050-f1115ac6-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-20 14:07 UTC, cockpituous commented on pkg/storaged/stratis-panel.jsx
> +        detail: _("Stopped Stratis pool"),
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230420-131050-f1115ac6-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-20 14:07 UTC, cockpituous commented on pkg/storaged/stratis-panel.jsx
> +    function cmp_stopped_pool(uuid_a, uuid_b) {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230420-131050-f1115ac6-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-20 14:07 UTC, cockpituous commented on pkg/storaged/stratis-panel.jsx
> +            .map(uuid => stratis_stopped_pool_row(client, uuid));
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230420-131050-f1115ac6-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-24 12:56 UTC, mvollmer commented
Most of the uncovered stuff is about Stratis 2 (which only runs on rhel-8 and centos-8) and about showing stopped pools in the overview.  I'll modify the test to cover the latter.

2023-04-24 14:22 UTC, cockpituous commented on pkg/storaged/client.js
> +                client.stratis_start_pool = (uuid) => {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230424-131415-eca64e0e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-24 14:22 UTC, cockpituous commented on pkg/storaged/client.js
> +            proxy.StoppedPools = { };
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230424-131415-eca64e0e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-24 14:22 UTC, cockpituous commented on pkg/storaged/content-views.jsx
> +            used_for = block_stratis_stopped_pool;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230424-131415-eca64e0e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-24 14:23 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                Body: _("This pool can not be unlocked here because its key description is not in the expected format.")
These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230424-131415-eca64e0e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-24 14:23 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +            return;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230424-131415-eca64e0e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-24 14:23 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                .catch(() => [{ }])
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230424-131415-eca64e0e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-24 14:23 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                        return start("keyring");
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230424-131415-eca64e0e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-24 14:23 UTC, cockpituous commented on pkg/storaged/stratis-panel.jsx
> +    function cmp_stopped_pool(uuid_a, uuid_b) {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230424-131415-eca64e0e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/client.js
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/client.js
>          if (values.LockedPoolsWithDevs) {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/client.js
>                  const l = values.LockedPoolsWithDevs[uuid];
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/content-views.jsx
>              used_for = mount_point;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/content-views.jsx
>              type = _("Stratis member");
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                Body: _("This pool can not be unlocked here because its key description is not in the expected format.")
These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +            return;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                .catch(() => [{ }])
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                        return start("keyring");
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 11:15 UTC, cockpituous commented on pkg/storaged/stratis-panel.jsx
> +    function cmp_stopped_pool(uuid_a, uuid_b) {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230425-100703-453867ac-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-25 13:39 UTC, martinpitt requested changes
Thanks! A few comments, but if this is urgent (blocking too much), I can be talked into landing as-is and treating the comments as follow-ups.

2023-04-26 07:06 UTC, mvollmer commented on pkg/storaged/client.js
> +const stratis3_interface_revision = "r2";
"r2" was released with Stratis 3.2.0 in July, 2022. What do we have in RHEL 9.0?
Stratis 2 in RHEL 8 etc continues to work.

2023-04-26 07:06 UTC, mvollmer commented on pkg/storaged/stratis-details.jsx
> +                Body: _("This pool can not be unlocked here because its key description is not in the expected format.")
Hmm, yes.  This error can only happen for encrypted pools, but we don't say "unlock" anywhere anymore in the UI.

2023-04-26 07:10 UTC, mvollmer commented on pkg/storaged/stratis-panel.jsx
> +    const action = <StorageButton onClick={() => start_pool(client, uuid, true)}><PlayIcon /></StorageButton>;
> But this makes me wonder, why didn't and don't we have an icon for lock/stop?

Version "r0" didn't support that. "r2" does, but I thought it is a bit too much work...

2023-04-26 07:11 UTC, mvollmer commented on pkg/storaged/client.js
> +const stratis3_interface_revision = "r2";
RHEL 9.2 has Stratis 3.4.4.

2023-04-26 07:17 UTC, martinpitt commented on pkg/storaged/client.js
> +const stratis3_interface_revision = "r2";
RHEL 9.0 has stratis 2.4.2. For the record, this is fine for this PR, just collecting some evidence for https://issues.redhat.com/browse/COCKPIT-943

2023-04-26 07:18 UTC, martinpitt commented on pkg/storaged/stratis-details.jsx
> +                Body: _("This pool can not be unlocked here because its key description is not in the expected format.")
I see, it also talks about keys. Then I'm inclinded to keep it as-is, as it avoids breaking translations.

2023-04-26 07:21 UTC, mvollmer commented on test/verify/check-storage-stratis
> +            # Stop the pool (only works with Stratis 3)
c8s still has Stratis 2, like rhel-8.

2023-04-26 07:27 UTC, martinpitt commented on test/verify/check-storage-stratis
> +            # Stop the pool (only works with Stratis 3)
Ignore me, I read this condition wrongly.

2023-04-26 07:28 UTC, mvollmer commented on pkg/storaged/stratis-panel.jsx
> +    const action = <StorageButton onClick={() => start_pool(client, uuid, true)}><PlayIcon /></StorageButton>;
Also, stopping pools was introduced for testing, afaics, so I don't think it is an important operation to expose in Cockpit.  But for completeness, sure.  I'll put it in the plan.

2023-04-26 07:46 UTC, mvollmer commented on pkg/storaged/stratis-panel.jsx
> +    const action = <StorageButton onClick={() => start_pool(client, uuid, true)}><PlayIcon /></StorageButton>;
Sorry, forgot the link: https://github.com/stratis-storage/project/issues/296

2023-04-26 08:30 UTC, mvollmer commented on pkg/storaged/stratis-panel.jsx
> +    const action = <StorageButton onClick={() => start_pool(client, uuid, true)}><PlayIcon /></StorageButton>;
> It should at least get an `aria-label=` for screenreaders.

Added.

2023-04-26 09:15 UTC, martinpitt submitted a review, later dismissed
Danke!

2023-04-26 09:16 UTC, martinpitt commented
[EBUSY](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230426-083032-1009a86d-rhel-8-9-distropkg/log.html#345-1), that's #18707, retrying

2023-04-26 09:37 UTC, cockpituous commented on pkg/storaged/client.js
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230426-083032-1009a86d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-26 09:37 UTC, cockpituous commented on pkg/storaged/client.js
>          if (values.LockedPoolsWithDevs) {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230426-083032-1009a86d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-26 09:37 UTC, cockpituous commented on pkg/storaged/client.js
>                  const l = values.LockedPoolsWithDevs[uuid];
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230426-083032-1009a86d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-26 09:37 UTC, cockpituous commented on pkg/storaged/content-views.jsx
>              used_for = mount_point;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230426-083032-1009a86d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-26 09:37 UTC, cockpituous commented on pkg/storaged/content-views.jsx
>              type = _("Stratis member");
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230426-083032-1009a86d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-26 09:37 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                .catch(() => [{ }])
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230426-083032-1009a86d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 07:39 UTC, martinpitt commented
Dang, conflict with Katerina's recent PF cleanup. I fixed the (simple) conflict and FPed your branch.

2023-04-30 07:39 UTC, martinpitt approved these changes

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/client.js
> +                client.stratis_start_pool = (uuid) => {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/client.js
> +            proxy.StoppedPools = { };
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/client.js
> +                proxy.StoppedPools[uuid] = {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/content-views.jsx
> +        } else if (block_stratis_stopped_pool) {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/content-views.jsx
> +            used_for = block_stratis_stopped_pool;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                Body: _("This pool can not be unlocked here because its key description is not in the expected format.")
These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +            return;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                .catch(() => [{ }])
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/stratis-details.jsx
> +                        return start("keyring");
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 08:42 UTC, cockpituous commented on pkg/storaged/stratis-panel.jsx
> +    function cmp_stopped_pool(uuid_a, uuid_b) {
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18679-20230430-073933-28ce209d-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-04-30 10:24 UTC, merged