Issue-#18705-Fixed service name text overflow issue
cockpit-project/cockpit pull request #18744
Opened 2023-05-02 15:38 UTC by shubhit7

Fixes  #18705 

Fixed service name title overflow issue along with alignment of the kebab menu icon on the services page.

2023-05-02 17:27 UTC, KKoukiou requested changes
This incorrectly updates pixel test references. Please reset test/reference to HEAD^. 


Also the CSS workaround is not actually working. It just makes the kebab and switcher get in the same line like the description, which is actually more problematic than before for small screen sizes.

2023-05-02 17:51 UTC, shubhit7 commented
> 

Yes, so things were working fine on larger screens, and ideally the kebab menu should be aligned on the right.
I can add word break property to the title, that should fix the issue keeping the kebab menu icon towards right.

![Screenshot from 2023-05-02 23-16-54](https://user-images.githubusercontent.com/31029314/235744819-1f594391-0d1c-4fde-93fb-6f3bb90f0a46.png)

2023-05-03 11:21 UTC, KKoukiou requested changes

2023-05-03 11:21 UTC, KKoukiou commented on pkg/systemd/service-details.scss
> +  flex-wrap: nowrap;
Please allow the header to wrap - squeezing it all in one line is not what we want. 

I will let @garrett approve but I would expect the actions to go to next line but stay on the right side in mobile mode.

![Screen Shot 2023-05-03 at 13 20 27](https://user-images.githubusercontent.com/14921356/235902260-658ba41d-50a2-4d0e-83f2-7f34c9285484.png)

2023-05-03 12:51 UTC, garrett commented
I'm seeing this right now:

![Screen Shot 2023-05-03 at 13 56 37](https://user-images.githubusercontent.com/10246/235909261-085f3a9a-893a-4b7d-9a5b-0b0dd77f8342.png)

Problems:

1. The name in the breadcrumbs is not wrapping.
2. The name in the tiggered-by is not wrapping either.
3. The kebab menu icon (⋮) should be aligned to baseline*, not center. (_Or_ it should wrap to a new line, as @KKoukiou mentions.)

* Actually aligning to the baseline here is problematic due to the type of widgets and how the elements are constructed in the DOM. I tried it and it's bad; this is probably why it's aligned to the middle (or because someone thought they'd never wrap). If we align to the top, it has the appearance of baseline and the alignment looks correct:

![image](https://user-images.githubusercontent.com/10246/235920128-b0677cb2-04cb-4f61-a27b-d46c6417b24e.png)

If I (artificially, by adjusting the text in Firefox's dev tools) truncate the text to 1 line, it still looks correct:

![image](https://user-images.githubusercontent.com/10246/235921023-e5541ec0-ef0d-448e-aee0-99e65aec84f9.png)

2023-12-05 07:41 UTC, martinpitt commented
@garrett Do you have some time to check this CSS fix? Thanks!

2023-12-06 13:55 UTC, garrett requested changes
My comments @ https://github.com/cockpit-project/cockpit/pull/18744#issuecomment-1532976945 have still not been addressed.

Please fix.

2023-12-06 14:17 UTC, garrett commented
Screenshot:

![image](https://github.com/cockpit-project/cockpit/assets/10246/6a61904d-c523-4ed2-90e4-03c756bf999d)

You can see the breadcrumb is still not handled properly (it doesn't wrap) and the layout is still wrong — it's under instead of the side.

(I mentioned both of this in my comment above.)

2025-04-28 15:55 UTC, Venefilyn commented
Closing as this is fixed in main

2025-04-28 15:55 UTC, closed without merging