RTL bdi-css
cockpit-project/cockpit pull request #18795
Opened 2023-05-11 15:33 UTC by garrett

Here's my attempt at making something that's like `<bdi>`, but in CSS. This is an attempt to fix paths so they're `/etc/foo` instead of `etc/foo/` and other similar issues.

It depends on the big RTL PR, so it duplicates the commits. When that lands and this is rebased, then it will be just one commit, c8681b518cd6acf24af5a59f2d72d58f8ed04cbf.

Due to the new build system, we can extend classes across files too, so we don't even have to add a class in the JSX; it can be included in SCSS via `@extend` now.

So elements that are formatted by the OS, such as paths, IPv6 addresses, and probably some other things, should be formatted one of the following ways:

1. Wrapped by a `<bdi>` element.
2. Include the class, currently called `ct-rtl-passthrough`.
3. Use `ct-rtl-passthrough` via an `@extend` in SCSS, as shown here on the logs details page.

In most cases, especially one-off places, we probably want to use `<bdi>`. But it's good to have options, as we might not be able to use `<bdi>` everywhere it's needed

---

I have this as a WIP commit and a draft pull request because we need to:
- figure out if this name is what we want (or something else)
- apply the fix to more places throughout Cockpit

Please feel free to pick up this PR and work on it (and unmark as draft and rework the commit).

2023-05-11 16:48 UTC, martinpitt commented
Ze Big PR™ landed, so I pushed a rebase (no conflicts) and started a f-37 run for getting pixel checks.

2023-05-24 04:17 UTC, martinpitt requested changes
Thanks!

2023-05-24 04:17 UTC, martinpitt commented on pkg/systemd/logs.scss
> +  }
I find this too magic and detached from the code. This isn't even a cockpit specific CSS class, but changes every table. If that was just for a demo, that's fine of course, and it sounds like that's what you meant in the description.

I.e. for the real PR, let's rather use `<bdi>` or the class in JSX, at the points where we know it's computer-generated content.

2023-05-24 04:17 UTC, martinpitt commented on pkg/lib/page.scss
> +  unicode-bidi: plaintext;
"rtl-passthrough" is a bit confusingly named. I suppose it means "passthrough in an RTL context", not "pass through RTL text".

The "computer-generated" text will often be LTR, but we often also pass through translated messages from the system, which could be RTL. I just read https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi and it seems it uses the unicode markers contained in the string itself to decide that. I'm not actually sure that the strings will always have that, at least not if they are explicit Unicode control characters. If it determines that based on the character range, that's fine of course.

A good test case may be the motd box -- putting in LTR or RTL text (or both), and showing that on an LTR or RTL Cockpit language. We could add an integration pixel test for all four cases.

Another good test case could be the hwinfo page. Things like "model name" will almost certainly be Latin/English/LTR, and we can test that on an RTL page.

2023-05-24 06:33 UTC, KKoukiou reviewed
@martinpitt I late arrived to review this - and I am wondering wy don't we just use the html bdi element instead of doing the css hacks? Are you aware of the background story?

2023-05-24 06:45 UTC, martinpitt commented
@KKoukiou See the description -- I figure that's indeed the primary tool, and that the CSS rule was just a demo.

2023-06-07 12:45 UTC, garrett commented
We should generally use the bdi element. But there might be some cases where we can't wrap everything inside of a `<bdi>` element, hence this draft PR.

We should try to make a full pass through Cockpit to add the `<bdi>` element and then use something like this technique as a follow-up in the places where we cannot use `<bdi>` for whatever reasons (which we might discover when porting everything that's output by the system to bdi element).

2024-11-30 03:38 UTC, martinpitt commented
This is rather stale, and realistically we don't have the capacity/skill to "go through all of cockpit and add bdi tags" anytime soon. @garrett is this still relevant?

2025-05-28 06:48 UTC, closed without merging