test: Don't use CSS to replace DOM elements with arbitrary text
cockpit-project/cockpit pull request #18807
Opened 2023-05-15 08:53 UTC by mvollmer

The tricky CSS tricks turned out to be a bit too tricky in the case where the production CSS already uses ::after or ::before pseudo elements.  Our ListingTable component uses those alot for handling the mobile layout, for example.

Let's use to most straightforward way: setting the text of an element via injected JavaScript.

This might fail when React decided to render inbetween the call to set_mock and capturing of the actual screenshot.  But the tests keep the pages quiet during pixel testing anyway, so hopefully this will not happen in practice.

Another way this might fail is that React gets confused the next time it renders after the call to set_mock because the DOM has changed too much.  This can hopefully be prevented by only replacing the text of elements, and not their children.

2023-05-23 13:47 UTC, martinpitt commented
This looks nice! We might indeed get a few flakes, but let's address that if/when we actually do (like with halting the browser or so). Unfortunately this PR is conflicty, but you'll get my +1 as soon as you resolve.

2023-05-24 04:03 UTC, martinpitt requested changes
See above, clearing my review queue

2023-05-24 08:16 UTC, martinpitt approved these changes
Cheers!

2023-05-25 04:23 UTC, martinpitt commented
@mvollmer Sorry, this is conflicting again. Let's land this really quickly after pushing and approving this time..

2023-05-25 08:04 UTC, mvollmer commented
Green enough!

2023-05-25 08:04 UTC, merged