networkmanager: add pixel test for edit checkboxes
cockpit-project/cockpit pull request #19023
Opened 2023-06-26 15:51 UTC by jelly

Closes: #19019

---

It now looks as following:

![image](https://github.com/cockpit-project/cockpit/assets/67428/be246c1b-345a-4f0d-8361-fb76460d3d8e)

2023-06-26 22:11 UTC, cockpituous commented on pkg/networkmanager/network-interface.jsx
> +                <DescriptionListDescription className="networking-interface-status">
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19023-20230626-214120-185a4bfd-fedora-38-devel-expensive//Coverage/lcov/github-pr.diff.gcov.html)

2023-06-27 06:44 UTC, jelly commented
Hmm I just found this https://github.com/cockpit-project/cockpit/commit/5e8444c9745367f94c294f1a3ad1002f39b99abf#diff-f532f3dbbc8a77b7edbabbafb2778bd1c04c7a1b64b1ff5870a5f3880133fa37R113 which makes me think my solution might need to be re-adjusted?

2023-06-27 07:30 UTC, garrett requested changes
Yeah, this should not need a one-off fix. It looks like a PF related problem?

2023-06-27 09:15 UTC, jelly commented
> Yeah, this should not need a one-off fix. It looks like a PF related problem?

Maybe it is because this used to be a `span` and an `input` next to each other but now it's  a `span` and a `<div><input>`

2023-07-04 09:00 UTC, jelly commented
Final pixel test changes are mostly around buttons which seem fine https://cockpit-logs.us-east-1.linodeobjects.com/pull-1088-20230703-145202-8ab5302f-fedora-38/log.html

2023-07-21 12:39 UTC, KKoukiou approved these changes

2023-07-23 18:36 UTC, martinpitt commented
@jelly Not sure if you noticed, but there's pixel test failures -- the IPv6 address isn't stable, so needs to be ignored.

2023-07-24 07:40 UTC, jelly commented
> @jelly Not sure if you noticed, but there's pixel test failures -- the IPv6 address isn't stable, so needs to be ignored.

No, it seems we have a double spacing now?!!

2023-07-24 09:13 UTC, martinpitt approved these changes
Cheers! This was quite embarrassing indeed.

2023-07-24 09:18 UTC, garrett commented on pkg/networkmanager/networking.scss
> +.network-interface-settings div.pf-c-description-list__text button:not(:first-child) {
This is wrong. Never use div or span when selecting things in CSS. Also, usually try to not prefix with the element when selecting a class. (PF has famously changed elements several times, including recently.)

2023-07-24 09:19 UTC, garrett submitted a review, later dismissed
Comment inline

2023-07-24 09:20 UTC, garrett commented
I wasn't aware of this and fixed it as a commit in the PF5 PR @ https://github.com/cockpit-project/cockpit/pull/19111/commits/aa5e628917ccc91002b3445785aaea823a62d3c0

2023-07-24 09:24 UTC, martinpitt commented
FWIW, https://github.com/cockpit-project/cockpit/pull/19111/commits/aa5e628917ccc91002b3445785aaea823a62d3c0 seems fine to me as well. @jelly are you d'accord with closing this PR then?

2023-07-24 09:33 UTC, martinpitt commented
Yes, seems fine to rebase this PR after #19111 for adding the pixel test.

2023-07-26 05:53 UTC, jelly commented
> Yes, seems fine to rebase this PR after #19111 for adding the pixel test.

That is now, let's rebase :)

2023-07-26 06:47 UTC, jelly commented
Added pixel tests and only triggered required tests.

2023-07-26 06:59 UTC, martinpitt approved these changes
Pixel perfect! Thanks for adding this.

2023-07-28 12:21 UTC, jelly commented
> Cheers! This was quite embarrassing indeed.

Needed to re-introduce a class to exclude the random ipv6 address from getting excluded from the pixel comparison.

2023-07-28 12:50 UTC, martinpitt approved these changes
Dankjewel!

2023-07-28 13:19 UTC, merged