tools: don't parse --force as valid SHA
cockpit-project/cockpit pull request #19089
Opened 2023-07-10 14:06 UTC by jelly

Closes #18929

2023-07-11 09:00 UTC, allisonkarlitskaya requested changes
I feel like `shift` somewhere might help us.

2023-07-11 09:00 UTC, allisonkarlitskaya commented on tools/node-modules
> +    if [ "${1-}" != "--force" ]; then
This feels like the wrong fix...

What if we want `--force` and the SHA?

2023-07-24 09:03 UTC, martinpitt requested changes
Unit tests fail with

    fatal: Failed to resolve '' as a valid ref.

Thanks!

2023-07-24 09:31 UTC, jelly commented on tools/node-modules
> +    sha="${*-$(get_index_gitlink node_modules)}"
No, $1 is unset when you call `shift`. Honestly I find no joy anymore in POSIX shell

2023-07-24 09:32 UTC, jelly commented on tools/node-modules
> +    sha="${*-$(get_index_gitlink node_modules)}"
Hmm seems I am wrong https://unix.stackexchange.com/questions/174566/what-is-the-purpose-of-using-shift-in-shell-scripts

Either way, POSIX shell is so limiting it :)

2023-07-24 09:42 UTC, martinpitt commented on tools/node-modules
> +    sha="${*-$(get_index_gitlink node_modules)}"
No, that's precisely the point of `shift` -- `$2` becomes `$1` and so on.

2023-07-24 13:56 UTC, martinpitt submitted a review, later dismissed
LGTM, thanks!

2023-07-28 08:05 UTC, jelly commented
Hmpfft I have seem to have regressed something:

```[jelle@t14s][~/projects/cockpit/tools-node-modules-force]%./tools/node-modules checkout 7aec4437ed49da19b6a5d4952d9bce60dadbdfb1
  REMOVE   node_modules
  CLONE    node_modules  [ref: 7aec4437ed49da19b6a5d4952d9bce60dadbdfb1]
[jelle@t14s][~/projects/cockpit/tools-node-modules-force]%
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[jelle@t14s][~]%cd projects/cockpit/main
[jelle@t14s][~/projects/cockpit/main]%./tools/node-modules checkout 7aec4437ed49da19b6a5d4952d9bce60dadbdfb1
package.json - differ: byte 255, line 7

*** node_modules 7aec4437ed49da19b6a5d4952d9bce60dadbdfb1 doesn't match our package.json
*** refusing to automatically check out node_modules

Options:

    - tools/node-modules checkout --force     # disable this check

    - tools/node-modules install              # npm install with our package.json

./tools/node-modules: *** aborting

```

2023-07-28 08:07 UTC, jelly commented
POSIX sh is hard....
```
[jelle@t14s][~/projects/cockpit/tools-node-modules-force]%./tools/node-modules checkout 7aec4437ed49da19b6a5d4952d9bce60dadbdfb1
package.json - differ: byte 255, line 7

*** node_modules 7aec4437ed49da19b6a5d4952d9bce60dadbdfb1 doesn't match our package.json
*** refusing to automatically check out node_modules

Options:

    - tools/node-modules checkout --force     # disable this check

    - tools/node-modules install              # npm install with our package.json

./tools/node-modules: *** aborting

[jelle@t14s][~/projects/cockpit/tools-node-modules-force]%./tools/node-modules checkout
  REMOVE   node_modules
  CLONE    node_modules  [ref: afba1086947543932bf771197ee6eac6462b82ce]
```

2023-07-28 08:10 UTC, martinpitt commented
Yeah, using `false` and `true` in shell scripts is *highly* unusual. It's more idiomatic to use an empty string and "1" or so, and check with `[ -n "$flag" ]`

2023-07-28 09:26 UTC, jelly commented
> 



> Yeah, using `false` and `true` in shell scripts is _highly_ unusual. It's more idiomatic to use an empty string and "1" or so, and check with `[ -n "$flag" ]`

Want me to do that before reviewing?

2023-07-28 09:38 UTC, martinpitt commented
I'd prefer that, yes. booleans in shell are *weird* (not even mentioning the fact that 0 is true and 1 is false..)

2023-07-28 11:11 UTC, martinpitt approved these changes
Cheers!

2023-07-28 14:50 UTC, merged