users: allow administrators to change the user shell
cockpit-project/cockpit pull request #19090
Opened 2023-07-10 15:20 UTC by jelly

On Fedora a normal user can change it's own shell only through `lchsh` while other distributions do package `chsh` a setuid binary. As a compromise allow changing of the shell only for the Administrator and use `usermod` for changing the users shell which should be available on all supported systems by default.

---

# Allow administrators to change the user shell

Administrators can now change a users shell via the user account page.

![image](https://github.com/cockpit-project/cockpit/assets/67428/2c4895e4-e71c-4068-926b-5335d434b75d.png)

![image](https://github.com/cockpit-project/cockpit/assets/67428/379a3ff1-20c6-46db-a966-88e4d3bfa108.png)

2023-07-20 20:04 UTC, cockpituous commented on pkg/users/shell-dialog.js
> +                            return Promise.reject();
These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19090-20230720-190203-1197d5a9-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-07-21 06:47 UTC, jelly commented on pkg/users/shell-dialog.js
> +            id: "shell",
This should be `shell-dialog`.

2023-07-24 07:26 UTC, jelly commented
```
  File "/work/bots/make-checkout-workdir/test/verify/check-users", line 1273, in testChangeShell
    b.select_from_dropdown("#edit-user-shell", "/usr/bin/bash")
```

Arch has no `/usr/bin/bash` but `/bin/sh` for example.

2023-07-24 09:00 UTC, martinpitt requested changes
see above

2023-07-24 13:54 UTC, jelly commented
> Thanks! LGTM in general. Can you please fix the test, and add a screenshot and release note?

Did you mean, a pixel test?

2023-07-24 13:56 UTC, martinpitt commented
Yes, the pixel test needed adjustment too. I meant the failure on arch because of missing /usr/bin/bash, but it seems you already fixed that.

2023-07-24 14:05 UTC, martinpitt commented
@jelly Please light theme for the screenshots

2023-07-24 14:19 UTC, martinpitt approved these changes
Thanks!

2023-07-24 15:01 UTC, cockpituous commented on pkg/users/shell-dialog.js
> +                            return Promise.reject();
These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19090-20230724-135916-b1798e3a-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-07-24 16:21 UTC, merged