testlib: introduce two new CDP helper methods
cockpit-project/cockpit pull request #19148
Opened 2023-07-28 15:23 UTC by KKoukiou

One for closing the browser page and one for responding to alert windows.

This will help to test pages like Terminal or Anaconda WebUI which have special handling for window.unload.

2023-07-28 16:05 UTC, KKoukiou reviewed
Unit tests fail with unused method. I can add the test for the terminal page on monday.

2023-07-28 17:50 UTC, martinpitt commented
@KKoukiou Just add them to https://github.com/cockpit-project/cockpit/blob/main/tools/vulture-suppressions/testlib.py

2023-08-22 16:08 UTC, KKoukiou commented
Tests are no passing in CI but passing locally. I assume that is specific to chrome version? No other idea.

2023-08-23 03:46 UTC, martinpitt requested changes
Epharisto!

2023-08-23 03:46 UTC, martinpitt commented on test/verify/check-system-terminal
> +        b.handle_alert(accept=False)
This [often fails](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19148-20230822-140007-3bf44846-debian-stable-other/log.html#190-1) with "No dialog is showing". I. e. this needs some waiting loop for a dialog to actually appear. That isn't part of the DOM, and there is no JS API for checking whether an alert or confirm dialog is present (as both functions are blocking). But you could change `handle_alert` to retry a few times if it returns that precise error message?

2023-08-23 03:46 UTC, martinpitt commented on test/verify/check-system-terminal
> +
Also, this test should now check that the terminal is still alive after rejecting the confirmation, and that the session indeed gets closed after accepting it.

2023-11-13 12:45 UTC, KKoukiou commented
@martinpitt it was needed for some test, not that important https://github.com/rhinstaller/anaconda/pull/5018. you can close this.

2023-11-13 13:35 UTC, closed without merging