lib: Improve password fields
cockpit-project/cockpit pull request #19220
Opened 2023-08-22 12:33 UTC by skobyda

- Adds show/hide feature
- Adds a minimum to a progress bar
- Changes width of a progress bar
- Shows message indicating the strength of the password

Fixes https://github.com/cockpit-project/cockpit/issues/19199

[Screencast from 2023-08-22 14-30-21.webm](https://github.com/cockpit-project/cockpit/assets/42733240/231f89ec-04b4-474e-adb1-95b405f5e778)

2023-08-22 12:39 UTC, skobyda commented
Currently we these 4 levels of messages for passwords "Weak password" < "Good password" < "Strong password" < "Excellent password".
I'm not sure about the wording of the "Good password". It has score more than 33 but less than 66 (and is shown in yellow color). It's a password which is neither good nor bad.
Maybe it should be "acceptable password"? 
WDTY @garrett

2023-08-22 13:53 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                        <TextInput className="check-passwords" type={passwordHidden ? "password" : "text"} id={idPrefix + "-pw1"}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20230822-125449-71e7c813-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-08-22 13:53 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                            {passwordHidden ? <EyeIcon /> : <EyeSlashIcon />}
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20230822-125449-71e7c813-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-08-22 13:53 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                        <TextInput type={passwordConfirmHidden ? "password" : "text"} id={idPrefix + "-pw2"} autoComplete="new-password"
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20230822-125449-71e7c813-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-08-22 13:53 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                            {passwordConfirmHidden ? <EyeIcon /> : <EyeSlashIcon />}
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20230822-125449-71e7c813-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-08-23 02:47 UTC, martinpitt commented
needsdesign → moving to draft

2023-09-13 08:08 UTC, garrett commented
![image](https://github.com/cockpit-project/cockpit/assets/10246/05b006ba-9c6a-49f5-adb3-a1f7723fad42)

The contrast between the text and its background is not high enough. The color of the text should be the darker gold.

You can see this in PF demos:

![image](https://github.com/cockpit-project/cockpit/assets/10246/cfcda94e-4dc4-4b70-b08e-41c046205bd2)
https://www.patternfly.org/components/helper-text/html-demos/#helper-text-on-a-form

Here, you can see how PF uses brighter versions for icons, progress bars, etc. and the darker related color for text:
 
![image](https://github.com/cockpit-project/cockpit/assets/10246/c5983e75-b5ea-4858-9316-421278d4c918)
https://www.patternfly.org/components/alert/html/#alert-examples

Colors are specified here:

![image](https://github.com/cockpit-project/cockpit/assets/10246/8adc0352-df94-416c-9853-2353b7983323)
https://www.patternfly.org/design-foundations/colors/#primary-colors

- icon: `--pf-v5-global--warning-color--100`
- text: `--pf-v5-global--warning-color--200`

This isn't just a problem with the warning colors either, but it's most noticeable with it, as it has the least contrast. The other colors need to use the text variants too.

2023-09-13 08:14 UTC, garrett commented
There's a strange intermediate step where the strength meter is shown in a blue state without text, right at the beginning of typing:

![image](https://github.com/cockpit-project/cockpit/assets/10246/c144a27f-7c04-442a-8a7e-e20a47ce0f69)

2023-09-13 08:34 UTC, garrett commented
> I'm not sure about the wording of the "Good password". It has score more than 33 but less than 66 (and is shown in yellow color). It's a password which is neither good nor bad.
> Maybe it should be "acceptable password"?

Yes. :+1:

2023-09-18 12:03 UTC, skobyda commented
Updated: Changed to the text color, got rid of the blue progress bar without any text and from now on using "Acceptable" instead of "Good" password:

![Screenshot from 2023-09-18 14-02-44](https://github.com/cockpit-project/cockpit/assets/42733240/93bd5298-f13e-4e0c-90dc-b997c4fe8771)

2023-09-18 13:14 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +            setPasswordStrength();
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20230918-120248-8fd6ef98-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-18 13:14 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                        <TextInput className="check-passwords" type={passwordHidden ? "password" : "text"} id={idPrefix + "-pw1"}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20230918-120248-8fd6ef98-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-18 13:14 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                            {passwordHidden ? <EyeIcon /> : <EyeSlashIcon />}
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20230918-120248-8fd6ef98-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-18 13:14 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                        <TextInput type={passwordConfirmHidden ? "password" : "text"} id={idPrefix + "-pw2"} autoComplete="new-password"
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20230918-120248-8fd6ef98-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-18 13:14 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                            {passwordConfirmHidden ? <EyeIcon /> : <EyeSlashIcon />}
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20230918-120248-8fd6ef98-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-20 08:01 UTC, garrett requested changes
It's a lot better. Thanks!

However, the meter (progress bar) doesn't update based on the strength.

[Screencast from 2023-09-20 09-59-43.webm](https://github.com/cockpit-project/cockpit/assets/10246/1bf48a36-7f82-498c-9386-2d601b34bef3)

2023-10-16 14:07 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +            setPasswordStrength();
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231016-125913-03c3b351-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-16 14:07 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                        <TextInput className="check-passwords" type={passwordHidden ? "password" : "text"} id={idPrefix + "-pw1"}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231016-125913-03c3b351-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-16 14:07 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                            {passwordHidden ? <EyeIcon /> : <EyeSlashIcon />}
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231016-125913-03c3b351-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-16 14:07 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                        <TextInput type={passwordConfirmHidden ? "password" : "text"} id={idPrefix + "-pw2"} autoComplete="new-password"
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231016-125913-03c3b351-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-16 14:07 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                            {passwordConfirmHidden ? <EyeIcon /> : <EyeSlashIcon />}
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231016-125913-03c3b351-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-17 13:06 UTC, skobyda commented
Fixed the issue @garrett 

[Screencast from 2023-10-17 15-06-03.webm](https://github.com/cockpit-project/cockpit/assets/42733240/9c50c190-0faa-4a2c-b1d5-cc4f563aaa8b)

2023-10-26 10:49 UTC, garrett approved these changes
This was waiting on the password meter fix. Thanks! Approved.

(But please move that line of CSS.)

2023-10-26 10:49 UTC, garrett commented on pkg/lib/cockpit-components-password.scss
>  }
```suggestion
.ct-password-strength-meter {
  grid-gap: var(--pf-v5-global--spacer--xs);
  inline-size: var(--pf-v5-global--spacer--2xl);

  .pf-v5-c-progress__description, .pf-v5-c-progress__status {
    display: none;
  }
}
```

Parent CSS should be grouped together at the top. (This doesn't change anything, but it's better when it's not scattered.)

2023-10-30 15:00 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +                            {passwordConfirmHidden ? <EyeIcon /> : <EyeSlashIcon />}
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231030-135959-d54860fd-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-31 02:16 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +            setPasswordStrength();
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231031-011601-1bae20a1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-31 04:52 UTC, martinpitt requested changes
Thanks! The code changes look good, but the committed pixel changes [look](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231031-011601-1bae20a1-fedora-38-storage/log.html) [like](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231031-011601-1bae20a1-fedora-38-other/log.html) they revert #19520. I'll rebase this PR, fix the above two little issues, and re-do the pixel updates.

2023-10-31 04:52 UTC, martinpitt commented on pkg/lib/cockpit-components-password.jsx
> +                            aria-label={ passwordHidden ? _("Show password") : _("Hide password")}>
This is inconsistent spacing, and it also doesn't belong into the "lib: Change width of password progress" commit. This bit should be reverted.

2023-10-31 04:52 UTC, martinpitt commented on pkg/lib/cockpit-components-password.jsx
> -                              className={"ct-password-strength-meter " + variant}
This previous indentation is better to read IMHO.

2023-10-31 04:55 UTC, martinpitt commented on pkg/lib/cockpit-components-password.jsx
> -                              className={"ct-password-strength-meter " + variant}
Ah, other code in that file uses 4-space indentation as well, so ok.

2023-10-31 05:25 UTC, martinpitt commented
That looks much saner -- most tests are okay, just the [accounts tests](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231031-045839-c175744c-fedora-38-other/log.html) have the updated pixels for the reveal buttons. I'll push these.

2023-10-31 05:25 UTC, martinpitt approved these changes
Thanks!

2023-10-31 06:27 UTC, cockpituous commented on pkg/lib/cockpit-components-password.jsx
> +            setPasswordStrength();
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19220-20231031-052537-1ade659f-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-31 06:58 UTC, merged