storage: StorageBarMenu dropdown should not be plain
cockpit-project/cockpit pull request #19248
Opened 2023-08-27 18:18 UTC by leomoty

So this partially contributes to #19241

How it looks without plain:

![image](https://github.com/cockpit-project/cockpit/assets/1463740/613190a6-6757-442f-b28e-fd61e86c4d25)

![image](https://github.com/cockpit-project/cockpit/assets/1463740/2198eba7-bab3-4339-8fb5-cb1e3efabaf1)

How it looked before:

![image](https://github.com/cockpit-project/cockpit/assets/1463740/e3eb2357-efea-4769-9631-a6bc2df5b984)

![image](https://github.com/cockpit-project/cockpit/assets/1463740/af68b974-d046-42c0-a9e9-e5ccca15f7d1)

----

I am not entirely sure why plain was working like that in light mode? but the dark mode was correct (no background/border).

Also the side effect of this change is now that it is using the proper width / slimmer profile as shown by patternfly docs.

2023-08-28 05:50 UTC, martinpitt commented
Thanks! @mvollmer , can you have a look ? I started the f38/storage tests to get the updated pixels

2023-08-28 06:09 UTC, mvollmer commented
I can't say why we used `isPlain` to begin with, tbh... probably to get the kebab variant to look right.

Removing `isPlain` has two problems:

 - The narrower button looks out of place with regard to toher buttons:

![image](https://github.com/cockpit-project/cockpit/assets/3228183/61a7afc8-8a44-4b8f-80c2-cfbeb2860ac1)

 - The kebab version looks wrong:

![image](https://github.com/cockpit-project/cockpit/assets/3228183/265aff48-c2e9-479a-8203-7bddd8a081de)

2023-08-28 06:11 UTC, mvollmer requested changes

2023-08-28 06:12 UTC, mvollmer commented
I am suprised that even with `isPlain` we do get the blue background. Hmm.

2023-08-28 11:15 UTC, leomoty commented on pkg/storaged/storage-controls.jsx
> -                  isPlain
Done

2023-08-28 11:16 UTC, leomoty commented
Let me know if the proposed css change is acceptable, it uses the same padding as present elsewhere

2023-08-28 13:52 UTC, mvollmer submitted a review, later dismissed
Result looks good to me.

2023-08-28 13:53 UTC, mvollmer commented
Thanks! Let's run the tests!

2023-08-28 14:42 UTC, leomoty commented
@mvollmer seems like we have pixel tests changes, can you do those for me? I don't have the proper setup to get the VMs running at the moment

2023-08-29 05:22 UTC, martinpitt approved these changes
Thanks @leomoty ! I pushed the updated pixel test, it [looks great](https://github.com/cockpit-project/pixel-test-reference/compare/138b4916df120570e9fa9a3d947e91c73e65b3da..f46cdbdd623a1de7db8b4e0be7b5dd8495bb199e) and confirms the fix.

2023-08-29 05:34 UTC, martinpitt commented
Only re-triggering the f38 tests (pixels), the rest already succeeded in the previous round.

2023-08-29 06:09 UTC, merged