cockpit.js: Add debugging marking for translated strings
cockpit-project/cockpit pull request #19261
Opened 2023-08-30 07:14 UTC by marusak

I am still trying to understand how this would help, opening PR to demonstrate how we can do this.

Looks like this:
![Screenshot from 2023-08-30 09-12-56](https://github.com/cockpit-project/cockpit/assets/12330670/ff64cba2-bb17-4306-a6c0-851dac7c8a08)

2023-09-04 05:22 UTC, tpardeshi commented
Thanks @marusak for this pull request. 
Enabling pseudo-localization markers will make it easy in automation for referencing and locating strings in the application, when it is running in preferred target localized language. It will be used to test the marked strings are translated on UI or not. Sometimes there are few cases where the strings(ex. Name of product, Name of services, etc) displayed in English language, can be detected as a bug in automation but in reality those happen to be displayed in English only and not in localized language. So pseudo-localization markers makes it easy to deal with such test scenario in automation. It would be really helpful if these markers get implemented for Cockpit .Thanks !!

2023-09-25 08:59 UTC, marusak commented
@martinpitt what do you think about this? Could we land this and just see what output the translation team will provide us with?

2023-09-25 09:39 UTC, martinpitt requested changes
Thanks! I'm not super-convinced, but okay. This PR is already a month old, let's please refresh it and do the caching below.

2023-09-25 09:39 UTC, martinpitt commented on pkg/lib/cockpit.js
> +        if (window.localStorage.test_l10n === 'true')
This is a hot codepath. Could this be read once and then cached? You'd then need a reload of the page after setting the storage flag, but I think that's acceptable.

2023-12-01 09:53 UTC, martinpitt commented
@marusak is this still an issue?

2024-01-12 08:37 UTC, martinpitt approved these changes
This is indeed "meh", but let's see what they make from it. Thanks!

2024-01-12 08:41 UTC, merged