networking: Add support for OpenVPN
cockpit-project/cockpit pull request #19363
Opened 2023-09-21 07:49 UTC by subhoghoshX

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/dialogs-common.jsx
> +            dlg = <OpenVPNDialog {...properties} />;
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/interfaces.js
> +            set("vpn", "data", "a{ss}", settings.vpn.data);
These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +    const model = useContext(ModelContext);
These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +    const [dialogError, setDialogError] = useState("");
These 9 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +            console.log("an error occured => ", err);
These 13 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +                    type: 'vpn',
These 6 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +                        key: userKeyPath,
These 6 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +                        'remote-cert-tls': 'server'
These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +                    'service-type': 'org.freedesktop.NetworkManager.openvpn'
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +            setDialogError,
These 7 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +            idPrefix={idPrefix}
These 7 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-09-21 09:04 UTC, cockpituous commented on pkg/networkmanager/openvpn.jsx
> +        </NetworkModal>
These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20230921-075022-79cb9fd2-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-10-03 12:59 UTC, subhoghoshX commented
Greatly simplified config/cert generation, fetching to host machine and file upload tests.

2023-10-04 12:13 UTC, subhoghoshX commented
353 ms to 140 ms = 60.4% reduction
1050 ms to 225 ms (in fast 3G) = 78.6% reduction

I guess the refactoring was worth it...

2023-10-29 16:41 UTC, subhoghoshX commented
Generating Deffie-Hellman params on the CI can be an interesting [flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20231029-160315-b7795355-fedora-38-networking/log.html#40) as generating the (prime) numbers can take anywhere from less than a second to more than a minute...

2023-10-30 15:27 UTC, martinpitt requested changes
I had a first coarse look at the import and config file structure. I'm rather relieved to see that there is nothing fundamentally weird -- just some rather shallow and easy cleanups (see threads below). I did not look into the design aspect of this, that needs to wait until Garrett is back. I figure he has some ideas/opinions about the dialog and the optional import, and how to "merge" it with Wireguard to have a single "Add VPN" button. But let's get the technical underpinnings right in the meantime.

Thanks, this is great work!

2023-12-11 11:40 UTC, subhoghoshX commented
I've seen this flake https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20231211-103844-f3eb448f-fedora-38-networking/log.html#40 couple times by now, but it doesn't happen locally. I'll dig into it.

2023-12-11 11:41 UTC, subhoghoshX commented
I've seen this flake https://cockpit-logs.us-east-1.linodeobjects.com/pull-19363-20231211-103844-f3eb448f-fedora-38-networking/log.html#40 couple times by now, but it doesn't happen locally. I'll dig into it.

2023-12-15 15:27 UTC, subhoghoshX commented
> I had a first coarse look at the import and config file structure. I'm rather relieved to see that there is nothing fundamentally weird...

Well the most fundamentally weird thing is still that temporarily importing a connection with `nmcli`, accessing a `.nmconnection` file (which you questioned whether it's a defined API of NM, it seems to be, but with the recent netplan changes in ubuntu, in #19724, I can't guarantee anymore), creating a config file and cleaning up the mess. I don't like the whole approach overall.

On Monday I found this [KDE bug report](https://bugs.kde.org/show_bug.cgi?id=396530) and this [commit closing it](https://invent.kde.org/plasma/plasma-nm/-/commit/9b22aa548f02ef43f7275ab2f9ffa48bde8a1ba8) that uses a shared object exposed by NM. It's in C++, over the weekend I'll see if can do something similar in Python.

2024-12-16 08:19 UTC, closed without merging

2024-12-16 08:19 UTC, martinpitt commented
This is rather stale, needs a lot of work, and there's currently nobody who could pick that up. So I'm closing this now. We can reopen it if/when there is someone interested in working on this again. Thanks!