storage: Disable "Apply" in Teardown dialogs after error
cockpit-project/cockpit pull request #19579
Opened 2023-11-07 13:54 UTC by mvollmer

We want the user to cancel and start over.

2023-11-07 14:55 UTC, cockpituous commented on pkg/storaged/vdo-details.jsx
> +                        disable_on_error: usage.Teardown,
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19579-20231107-135515-193b7257-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-11-07 17:58 UTC, jelly approved these changes

2023-11-07 17:58 UTC, jelly requested changes
Unit tests fail:

# test/verify/check-storage-used:170:9: F841 Local variable `sleep_pid` is assigned to but never used

2023-11-08 12:40 UTC, cockpituous commented on pkg/storaged/vdo-details.jsx
> +                        disable_on_error: usage.Teardown,
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19579-20231108-113532-872713b2-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-11-08 12:40 UTC, cockpituous commented on pkg/storaged/vdo-details.jsx
> +                    disable_on_error: usage.Teardown,
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19579-20231108-113532-872713b2-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2023-11-08 15:08 UTC, jelly approved these changes

2023-11-08 15:09 UTC, merged