Single device btrfs filesystem presentation
cockpit-project/cockpit pull request #20012
Opened 2024-02-13 10:56 UTC by jelly

We probably still want to include stuff from the BtrfsVolumeCard, like the label. But not the list of devices.

2024-02-13 13:54 UTC, cockpituous commented on pkg/storaged/btrfs/volume.jsx
> +                                                    <StorageLink onClick={() => rename_dialog(block_btrfs, label)}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20012-20240213-120945-ddb5f9df-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2024-02-13 22:02 UTC, cockpituous commented on pkg/storaged/btrfs/volume.jsx
> +                                                    <StorageLink onClick={() => rename_dialog(block_btrfs, label)}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20012-20240213-200341-0a2fe28e-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2024-02-13 23:45 UTC, cockpituous commented on pkg/storaged/btrfs/volume.jsx
> +                                                    <StorageLink onClick={() => rename_dialog(block_btrfs, label)}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20012-20240213-221034-6d18bdb8-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2024-02-14 08:38 UTC, garrett requested changes
While I would like this in ASAP... sadly, this PR isn't working properly for me:

![image](https://github.com/cockpit-project/cockpit/assets/10246/3ba85c57-14dc-4f48-8989-1e5875af65b5)

Bugs:

- Everything is shown as "710" for the size
- Everything is "(not mounted)" except for root (which is at / and shows why the main subvolume should not be "/")
- Sizes and units are different in 3 places: The disk itself is 1.00 TB; the btrfs filesystem is 999 GB, btrfs subvolumes are 1,000 GB

Not a bug, even if it looks like one:

- Everything has a size of 1,000 GB (but I guess that's expected, as I don't have quotas, so any subvolume could grow, so this isn't a bug)

Here are the currently mounted btrfs volumes:

```
~ ❯ mount | grep btrfs
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a on /sysroot type btrfs (ro,relatime,seclabel,compress-force=zstd:5,ssd,discard=async,space_cache,subvolid=257,subvol=/root)
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a on / type btrfs (rw,relatime,seclabel,compress-force=zstd:5,ssd,discard=async,space_cache,subvolid=257,subvol=/root)
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a on /etc type btrfs (rw,relatime,seclabel,compress-force=zstd:5,ssd,discard=async,space_cache,subvolid=257,subvol=/root)
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a on /usr type btrfs (ro,relatime,seclabel,compress-force=zstd:5,ssd,discard=async,space_cache,subvolid=257,subvol=/root)
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a on /sysroot/ostree/deploy/fedora/var type btrfs (rw,relatime,seclabel,compress-force=zstd:5,ssd,discard=async,space_cache,subvolid=257,subvol=/root)
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a on /var type btrfs (rw,relatime,seclabel,compress-force=zstd:5,ssd,discard=async,space_cache,subvolid=257,subvol=/root)
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a on /var/home type btrfs (rw,relatime,seclabel,compress-force=zstd:5,ssd,discard=async,space_cache,subvolid=256,subvol=/home)
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a on /sysroot/ostree/deploy/fedora/var/home type btrfs (rw,relatime,seclabel,compress-force=zstd:5,ssd,discard=async,space_cache,subvolid=256,subvol=/home)
```

Sizes according to `df -h / /var/home` (I know it's not going to be 1:1 to btrfs, due to compression, but this seems way off):

```
Filesystem                                             Size  Used Avail Use% Mounted on
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a  930G  660G  182G  79% /
/dev/mapper/luks-3614bc40-66c8-47b0-96bb-680f0368131a  930G  660G  182G  79% /var/home
```

2024-02-14 08:41 UTC, garrett commented
Not related to this PR, but shows up in the screenshot above (and should be addressed in a follow-up):

Also, I don't know why "home" has a warning triangle. It's not obvious to me, and if I hover over it, nothing happens.

After visiting the details page, I see this:

![image](https://github.com/cockpit-project/cockpit/assets/10246/58d3c764-6b75-4907-b71f-79dd0e37fc57)

(I didn't change where it gets mounted. However, both /var/home/ and /home/ are the same place on Silverblue, as there's a symlink.)

"The filesystem is currently mounted on /var/home but will be mounted on /home on the next boot."

```
~ ❯ ls -ld /home /var/home
lrwxrwxrwx. 8 root root  8 Jul 27  2021 /home -> var/home/
drwxr-xr-x. 1 root root 66 Mar 29  2023 /var/home/
```

```
~ ❯ grep home /etc/fstab 
UUID=91d6971d-55d0-4fa0-a943-95d604453f8d /home                   btrfs   subvol=home,compress-force=zstd:5,x-systemd.device-timeout=0 0 0
```

2024-02-14 09:07 UTC, garrett approved these changes
These issues are all there on main as well (here's a screenshot of main, not this PR):

![image](https://github.com/cockpit-project/cockpit/assets/10246/7f75247c-89ce-404a-97a0-77108b2145b7)

So, I'm going to approve this PR as it only addresses the shuffling around, which looks like it works.

We should quickly follow-up with fixes for all the other points I raised above.

2024-02-14 10:39 UTC, cockpituous commented on pkg/storaged/btrfs/volume.jsx
> +                                                    <StorageLink onClick={() => rename_dialog(block_btrfs, label)}
This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20012-20240214-082353-6d18bdb8-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

2024-02-14 11:15 UTC, merged