Btrfs snapshot support
cockpit-project/cockpit pull request #20234
Opened 2024-03-28 15:47 UTC by jelly

Show snapshots of a subvolume

![image](https://github.com/cockpit-project/cockpit/assets/67428/aeb89c6f-e827-4efc-8d54-01f4d86f2f62)

2024-04-03 14:34 UTC, jelly commented
@mvollmer I thought a bit on how we could implement filtering:

We could come up with a system where we don't have to hardcode the "filters" in but we could register filters for pages which want that.

```
register_filter(display_name, property_name)
```

This registers a filter which lives in `pages.jsx`, then we use these filter with `property_name` and `filter_properties.`

Alternatively, we just hardcode filters:

```
PAGE_FILTER_SNAPSHOT = 'snapshot'
```

Page/Card can have `filter_properties` which contains the key we are interested for with the value. State can come later.

I'm not thinking of introducing something like a [filter component](https://www.patternfly.org/patterns/filters#checkbox-select). But maybe it is interesting to have something usable.

2024-04-04 08:00 UTC, mvollmer commented
> @mvollmer I thought a bit on how we could implement filtering:

I think this is a bit too much machinery. Let's just do what we need, and nothing more.

2024-04-04 16:14 UTC, jelly commented
Alright, after the discussion today in standup:

* First pass, show snapshots under a subvolume
* Second pass, hide snapshots

2024-05-23 14:16 UTC, garrett commented
@jelly: Yes, I think that's what we want. Good, simple summary.

 I think we (you and/or @mvollmer and I) agreed on that a while ago somewhere? Perhaps in a video call? Perhaps in an issue? I don't remember where, but if we all agree on that, then that's great.

To restart: I definitely do not want them on the overview (and never have) and I think the details pages are the right places for the snapshots.

2024-05-31 09:21 UTC, mvollmer commented
So the listing of snapshots on the page of their origin in a crossref table works. Let's nail down when to hide snapshots in the regular child tables.

What about this: snapshots are only included in a child table when they are on the top-level. Otherwise they are replaced with a row that summarizes them "(20 snapshots)". Clicking on that row will go to the parent of those snapshots.

Here is a made-up example (_without_ that rule applied):

![image](https://github.com/cockpit-project/cockpit/assets/3228183/fe7b37a6-93a6-4437-9a9e-b8f8b64dabb8)

Here, all the home-123 and images-123 subvolumes are snapshots. They would be omitted from the table and replaced with "(13 snapshots)".

But when going to the "snapshots" subvolume, they would be listed like they are now, because they are on the top-level in that table:

![image](https://github.com/cockpit-project/cockpit/assets/3228183/4d227f96-9c9a-46cd-85cf-0b7ebde49875)

2024-05-31 10:58 UTC, jelly commented
> So the listing of snapshots on the page of their origin in a crossref table works. Let's nail down when to hide snapshots in the regular child tables.

Good point.... I forgot about that...

So on the overview they need to go away, that is a requirement from @garrett 
 
> What about this: snapshots are only included in a child table when they are on the top-level. Otherwise they are replaced with a row that summarizes them "(20 snapshots)". Clicking on that row will go to the parent of those snapshots.

What view is this? The filesystem detail page? Can we differentiate the overview and filesystem detail page easily?

> Here is a made-up example (_without_ that rule applied):
> 
> ![image](https://private-user-images.githubusercontent.com/3228183/335517974-fe7b37a6-93a6-4437-9a9e-b8f8b64dabb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTA0MTUsIm5iZiI6MTcxNzE1MDExNSwicGF0aCI6Ii8zMjI4MTgzLzMzNTUxNzk3NC1mZTdiMzdhNi05M2E2LTQ0MzctOWE5ZS1iOGY4YjY0ZGFiYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTAwODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUyMmRlOTAxZDllODY1OGJiNTk4MWE4NjFhNjhiZGIzNWMyMDI0ZWIwNWMyYmE1NmM2YmIyOWI4NmVlOTQzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m3_zFaB7xxJb9BLynBg5tDgz6NOjHA056crmPIeDzVo)
> 
> Here, all the home-123 and images-123 subvolumes are snapshots. They would be omitted from the table and replaced with "(13 snapshots)".

Hmm feels a bit magical to me.
 
> But when going to the "snapshots" subvolume, they would be listed like they are now, because they are on the top-level in that table:
> 
> ![image](https://private-user-images.githubusercontent.com/3228183/335518934-4d227f96-9c9a-46cd-85cf-0b7ebde49875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTA0MTUsIm5iZiI6MTcxNzE1MDExNSwicGF0aCI6Ii8zMjI4MTgzLzMzNTUxODkzNC00ZDIyN2Y5Ni05YzlhLTQ2Y2QtODVjZi0wYjdlYmRlNDk4NzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTAwODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWUyZTNlYzRlNjc1OTNjYTM0NmNkMzExMjc1OWE2MzBmYzRmMzczNWE4ODI5ODEwODUyMzU0M2IxZGRjNTNmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3X6B6qneG5TOnlzUV294DVrfO6YsSWVx6B52fOqsNhI)

But then you wouldn't know it is a special subvolume would you? Better asked, how would we implement this:

```
for subvolume in parent_dir.subvolumes:
       if subvolume.parent__uid == parent_dir.uuid
            show()
      else
           hide()
```

The problem is a bit that BTRFS is very lenient and you can make everything everywhere without having to give it logical names.

> And of course they would also be listed on the page of their origin:
> 
> ![image](https://private-user-images.githubusercontent.com/3228183/335525992-271caa05-1480-4a8b-93af-88f289303918.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTA0MTUsIm5iZiI6MTcxNzE1MDExNSwicGF0aCI6Ii8zMjI4MTgzLzMzNTUyNTk5Mi0yNzFjYWEwNS0xNDgwLTRhOGItOTNhZi04OGYyODkzMDM5MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTAwODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTA0M2UwM2E2NTAwMGZhNTJmZTFkMzEwM2E5ODQyYzE0ZjJiM2RmOWJmYzg5ZjYxYWQ4ZWU3MjA2MGEwMDQ5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8ulUV7cGVMwIbxGg9RA0a_22cOpWLnHSAAXCxg2-9rg)

Agreed.

> In addition the page for a snapshot subvolume should have a link back to its origin:
> 
> ![image](https://private-user-images.githubusercontent.com/3228183/335526391-e09b843c-808c-4afd-a5c4-ace73b6a2c38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNTA0MTUsIm5iZiI6MTcxNzE1MDExNSwicGF0aCI6Ii8zMjI4MTgzLzMzNTUyNjM5MS1lMDliODQzYy04MDhjLTRhZmQtYTVjNC1hY2U3M2I2YTJjMzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTAwODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTJiMGZkZDJhOTA0ZjEwYzA4ODk0YzNiNTFhY2M5ZjU2NjFlOTJmM2E2YjA1NTE3MjU5MzY5NzhmMzdiZmJmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XKkOg_8EI0QI5VsfX6dR1bmv14RizN4kKp7Qs5Di-EQ)
> 
> Heere the could be a description row with "Snapshot origin data/home".

Stretch goal, but seems nice!

2024-05-31 11:48 UTC, mvollmer commented
> Better asked, how would we implement this:
> 
> ```
> for subvolume in parent_dir.subvolumes:
>        if subvolume.parent__uid == parent_dir.uuid
>             show()
>       else
>            hide()
> ```

So parent_uuid is the origin of the snaphot subvolume, and parent_dir is the parent subvolume, right?  In my example, "snapshots" is the parent of "home-1234", and "home" is the origin of "home-1234" (since it was created by "btrfs subvolume snapshot /run/butter/data/home /run/butter/data/snapshots/home-1234").

So your code above would not hide any snapshots in my example, since no snapshot subvolume has the subvolume as both parent and origin. It would only hide snapshots that are directly inside their origins, like the one created by "btrfs subvolume snapshot /run/butter/data/home /run/butter/data/home/snapshot-1".

In my understanding, we want to get rid of snapshots in our tables because there are too many of them and they are usually not interesting.

2024-05-31 11:52 UTC, mvollmer commented
> > What about this: snapshots are only included in a child table when they are on the top-level. Otherwise they are replaced with a row that summarizes them "(20 snapshots)". Clicking on that row will go to the parent of those snapshots.
> 
> What view is this? The filesystem detail page? Can we differentiate the overview and filesystem detail page easily?

That rule would apply to any ChildrenTable, thus to each page, overview and details.

We can distinguish overview  and details pages and we do that already: only the overview has icons, for example), But I propose we don't do that when deciding whether to hide snapshots. If they are distracting on the overview, they are also distracting elsewhere, no? And with the summary line, you can easily find the place that lists them all.

2024-05-31 11:55 UTC, mvollmer commented
Should we have actions on snapshots when they are listed in the crossrefs table? At least "Delete" seems appropriate.

2024-05-31 12:12 UTC, jelly commented
> > Better asked, how would we implement this:
> > ```
> > for subvolume in parent_dir.subvolumes:
> >        if subvolume.parent__uid == parent_dir.uuid
> >             show()
> >       else
> >            hide()
> > ```
> 
> So parent_uuid is the origin of the snaphot subvolume, and parent_dir is the parent subvolume, right? In my example, "snapshots" is the parent of "home-1234", and "home" is the origin of "home-1234" (since it was created by "btrfs subvolume snapshot /run/butter/data/home /run/butter/data/snapshots/home-1234").
> 
> So your code above would not hide any snapshots in my example, since no snapshot subvolume has the subvolume as both parent and origin. It would only hide snapshots that are directly inside their origins, like the one created by "btrfs subvolume snapshot /run/butter/data/home /run/butter/data/home/snapshot-1".

No this does indeed not work...

```
[root@fedora-40-127-0-0-2-2201 ~]# btrfs subvolume list -apuq /
ID 256 gen 838 parent 5 top level 5 parent_uuid -                                    uuid 13c51cda-d57a-0a45-a808-1785eca3bc28 path <FS_TREE>/root
ID 257 gen 838 parent 5 top level 5 parent_uuid -                                    uuid 9d64752d-1de6-2849-baac-696ce79f3a7b path <FS_TREE>/home
ID 258 gen 840 parent 5 top level 5 parent_uuid -                                    uuid bd3edcf1-e9b5-654a-96ec-6e62ee17d924 path <FS_TREE>/var
ID 259 gen 78 parent 258 top level 258 parent_uuid -                                    uuid b3735d93-91e0-1046-98f7-e377fafc1b3c path <FS_TREE>/var/lib/machines
ID 260 gen 836 parent 256 top level 256 parent_uuid -                                    uuid 6b5445f7-2d40-5c45-b914-9eedd47dd5cd path root/snapshots
ID 261 gen 836 parent 260 top level 260 parent_uuid 9d64752d-1de6-2849-baac-696ce79f3a7b uuid cf9b06e1-6141-0b42-b61c-5d2c920e88ab path <FS_TREE>/root/snapshots/today
```

> In my understanding, we want to get rid of snapshots in our tables because there are too many of them and they are usually not interesting. Isn't that the goal?

Yes, but you argued for showing them?

2024-05-31 12:12 UTC, jelly commented
> Should we have actions on snapshots when they are listed in the crossrefs table? At least "Delete" seems appropriate.

Sounds reasonable.

2024-05-31 12:27 UTC, mvollmer commented
> > In my understanding, we want to get rid of snapshots in our tables because there are too many of them and they are usually not interesting. Isn't that the goal?
> 
> Yes, but you argued for showing them?

Yes, but sparingly. Snapshots are also subvolumes and we need to offer all the functionality of subvolumes for them, somewhere. Maybe people want to mount them, or copy them back to their origin.

2024-05-31 15:40 UTC, jelly commented
Conclusion from standup with @mvollmer "Let's merge this and figure out filtering/hiding subvolumes later.

2024-05-31 17:22 UTC, cockpituous commented on pkg/storaged/btrfs/subvolume.jsx
> +            size: mounted && <StorageUsageBar stats={use} short />,
This added line is not executed by any test.

2024-06-03 09:33 UTC, cockpituous commented on pkg/storaged/btrfs/subvolume.jsx
> +            size: mounted && <StorageUsageBar stats={use} short />,
This added line is not executed by any test.

2024-06-03 10:55 UTC, cockpituous commented on pkg/storaged/btrfs/subvolume.jsx
> +            size: mounted && <StorageUsageBar stats={use} short />,
This added line is not executed by any test.

2024-06-03 11:00 UTC, jelly commented
@martinpitt do you mind taking the review over?

2024-06-07 11:37 UTC, jelly commented
Alternative idea, we have one list of subvolumes:

* Show subvolumes and snapshots different, either with a Label 
* Allow filtering of the table

2024-06-07 17:08 UTC, cockpituous commented on pkg/storaged/btrfs/subvolume.jsx
> +            size: mounted && <StorageUsageBar stats={use} short />,
This added line is not executed by any test.

2024-06-07 17:08 UTC, cockpituous commented on pkg/storaged/btrfs/subvolume.jsx
> +                    <StorageDescription title={_("Snapshot origin")} value={snapshot_origin.pathname} />
This added line is not executed by any test.

2024-06-18 08:11 UTC, mvollmer requested changes

2024-06-18 08:11 UTC, mvollmer commented on pkg/storaged/btrfs/subvolume.jsx
> +                    <StorageDescription title={_("Snapshot origin")} value={snapshot_origin.pathname} />
This should be a link, no?

2024-06-18 08:11 UTC, mvollmer commented on pkg/storaged/btrfs/subvolume.jsx
> +        register_crossref({
Let's add the "Delete" action here.

2024-06-20 14:45 UTC, mvollmer approved these changes
Thanks!

2024-06-20 15:50 UTC, cockpituous commented on pkg/storaged/btrfs/subvolume.jsx
> +            size: mounted && <StorageUsageBar stats={use} short />,
This added line is not executed by any test.

2024-06-21 08:39 UTC, merged

2025-01-25 17:39 UTC, 2nv2u commented
Can you add the timestamp of the snapshots to the overview and detail page?
Not very useful for subvolumes, but it means a lot for snapshots.

2025-01-26 09:34 UTC, jelly commented
> Can you add the timestamp of the snapshots to the overview and detail page? Not very useful for subvolumes, but it means a lot for snapshots.

subvolume list does not expose the time the snapshot is made. If you want this implement I think we have to stat the snapshot directory? Either way it would be useful to have a new issue if you want this feature request researched.

2025-01-26 17:12 UTC, 2nv2u commented
Yes that's correct, it only show in the stats of the snap shot itself `btrfs subvol show {snapshot}`, I'll create a ticket for this.