users: Fix crash on nonexisting lastlog
cockpit-project/cockpit pull request #20575
Opened 2024-06-11 16:05 UTC by martinpitt

If `lastlog` is not installed, and neither is `lastlog2`, `getLogins()` ran into an uncaught "not-found" exception due to the spawn failure. The page then never finished loading.

Move the lastlog call closer to where the output is parsed, and handle failure.

----

Spotted in https://github.com/cockpit-project/bots/pull/6491 . This makes the tests mostly work (other than of course the actual "last login" checks)

2024-06-11 16:32 UTC, allisonkarlitskaya commented
Moving the code down to that point separates a comment from the code it was attempting to explain.

Also (suggestion): how about using the empty string as an initializer instead of setting it in the catch block?

2024-06-11 16:33 UTC, allisonkarlitskaya requested changes

2024-06-11 16:33 UTC, allisonkarlitskaya commented on pkg/users/users.js
> +    let lastlog;
`= "";`?

2024-06-11 16:33 UTC, allisonkarlitskaya commented on pkg/users/users.js
>      // drop header and last empty line with slice
This comment goes with...

2024-06-11 16:33 UTC, allisonkarlitskaya commented on pkg/users/users.js
>      const promises = lastlog.split('\n').slice(1, -1).map(async line => {
...this code.

2024-06-11 19:45 UTC, martinpitt commented on pkg/users/users.js
> +    let lastlog;
No strong opinion. Changed.

2024-06-11 19:46 UTC, martinpitt commented on pkg/users/users.js
>      const promises = lastlog.split('\n').slice(1, -1).map(async line => {
Fixed, thanks!

2024-06-11 21:00 UTC, cockpituous commented on pkg/users/users.js
> +        console.warn(`Failed to run ${LastLogPath}: ${ex.toString()}`);
These 2 added lines are not executed by any test.

2024-06-12 09:13 UTC, allisonkarlitskaya approved these changes

2024-06-12 09:13 UTC, merged