pkg/sosreport: Generate sos reports in /var/tmp to display them
cockpit-project/cockpit pull request #20584
Opened 2024-06-13 14:02 UTC by naruxde

In this plugin, the static path "/var/tmp" is used to search for SOS reports. Due to configurations in the "sos" program, the path for creating the reports may differ from this path. In order to create the reports for this plugin findable, the "sos" call is passed the parameters "--tmp-dir" with the value "/var/tmp" in order to generate the reports in the right place.

fix: #19617

2024-06-16 10:31 UTC, jelly commented
This approach works around the issue we have on Ubuntu, on Ubuntu the sos config seems dump reports to `/tmp` instead of `/var/tmp` on RHEL/Fedora. We don't want to override the distribution default for this but instead read the config file or ask `sos` about where it dumps its reports and then adjust `pkg/sosreport/sosreport.jsx` to use that location in the UI and for `cockpit.spawn` invocations. As well as a test case where we change the sos report configuration path to something like `/sos-report` and check that Cockpit can handle that.

2024-06-16 10:35 UTC, jelly commented
Taking a quick look at `sos` it doesn't seem to report where it dumps the reports, so ideally we would ask `sos` to include a new option to get this information.

2024-06-28 13:36 UTC, martinpitt commented
Indeed the default /etc/sos/sos.conf on Debian/Ubuntu has tmp-dir = /tmp. We should totally respect that in the tests and not stomp over it. That's also quite feasible to parse at runtime.

@naruxde do you want to take a stab at this, or shall I look into it? Thanks!

2024-06-28 13:36 UTC, martinpitt requested changes
See discussion above.

2024-07-01 04:55 UTC, naruxde commented
> Indeed the default /etc/sos/sos.conf on Debian/Ubuntu has tmp-dir = /tmp. We should totally respect that in the tests and not stomp over it. That's also quite feasible to parse at runtime.
> 
> @naruxde do you want to take a stab at this, or shall I look into it? Thanks!

Hi @martinpitt! It would be great if you could take over. Unfortunately, I am only a Python developer and have too little experience with JavaScript to implement it, sorry 🙁.
It would be great if this plugin also ran on Debian/Ubuntu!

2024-07-01 06:18 UTC, martinpitt commented
@naruxde ok! Will send a PR, and follow up on #19617

2024-07-01 06:18 UTC, closed without merging