shell: Navigate to new host after adding one
cockpit-project/cockpit pull request #21004
Opened 2024-09-13 11:54 UTC by mvollmer

- [ ] #20826

2024-09-13 12:57 UTC, cockpituous commented on pkg/shell/hosts.jsx
> +        window.trigger_connection_flow = null;
These 2 added lines are not executed by any test.

2024-09-13 12:57 UTC, cockpituous commented on pkg/shell/hosts.jsx
> +                this.props.jump(addr);
These 3 added lines are not executed by any test.

2024-09-13 12:57 UTC, cockpituous commented on pkg/shell/hosts.jsx
> +            } catch (err) {
This added line is not executed by any test.

2024-09-13 12:57 UTC, cockpituous commented on pkg/shell/hosts.jsx
> +                    template: codes[err.problem] || "change-port",
This added line is not executed by any test.

2024-09-13 12:57 UTC, cockpituous commented on pkg/shell/hosts_dialog.jsx
> +            old_machine = null;
This added line is not executed by any test.

2024-09-13 12:57 UTC, cockpituous commented on pkg/shell/hosts_dialog.jsx
> +                        host_id_port = address + ":22";
These 2 added lines are not executed by any test.

2024-09-13 12:57 UTC, cockpituous commented on pkg/shell/hosts_dialog.jsx
> +            conn_options['host-key'] = machine.host_key;
These 4 added lines are not executed by any test.

2024-09-13 12:57 UTC, cockpituous commented on pkg/shell/indexes.jsx
> +                    window.sessionStorage.setItem("connection-warning-shown", "yes");
These 3 added lines are not executed by any test.

2024-10-09 14:36 UTC, garrett requested changes
This looks _mostly_ great. Thanks!

However: After I added a new host, I got the connect warning dialog and then the key dialog, all as expected. However, it didn't switch to that remote host. Instead, it stayed on the original host and the switcher persisted. 

I would have expected it to switch to the new host and the switcher to go away at the same time.

(I thought I spotted some regressions, like the host switcher not having a hover state, but it looks like that in main too, so I guess we picked up that regression elsewhere, in the past. I guess after we land the rework and reimplement the shell's UI, it'll be automatically fixed. Otherwise, I could send up a PR to fix the CSS outside of your changes.)

2024-10-11 09:16 UTC, mvollmer commented
Now part of #20826.

2024-10-11 09:16 UTC, closed without merging