Fix loading spinner for OAuth / Bearer token validation
cockpit-project/cockpit pull request #21326
Opened 2024-11-25 20:44 UTC by marvinruder

* Fixes #21325

2024-11-25 20:47 UTC, marvinruder commented
It looks like this loading spinner was never supposed to work outside of a certain button. The animation is fixed when applying `display: inline-flex` to every spinner, not just to those inside a `.pf-v5-c-button[spinning]`:

![Screenshot 2024-11-25 at 9 46 23 PM](https://github.com/user-attachments/assets/6ffca00d-0898-4d49-ae03-58fee83c556e)

2024-11-26 06:19 UTC, martinpitt requested changes

2024-11-26 06:19 UTC, martinpitt commented on pkg/static/login.scss
> +.spinner {
Thanks @marvinruder for fixing this! However, I think this breaks the other "spinner" in the "login-actions" form. That one is enabled/disabled dynamically:

pkg/static/login.js:        id("login-button").removeAttribute('spinning');
pkg/static/login.js:        id("login-button").setAttribute('spinning', "true");

To make this more targetted, I suppose this should keep the original selector, but add the new one:

```css
.pf-v5-c-button[spinning] .spinner,
#login-wait-validating .spinner {
```

2024-11-26 19:54 UTC, marvinruder commented
As mentioned in #21325, I adressed some more UI element issues:

- The selector `.login-pf .container .help-block` appears to apply only to the “Validating authentication token” text. The `help-block` class was probably applied to easily get `display: block` and a pretty margin. To fix the color, `#fff` was specified, which works in dark mode, but not in light mode. `color: unset` will reset the color to the default values, which work nicely on the background of both themes
- The spinner color is always white, which works in buttons on both themes, but not on the plain white background of the bright theme. `html:not(.pf-v5-theme-dark) #login-wait-validating .spinner` selects a spinner only when it is the one in the “Validating authentication token” dialog and only if the dark theme is not active.
- `.pf-v5-theme-dark a.pf-v5-c-button` selects links that are styled as buttons with the dark theme active, and applies the default text color `#fff`, which works great with the button styling. Without it, the button link text has a light blue color in dark mode, which looks faded.

2024-11-28 10:12 UTC, martinpitt approved these changes
Thanks a lot! This looks reasonable and doesn't break the non-oauth login page.

2024-11-28 10:12 UTC, merged