Add testing support for OpenSUSE Tumbleweed
cockpit-project/cockpit pull request #21335
Opened 2024-11-26 13:02 UTC by SludgeGirl

Hey!

First up, sorry for the size of this, I've tried to keep the commits as atomic as possible and provide as much information as I can, let me know if you need it improved or re-organized in any way. Secondly, sorry for the wait! 

This looks to largely fix most of the issues with Tumbleweed experiences when running the tests for it. There will be another PR opened against bots shortly, I'll link both together once it's opened

2024-11-28 10:03 UTC, martinpitt requested changes
*phew* that's a mouthful :grin Thanks for working through them!

To be honest, this is too big to ever have a chance to land. Please don't try to fix everything at once -- trust me, it's going to be such a yak shave that both you and me will just give up in desperation.

I suggest that you split this up into multiple smaller stages and pull requests.

 1. Start with a PR that clears away the generic stupid boring stuff, like ".gitignore: Ignore test results, the ruff fix, lease path to /run/dnsmasq, and similar. We can test and land that without an opensuse-tw image and test.

 2. Sort out the image fixes in https://github.com/cockpit-project/bots/pull/7143

 3. A minimal PR that fixes the spec, build system, PAM file, and `test/image-prepare` to work at all. After `bots/vm-run -s cockpit.socket opensuse-tumbleweed` you should be able to get a cockpit UI on http://1270.0.2:2201 which isn't completely broken. In that PR, take all commits which add test skips and squash them together.

 4. There will likely be more failures in the PR from 2., but that's fine -- at that point let's decide if we mark them as skipImage and enable opensuse-tumbleweed for all PRs (to avoid regressing it), or keep it as a manual test for the time being.

 5. Discuss/fix some general mechanics/approach/helpers for the /usr write problem, in particular `sed_file()`  that checks if the file exists in /usr/etc instead and copies it first. (that'd be my recommendation, it mirrors what admins would do).

 6. See what's left, and split out the complicated bits into their own PR.

So let's keep this as a draft, and split out PRs step by step until this becomes empty or small enough to be reviewable and fixable.

Thanks!

2024-12-04 10:42 UTC, Nykseli commented
Hi @martinpitt 

Thank you for taking the time to review the huge pile of commits.

It's close to the end of the year and both me and @SludgeGirl are a bit busy trying to get urgent things done before we are "forced" to take our unspent PTO. Meaning that, unfortunately, we'll have to move continuing working on this to start of next year.

Just letting you know in case you're wondering why there are no new PRs coming to your way. Thank you for always being so patient!

2024-12-04 10:58 UTC, martinpitt commented
@Nykseli Thanks for the heads-up! No worries, enjoy your holidays and talk to you next year!

2025-05-14 10:18 UTC, Venefilyn commented
Hey all! What's the current status of this now? Have we split out all the work to other PRs or are there stuff left to do?

2025-05-14 10:33 UTC, SludgeGirl commented
@Venefilyn I've got one branch ready and split out for it, but then the image refresh broke so there wasn't much point in it submitting it till we got it fixed. I'll try dig it back out and get it submitted at some point today or tomorrow

2025-05-14 10:43 UTC, Venefilyn commented
Ack no rush @SludgeGirl just wanted to make sure we don't forget about it

2026-04-16 13:53 UTC, jelly commented
Hi, we now run `opensuse-tumbleweed/other` in all our pull requests, of course other scenarios need to be ported but should we keep this pull request open or close it?

2026-04-21 07:11 UTC, SludgeGirl commented
@jelly I think this one's good to close now. Thanks @Lunarequest and to your team for all of the hard work getting this done

2026-04-21 07:11 UTC, closed without merging