lib: Give secondary buttons more contrast in toolbars
cockpit-project/cockpit pull request #21389
Opened 2024-12-05 14:30 UTC by mvollmer

Secondary buttons have a transparent background by default, which needs more contrast on grey backgrounds like in toolbars.

2024-12-05 15:07 UTC, martinpitt commented
Technical review :+1: . Happy to give a formal ack if you already agreed on this with Garrett someplace else. Thanks!

2024-12-10 08:01 UTC, martinpitt commented
@mvollmer would you mind putting a before/after screenshot? that may make it easier for @garrett to review.

2024-12-13 10:23 UTC, mvollmer commented
Pixel changes are here: https://github.com/cockpit-project/pixel-test-reference/compare/b8704b853a9ebd0f137c55ea95bc2e8b818a3148..89b3ed85d0006a22e767f6da77513a335b97558b

This clearly goes too far.... this PR also changes disabled buttons.

2024-12-13 12:36 UTC, mvollmer commented
The hostswitcher has changed in light mode:

https://cockpit-logs.us-east-1.linodeobjects.com/pull-21389-169b0f2e-20241213-110942-fedora-41/pixeldiff.html#TestHostSwitching-testBasic-edit-hosts

This _does_ increase the contrast, and now the buttons have the same background color as the text input box. So I guess it's correct in that sense and looks as intended.

2024-12-13 12:39 UTC, mvollmer commented
The rest of the pixel changes are as expected. For example, the secondary buttons on the Networking page now look like this in dark mode:

![image](https://github.com/user-attachments/assets/a83a0d4b-9d0e-4f4d-8eb3-fe1afcf1b198)

as opposed to:

![image](https://github.com/user-attachments/assets/3852e32a-64c8-4573-ba2a-5359ced3a1e5)

2025-01-08 13:16 UTC, garrett requested changes
That actually _decreases_ contrast between the background and the text, not increases it.

(referring to https://github.com/cockpit-project/cockpit/pull/21389#issuecomment-2541367979)

The way PatternFly is designed is to have secondary buttons inherit the background color.

Buttons are incorrect in all the screenshots. IIRC, the goal was to ensure that there is enough contrast between the text and background in certain circumstances (where the background that is bleeding through and text does not have enough contrast).

2025-01-08 14:07 UTC, mvollmer commented
> That actually _decreases_ contrast between the background and the text, not increases it.

Ah, I misunderstood which contrast we want to increase: I thought buttons should have a different background than their surroundings.

> The way PatternFly is designed is to have secondary buttons inherit the background color.

And we should keep that?

It all started with this [comment](https://github.com/cockpit-project/cockpit/pull/21356#issuecomment-2516980941) and screenshot:

![image](https://github.com/user-attachments/assets/0d96fab1-2ece-4925-a550-0ed43f8254b1)

You said:

> the widgets should all have a white background there, including the secondary button; they need contrast... the text on grey isn't enough contrast, and additionally the grey on the widgets make them look disabled

From that I thought that widgets should get the primary background color (white in light mode), including secondary buttons. I completely missed the "text on grey" part. :-(

So in this PR it looks like this in light mode:

![image](https://github.com/user-attachments/assets/23fe6c21-4f2c-4a6f-a04d-b14728a1bc01)

And this is dark mode now:

![image](https://github.com/user-attachments/assets/3b3a2f21-1a6e-4035-b6e9-313813ec6dd4)

In both modes, the secondary button has the same background as the text input (for example).

I am happy to just close this PR, of course, but if you think we should change how secondary buttons look, I am happy to do that as well. :-) But I can't tell right now what should be changed exactly.

2025-01-08 14:21 UTC, garrett commented
Yeah, this is clearly wrong:

![image](https://github.com/user-attachments/assets/d5013cfc-eb38-4ad7-b68d-6fe9f45e1d35)

The dropdowns and the button should have the white background. The grey background makes them not look like widgets, does not have enough contrast between the text and the background, and even makes the button look disabled. Those are all things that need fixing, and why it has a white background on main (unless that was changed recently and is then a big usability and accessibility bug if so) and should always have a white background.

2025-01-09 07:39 UTC, mvollmer commented
> Which component is providing that grey background?

It's a Toolbar, with our own styling:

```
.pf-v5-c-toolbar {
  --pf-v5-c-toolbar--BackgroundColor: var(--pf-v5-c-page__main-section--BackgroundColor);

  // Make toolbar stretch to all the available space and wrap up to two lines
  .pf-v5-c-toolbar__group:nth-child(3) {
    flex-grow: 1;
  }

  // Make text filter stretch to all the available space
  .pf-v5-c-toolbar__item.text-search, .journal-filters-grep {
    flex-grow: 1;
  }

  .text-help {
    padding-inline-start: var(--pf-v5-global--spacer--xs);
  }

  // Hide filters from advanced search dropdown entries which already exist in the toolbar
  .journal-filters-grep .pf-v5-c-panel__main-body {
    .pf-v5-c-form__group:nth-child(5), .pf-v5-c-form__group:nth-child(6) {
      display: none;
    }
  }

  .pf-v5-c-toolbar__expandable-content.pf-m-expanded .pf-v5-c-divider {
    display: none;
  }

  // FIXME: When porting the selects to the PF5 select implementation drop this
  .pf-v5-c-toolbar__item {
    align-self: center;
  }
}
```

I wasn't aware that toolbars normally don't have a grey background...

Oh, there is a FIXME that we can now act on. :)

2025-01-09 08:52 UTC, mvollmer commented
Ok, I have redone this. The CSS changes now only apply to the journal filter toolbar, and I hope I have also found a better way get the desired effect by setting some PF variables.

Dark mode is unchanged for now.

2025-01-09 10:11 UTC, mvollmer commented
Pixel changes are as expected: https://github.com/cockpit-project/pixel-test-reference/compare/c83ced24f3d8a9d0279808014598b9a85893d061..246a85aef9d47b950a61ac9327c0cd7cd1f0cdc8

2025-04-02 06:41 UTC, mvollmer commented
I guess this is obsolete now with Patternfly 6.

2025-04-02 06:41 UTC, closed without merging