metrics: show system boots in metrics
cockpit-project/cockpit pull request #21444
Opened 2024-12-17 11:06 UTC by jelly

Show a boot as an metric event in the historical metrics overview. A boot is likely to cause a high CPU/memory spikes so it is interesting for a system administrator to be aware of them. We obtain the boot information from systemd as `last` is deprecated and not all distros use lastlog2 while `journalctl` is freely available.

Closes: #15983

2024-12-17 12:13 UTC, cockpituous commented on pkg/metrics/metrics.jsx
> +                </div>
These 12 added lines are not executed by any test.

2024-12-17 12:13 UTC, cockpituous commented on pkg/metrics/metrics.jsx
> +        } else if (this.props.isExpanded && this.props.events) {
This added line is not executed by any test.

2024-12-17 12:13 UTC, cockpituous commented on pkg/metrics/metrics.jsx
> +            console.warn("journalctl --list-boots failed", exc);
These 2 added lines are not executed by any test.

2024-12-17 16:40 UTC, cockpituous commented on pkg/metrics/metrics.jsx
> +            console.warn("journalctl --list-boots failed", exc);
These 2 added lines are not executed by any test.

2024-12-18 08:23 UTC, martinpitt requested changes
Thanks! Some small stuff, but by and large looks good. I don't have an off-hand idea why it doesn't work on Ubuntu. Does that reproduce locally or is it a race?

The [arch failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21444-c8e37bf8-20241217-154109-arch-other/log.html#160-1) is weird, though:

> wait_js_cond(ph_in_text(".metrics-minute[data-minute='35']","Boot")): Error: actual text: 10:35 AMBoot

Like what now? The text is right there!?

2024-12-18 08:23 UTC, martinpitt commented on pkg/metrics/metrics.jsx
> -        this.setState({ packagekitExists, isBeibootBridge });
I think it makes sense to keep this, as determining these two are quick. Reading the journal may take several seconds.

2024-12-18 08:23 UTC, martinpitt commented on pkg/metrics/metrics.jsx
> +        this.setState({ packagekitExists, isBeibootBridge, boots });
Please move this into the try block (no need to set `boots` if it failed to scan), and only set `boots` here, see above.

2024-12-18 08:23 UTC, martinpitt commented on pkg/metrics/metrics.jsx
> +                                                                                   reboot.started.getHours() === date_time.getHours())
inconsistent indentation

2024-12-18 09:34 UTC, jelly commented
> Thanks! Some small stuff, but by and large looks good. I don't have an off-hand idea why it doesn't work on Ubuntu. Does that reproduce locally or is it a race?

Will check locally but so far wasn't able to reproduce any of this locally.
 
> The [arch failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-21444-c8e37bf8-20241217-154109-arch-other/log.html#160-1) is weird, though:
> 
> > wait_js_cond(ph_in_text(".metrics-minute[data-minute='35']","Boot")): Error: actual text: 10:35 AMBoot
> 
> Like what now? The text is right there!?

Right, can't reproduce this, so assume it is a race.

2024-12-18 13:30 UTC, jelly commented on pkg/metrics/metrics.jsx
> -
woops! Can fix in a repush

2024-12-18 14:25 UTC, cockpituous commented on pkg/metrics/metrics.jsx
> +            console.warn("journalctl --list-boots failed", exc);
These 2 added lines are not executed by any test.

2024-12-18 16:21 UTC, jelly commented
On Ubuntu the journal doesn't seem to get picked up?

```
root@m1:~# journalctl --list-boots
IDX BOOT ID                          FIRST ENTRY                 LAST ENTRY
 -1 3a67d55d86ea41549ac55950991222ae Wed 2024-12-18 15:17:51 UTC Mon 2021-03-08 11:45:01 UTC
  0 1776c19e4e9f48b99158f0a265b864c4 Wed 2024-12-18 15:15:37 UTC Wed 2024-12-18 15:15:40 UTC
root@m1:~# date
Mon Mar  8 11:50:41 UTC 2021
```

Versus for example Arch:

```
[root@m1 ~]# journalctl --list-boots
IDX BOOT ID                          FIRST ENTRY                 LAST ENTRY
 -1 d1b4578c55c1435f9f5aac81889f1999 Mon 2021-03-08 10:35:47 UTC Mon 2021-03-08 10:41:54 UTC
  0 bfd5c2d9a2b04503a636041533cd59fb Wed 2024-12-18 15:59:46 UTC Mon 2021-03-08 11:08:55 UTC
```

2024-12-19 08:44 UTC, martinpitt commented
So on Ubuntu, even if I remove all other system*.journal files and rename journal.journal to system.journal, the list-boots list is still wrong:
```
 0 a6fec5b7e903464e9899394e18e6f49b Mon 2020-08-17 14:00:03 UTC Mon 2021-03-08 10:52:01 UTC
```

`journalctl` indeed starts with "Aug 17" to "Sep 19" and then continues with a boot on March 8, which is utterly  wrong. These come from the `user@` logs.

2024-12-19 08:45 UTC, martinpitt commented
I pushed this rather simple diff (not quite simple to come up with it, but wrt. review):

```diff
--- test/verify/check-metrics
+++ test/verify/check-metrics
@@ -440,7 +440,10 @@ class TestHistoryMetrics(testlib.MachineCase):
             return
 
         m.upload(["verify/files/metrics-archives/journal.journal.gz"], "/tmp")
+        # we need to move all other existing journals out of the way, otherwise boot order is going back in time
         m.execute("""gunzip /tmp/journal.journal.gz
+                     systemctl stop systemd-journald
+                     rm /var/log/journal/*/*.journal
                      cp /tmp/journal.journal /var/log/journal/*/""")
         b.reload()
         b.enter_page("/metrics")

```

This works for me locally. Let the bots have their deliberations!

2024-12-19 09:48 UTC, cockpituous commented on pkg/metrics/metrics.jsx
> +            console.warn("journalctl --list-boots failed", exc);
These 2 added lines are not executed by any test.

2024-12-19 09:51 UTC, martinpitt approved these changes

2024-12-19 11:40 UTC, merged