Shell validation
cockpit-project/cockpit pull request #21449
Opened 2024-12-18 12:53 UTC by mvollmer

- [ ] #21425

2024-12-18 12:57 UTC, mvollmer commented
This is quite WIPy still...

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    throw new ValidationError();
These 3 added lines are not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a string: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a number: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a boolean: ${JSON.stringify(val)}`);
These 4 added lines are not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an object: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an array: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +                throw e;
These 3 added lines are not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +                throw e;
These 3 added lines are not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +            throw e;
These 3 added lines are not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        validation_error(`Field ${String(field)} is missing`);
These 2 added lines are not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
This added line is not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
These 4 added lines are not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/shell/nav.tsx
> +                    document.querySelector<HTMLElement>("#" + sel + " .pf-v5-c-text-input-group__text-input")?.focus();
This added line is not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/shell/nav.tsx
> +                                                this.props.jump(g.action.target);
These 2 added lines are not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/shell/shell-modals.tsx
> +                                    const locales = state.config.manifest.locales || {};
This added line is not executed by any test.

2024-12-18 14:06 UTC, cockpituous commented on pkg/shell/topnav.tsx
> +        (shell_manifest.docs ?? []).forEach(doc => {
This added line is not executed by any test.

2025-01-07 16:27 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
These 4 added lines are not executed by any test.

2025-01-09 11:21 UTC, martinpitt requested changes
Thanks @mvollmer ! I like the approach a lot -- explicit, clean, no new dependencies, and pleasant to use.

2025-01-09 11:21 UTC, martinpitt commented on pkg/base1/test-import-json.ts
> +        "record of numbers with a string");
Similar to the inconsistent array above, IMHO this should throw and ignore the value in its entirety.

2025-01-09 11:21 UTC, martinpitt commented on pkg/lib/import-json.ts
> +   object is invalid, it will be omitted. This doesn't happen
This is what I mentioned above: IMHO this isn't safe in general. Think about `"bridges": []` in the shell manifest. Silently ignoring a non-string argument from sudo or pkexec is potentially disastrous. It's of course less of an issue for docs or locales, but IMHO it would make more sense to be strict and completely ignore the value -- that will greatly increase the chance of catching bugs in our tests.

(Also, "conretely" typo)

2025-01-09 11:21 UTC, martinpitt commented on pkg/base1/test-import-json.ts
> +    assert.equal(validate("test input", 12, import_string, ""), "", "not a string");
Could you do "" → "default", to make it more obvious what that does?

2025-01-09 11:21 UTC, martinpitt commented on pkg/base1/test-import-json.ts
> +}
This is quite pleasant to read and cleanly and robustly typed. Neat! :clap

2025-01-09 11:21 UTC, martinpitt commented on pkg/base1/test-import-json.ts
> +                MAC: {
Sorry, I just have to ask: What does "MAC" mean in soccer context?

2025-01-09 11:21 UTC, martinpitt commented on pkg/base1/test-import-json.ts
> +                },
Can you please add a description comment before each scenario? Like, this one is probably "No stadium (it's optional)" or so

2025-01-09 11:21 UTC, martinpitt commented on pkg/lib/import-json.ts
> +    throw new ValidationError();
Couldn't hurt to pass on `msg` into the exception object?

2025-01-09 11:21 UTC, martinpitt commented on pkg/lib/import-json.ts
> +    if (typeof val == "number")
Bikeshedding: `NaN` is literally defined as "not a number", but its type is `number`. Shall we explicitly disallow that? (`!isNaN(val)`)

2025-01-09 11:21 UTC, martinpitt commented on pkg/shell/machines/machines.js
> +                manifests: import_manifests(cockpit.manifests)
I'm curious -- how many ts errors disappear with this? (do a before/after comparison with ts-relaxed?)

2025-01-09 14:34 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +    assert.deepEqual(import_array([1, 2, "c"], import_number), [1, 2], "array of numbers with a string");
Yes, this is the big philosophical question. Personally, I like the non-strict approach, but I have no problem with making this strict.

My best argument for making this strict is to amplify that something is wrong. If you make a mistake with your search terms, your whole page doesn't get loaded instead of some search terms being omitted.

2025-01-09 14:39 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +        import_record({ a: "a", b: "b", c: "c" }, import_string),
The "record" term is from the TypeScript utility class `Record<Keys, Type>`, which is indeed a Map or Dict, not a structure.

2025-01-09 14:41 UTC, mvollmer commented on pkg/lib/import-json.ts
> +   object is invalid, it will be omitted. This doesn't happen
Yeah, command lines are a very good example of something that better be rejected in its entirety.

2025-01-09 14:41 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +    assert.equal(validate("test input", 12, import_string, ""), "", "not a string");
Yes.

2025-01-09 14:42 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +                MAC: {
It's supposed to be the short form of "ManCity"...

2025-01-09 14:42 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +                },
Yep.

2025-01-09 14:53 UTC, mvollmer commented on pkg/lib/import-json.ts
> +    if (typeof val == "number")
Hmm, NaN is a valid value for IEEE floating point and included in the TypeScript type "number", so I think we should just accept it here.
 
The main point of this is to get something that conforms to a given TypeScript type, and Nan is in `number`.

https://github.com/microsoft/TypeScript/issues/28682#issuecomment-1563530381

2025-01-09 14:56 UTC, mvollmer commented on pkg/shell/machines/machines.js
> +                manifests: import_manifests(cockpit.manifests)
None. :-)

From TypeScripts point of view, manifests always were fully typed. What is different now is that we don't crash at run-time in random places with a invalid manifest anymore, but just output a validation error.

2025-01-09 15:00 UTC, martinpitt commented on pkg/lib/import-json.ts
> +    if (typeof val == "number")
Ack, let's keep it as-is. Not important.

2025-01-09 15:02 UTC, martinpitt commented on pkg/base1/test-import-json.ts
> +        import_record({ a: "a", b: "b", c: "c" }, import_string),
Ugh -- this is opposite to pretty much everywhere else https://en.wikipedia.org/wiki/Record_(computer_science) -- shame on you, MS.

2025-01-10 15:48 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +   object is invalid, it will be omitted. This doesn't happen
Put me also in the "reject outright" camp.

2025-01-10 16:10 UTC, allisonkarlitskaya requested changes

2025-01-10 16:10 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +export function import_optional<T, F extends keyof T>(res: T, obj: JsonObject, field: F, importer: (val: JsonValue) => T[F]): void {
(thinking out loud — not necessarily a very strong request for change or anything)

The way this function works is a bit weird.  The assumption that the name of the input key and output key are the same is probably true for most cases, but might not be what the user wants.  It also involves using mutable state, which I generally try to avoid if possible.

Two possible alternatives:
 - just write `null` or `undefined` explicitly to the dictionary.  That's what the equivalent code in the bridge does (although `str | None` is a lot more Pythonic — JS seems to be quite happy when just blindly deferencing things and getting `undefined`).
 - Do something like having this function return something like `{ F?: T }` and use it like:

```typescript
const myobj = {
  field: import_mandatory(input, "x", ...),
  ... import_optional(input, "y", ...),
  ... import_optional(input, "z", ...)
};
```

ie: the function will return either an empty dictionary or the dictionary to merge with the optional value.

I sort of like the `null` thing, personally.  It clashes with `in` and `?`, though...

2025-01-10 16:10 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +    if (obj[field as string] === undefined) {
More `as` abuse...

2025-01-10 16:10 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +        return val as JsonValue[];
You should try to get this working without resorting to unsafe casts.  The compiler has a fairly impressive set of narrowing mechanisms...

See also https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

2025-01-10 16:10 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +    validation_error(`Not an object: ${JSON.stringify(val)}`);
What if we want to add a "length" property to some future thing we store in manifests?

2025-01-10 16:10 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +        return val as JsonObject;
...as...

2025-03-03 18:02 UTC, mvollmer commented
Ouch, dropped the ball on this...

2025-03-04 09:38 UTC, mvollmer commented on pkg/lib/import-json.ts
> +   object is invalid, it will be omitted. This doesn't happen
Ok, convinced.

`import_Manifests` is a counter-example: We don't want to break all of Cockpit when one manifest is bad. But I guess we can easily write import_Manifests without import_record.

2025-03-04 09:39 UTC, mvollmer commented on pkg/lib/import-json.ts
> +    throw new ValidationError();
Hmm, when being strict, there is only one error, so we can do that.

2025-03-04 09:48 UTC, mvollmer commented on pkg/lib/import-json.ts
> +export function import_optional<T, F extends keyof T>(res: T, obj: JsonObject, field: F, importer: (val: JsonValue) => T[F]): void {
> I sort of like the null thing, personally. It clashes with in and ?, though...

I think we should omit fields in the output when they are not in the input (instead of setting them to undefined). There is a difference also in JavaScript, but I can't give any great example right now.

2025-03-04 09:49 UTC, mvollmer commented on pkg/lib/import-json.ts
> +export function import_optional<T, F extends keyof T>(res: T, obj: JsonObject, field: F, importer: (val: JsonValue) => T[F]): void {
> Do something like having this function return something like { F?: T } and use it like:

Yes, good idea!

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    throw new ValidationError();
These 3 added lines are not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a string: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a number: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a boolean: ${JSON.stringify(val)}`);
These 4 added lines are not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an object: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an array: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +                throw e;
These 3 added lines are not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +                throw e;
These 3 added lines are not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +            throw e;
These 3 added lines are not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        validation_error(`Field "${String(field)}" is missing`);
These 2 added lines are not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
This added line is not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
These 4 added lines are not executed by any test.

2025-03-04 10:40 UTC, cockpituous commented on pkg/shell/shell-modals.tsx
> +                                    const locales = state.config.manifest.locales || {};
This added line is not executed by any test.

2025-03-04 13:31 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +    import_json_object, import_optional, import_mandatory,
`get` is for getting the values of fields, `import` is for converting values from their external form to their internal one. That was my thinking.

2025-03-04 13:36 UTC, mvollmer commented on pkg/lib/import-json.ts
> +    validation_error(`Not an object: ${JSON.stringify(val)}`);
Yep, replaced with `Array.isArray`.

2025-03-04 13:43 UTC, mvollmer commented
OKPTALYALL.

This is another version that I am quite happy with.  Main changes:

 - Checking is strict now. (This means we need to write more client code when strictness is not wanted, as in import_Manifests, but that is okay.)
 - Optional fields are now done with "| undefined". This makes the importers for mandatory and optional fields very symmetric and allows us to construct the result in one go. TS no longer checks whether we use the right field names, but that's acceptable.

2025-03-04 14:36 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    throw new ValidationError(`JSON validation error for ${validation_path.join("")}: ${msg}`);
These 2 added lines are not executed by any test.

2025-03-04 14:36 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a string: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-04 14:36 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a number: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-04 14:36 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a boolean: ${JSON.stringify(val)}`);
These 4 added lines are not executed by any test.

2025-03-04 14:36 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an object: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-04 14:36 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an array: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-04 14:36 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Field "${String(field)}" is missing`);
This added line is not executed by any test.

2025-03-04 14:36 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
This added line is not executed by any test.

2025-03-04 14:36 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
These 5 added lines are not executed by any test.

2025-03-04 14:36 UTC, cockpituous commented on pkg/shell/shell-modals.tsx
> +                                    const locales = state.config.manifest.locales || {};
This added line is not executed by any test.

2025-03-04 18:49 UTC, allisonkarlitskaya requested changes
This looks a lot better than the last round, thanks!

I like how you avoid the `get_*()` variants but it comes at the cost of adding lots of `import_*` that you need to use instead.  Your `validate()` function is a somewhat compelling case for having the "import" functions free-standing though.  I do agree that "import" isn't the best name though: "as" would be nicer (as mentioned).  That's bikeshed material though.

In general a lot of my comments turn into "do this more like jsonutil".  Of course I'd have that opinion and you're absolutely free to ignore it and go your own way.  The ways are already pretty similar... Having things the same just for the sake of having them the same is potentially useful though, considering this is a single codebase...

The only real firm request here is about adding some clarifying comments.  Everything else can be considered drive-bys.

Thanks!

2025-03-04 18:49 UTC, allisonkarlitskaya commented on pkg/base1/test-import-json.ts
> +    import_json_object, import_optional, import_mandatory,
In Python we call this `as_*()` which kinda makes sense because it's effectively a checked downcast.

2025-03-04 18:49 UTC, allisonkarlitskaya commented on pkg/base1/test-import-json.ts
> +} from "import-json";
I see that you like double quotes.

2025-03-04 18:49 UTC, allisonkarlitskaya commented on pkg/base1/test-import-json.ts
> +import QUnit from 'qunit-tests';
I see that you like single quotes.

2025-03-04 18:49 UTC, allisonkarlitskaya commented on pkg/base1/test-import-json.ts
> +        name: import_mandatory(obj, "name", import_string),
It would be really cool to have a generic `get()` function here which had an optional `default` parameter.  If `default` was `undefined` (ie: not provided) then it would mean "value must be present in JSON" whereas if it was something else (including the most usual case of `null`) it would mean to use this value if the default value was missing.

I'm not a fan of using undefined for missing values.  TypeScript already has a rather colored (and confusing) history of its treatment of undefined vs. optional fields...

Of course, this all sounds a lot like "just copy what we did in jsonutil in the bridge" and I understand if you want to go a different way here, but there is definitely value in having things behaving similarly...

2025-03-04 18:49 UTC, allisonkarlitskaya commented on pkg/base1/test-import-json.ts
> +        players: import_mandatory(obj, "players", v => import_array(v, import_Player)),
This looks pretty cool.

In general I kinda like how your way avoids adding `get_*()` for `str`, `number`, `obj`, `objv`, and a thousand other things...

2025-03-04 18:49 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +        return with_validation_path(`.${String(field)}`, () => importer(obj[field]));
It might be interesting to capture the error raised by `importer` and augment it.  Consider some document like `{x: 0, y: 0, z: 0}` and then we call `import_mandatory(obj, "x", import_string)` and get the error "Not a string: 0".

2025-03-04 18:49 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +        return with_validation_path(`.${String(field)}`, () => importer(obj[field]));
Sorry.  I just found `with_validation_path()` and take this back.

But: not excellent how this is effectively implemented via global variable... do we have any other reasonable options there?

2025-03-04 18:49 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +        if (!(e instanceof ValidationError))
This block would definitely benefit from a comment explaining the two cases of errors that you intend to handle here and why they ought to be treated differently... I'm reasonably sure I understand it, but only "reasonably" :)

2025-03-04 18:49 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +        if (!(e instanceof ValidationError))
It might also read better if you inverted the logic: ie: handle `if (e instanceof ValidationError)` in a block and then have `throw e` as a trailing/`else`.  That would make it easier to see that you're basically just doing `catch e: ValidationError` except that JS doesn't have that feature...

2025-03-13 11:41 UTC, martinpitt requested changes
Thanks! I'm quite happy with this, just a few minor details. Most of my [previous revivew](https://github.com/cockpit-project/cockpit/pull/21449#pullrequestreview-2539549853) is resolved, there's just the "import vs. get" [naming bikeshedding](https://github.com/cockpit-project/cockpit/pull/21449#discussion_r1908560942) left, but @allisonkarlitskaya also covers this -- her review still has a few relevant things.

2025-03-13 11:41 UTC, martinpitt commented on pkg/base1/test-import-json.ts
> +    assert.throws(() => import_string(12), /JSON validation error for : Not a string: 12/, "not a string");
I suggest to cover `""` as well, as that often triggers bugs with "falsy?" checks.

2025-03-13 11:41 UTC, martinpitt commented on pkg/base1/test-import-json.ts
> +    assert.deepEqual(import_array([1, 2, 3], import_number), [1, 2, 3], "array of numbers");
Let's cover empty array

2025-03-13 11:41 UTC, martinpitt commented on pkg/lib/import-json.ts
> +    return !!val && typeof val == "object" && Array.isArray(val);
`isArray()` already deals fine with `undefined`, `null`, `NaN`, `{}` or other garbage. So the only reason to have your own function would be if you inspect the *contents* of `val`, i.e. that it doesn't contain some entries that are not representable in  JSON. But being a `JsonValue` ought to already enforce that, so I think this function is unnecessary.

2025-03-13 11:41 UTC, martinpitt commented on pkg/shell/manifests.ts
> +            res[pkg] = m;
Ah, so this takes care of (entirely) ignoring broken manifests but keeping the good ones. For a broken manifest, `validate()` would return the `null` default value that you gave it, right? And the importer already does `console.error()` to notify the user what's wrong. Did I get that right?

Can you please add an integration test (`check-shell-menu` feels quite appropriate, in testBasic()?) that adds an invalid manifest and ensures that (1) it's not shown in the menu, and (2) other menu items are?

2025-03-17 14:56 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +} from "import-json";
I don't care and use on or the other randomly...

2025-03-17 15:02 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +    assert.deepEqual(import_array([1, 2, 3], import_number), [1, 2, 3], "array of numbers");
Done.

2025-03-17 15:04 UTC, mvollmer commented on pkg/lib/import-json.ts
> +    return !!val && typeof val == "object" && Array.isArray(val);
Good point! Fixed.

2025-03-17 15:07 UTC, mvollmer commented on pkg/lib/import-json.ts
> +        return with_validation_path(`.${String(field)}`, () => importer(obj[field]));
The best way would indeed be to catch the error and augment it. I'll do that.

2025-03-17 16:31 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +        name: import_mandatory(obj, "name", import_string),
Hmm, I would like to retain the ability to distinguish a input of `{ }` from a input of `{ x: null }`.

If we have a importer that does `{ x: get(obj, "x", import_string, null) }`, then both these inputs will end up as `{ x: null }`.

Also, initially I didn't want to have any defaults or fallbacks in the importer code. The TypeScript interfaces should tell you directly what kind of JSON is acceptable. TypeScript doesn't have default values in interfaces, so I thought the importers shouldn't have them either. Ideally, we would auto-generate the importers directly from the TypeScript interfaces.

But, what about this compromise: We'll have both `get` with a fallback as you describe and will never retrurn `undefined`, and also `get_optional` that is exactly like `import_optional` now.

Most people would use `get` unless you really really need `get_optional`.

2025-03-17 16:33 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +        players: import_mandatory(obj, "players", v => import_array(v, import_Player)),
Now you get it. :-)

2025-03-17 16:34 UTC, mvollmer commented on pkg/lib/import-json.ts
> +        return with_validation_path(`.${String(field)}`, () => importer(obj[field]));
Done.

2025-03-17 16:34 UTC, mvollmer commented on pkg/lib/import-json.ts
> +        if (!(e instanceof ValidationError))
Done.

2025-03-17 16:41 UTC, mvollmer commented on pkg/base1/test-import-json.ts
> +        name: import_mandatory(obj, "name", import_string),
> Most people would use `get` unless you really really need `get_optional`.

Another argument against fallbacks: Old JavaScript code that consumes JSON raw will already have its own way of handling fallbacks for missing fields. When typing this old code and putting these import validation functions between JSON.parse and the old consumer, we would have to refactor the code to move the fallback logic into the validator. That's probably an improvement, but it would be nice to not make it a requirement.

For that reason, I'll keep using `get_optional` for the manifests and leave the existing fallback-handling code in place.

2025-03-17 16:53 UTC, mvollmer commented
@martinpitt, @allisonkarlitskaya, let's bikeshed the names! I am not strongly attached to `import`, but I think I'll fight `get`.

`get` means to me "retrieve something out of a whole based on some search criteria", like getting the value of a field of an object based on its name. That's appropriate for the old `import_mandatory` and `import_option`, which are now called `get` and `get_optional`.

For the rest I want a name that describes the process of taking some input and returning that input whole in some other form. "Import" fits, it imports goods from the wild, untyped lands of JSONia into the well-controlled trade union of TypeScriptinium, in a safe to use form.

What about `as_string`, `as_Player`, etc, as Lis has suggested?  I am happy with that.

2025-03-18 07:25 UTC, mvollmer commented
> > @martinpitt, @allisonkarlitskaya, let's bikeshed the names! I am not strongly attached to `import`, but I think I'll fight `get`.
> > What about `as_string`, `as_Player`, etc, as Lis has suggested? I am happy with that.
> 
> From my POV, I'm fine with either. As the PR author I'll let you choose. This is very cool, and it's fine if this has your Stallgeruch 😉

I tried renaming it all to `as_*` and I just don't like it... :-/ It implies to me that some real type casting is going on, like interpreting a string as a number... I'll keep it as `import_*`.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +            throw new ValidationError(undefined, e, p);
This added line is not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +            throw e;
This added line is not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a string: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a boolean: ${JSON.stringify(val)}`);
These 4 added lines are not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an object: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an array: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
These 2 added lines are not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        validation_error(`Field "${String(field)}" is missing`);
This added line is not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
This added line is not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/lib/import-json.ts
> +            throw e;
This added line is not executed by any test.

2025-03-18 08:34 UTC, cockpituous commented on pkg/shell/shell-modals.tsx
> +                                    const locales = state.config.manifest.locales || {};
This added line is not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +            throw new ValidationError(undefined, e, p);
This added line is not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +            throw e;
This added line is not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a string: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not a boolean: ${JSON.stringify(val)}`);
These 4 added lines are not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an object: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +    validation_error(`Not an array: ${JSON.stringify(val)}`);
This added line is not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
These 2 added lines are not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        validation_error(`Field "${String(field)}" is missing`);
This added line is not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +        return fallback;
This added line is not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/lib/import-json.ts
> +            throw e;
This added line is not executed by any test.

2025-03-19 17:11 UTC, cockpituous commented on pkg/shell/shell-modals.tsx
> +                                    const locales = state.config.manifest.locales || {};
This added line is not executed by any test.

2025-03-28 08:07 UTC, martinpitt approved these changes
Cheers! LGTM, this is a cool improvement!

2025-03-31 07:02 UTC, allisonkarlitskaya approved these changes
LGTM.  I'm not wild about the "import" thing, but what can you do? :bike::house:

2025-03-31 07:02 UTC, allisonkarlitskaya commented on pkg/lib/import-json.ts
> +        return with_validation_path(`.${String(field)}`, () => importer(obj[field]));
This looks a lot nicer than it was before and it was my main real gripe from the previous iteration.

2025-03-31 07:05 UTC, merged